var searchData=
[
  ['gaussbilinear2dfiniteelement',['GaussBiLinear2DFiniteElement',['../classmfem_1_1GaussBiLinear2DFiniteElement.html',1,'mfem']]],
  ['gaussbiquad2dfiniteelement',['GaussBiQuad2DFiniteElement',['../classmfem_1_1GaussBiQuad2DFiniteElement.html',1,'mfem']]],
  ['gausslinear2dfiniteelement',['GaussLinear2DFiniteElement',['../classmfem_1_1GaussLinear2DFiniteElement.html',1,'mfem']]],
  ['gausslineardiscont2dfecollection',['GaussLinearDiscont2DFECollection',['../classmfem_1_1GaussLinearDiscont2DFECollection.html',1,'mfem']]],
  ['gaussquad2dfiniteelement',['GaussQuad2DFiniteElement',['../classmfem_1_1GaussQuad2DFiniteElement.html',1,'mfem']]],
  ['gaussquadraticdiscont2dfecollection',['GaussQuadraticDiscont2DFECollection',['../classmfem_1_1GaussQuadraticDiscont2DFECollection.html',1,'mfem']]],
  ['geometry',['Geometry',['../classmfem_1_1Geometry.html',1,'mfem']]],
  ['geometryrefiner',['GeometryRefiner',['../classmfem_1_1GeometryRefiner.html',1,'mfem']]],
  ['geominfo',['GeomInfo',['../structmfem_1_1NCMesh_1_1GeomInfo.html',1,'mfem::NCMesh']]],
  ['gmressolver',['GMRESSolver',['../classmfem_1_1GMRESSolver.html',1,'mfem']]],
  ['gradientinterpolator',['GradientInterpolator',['../classmfem_1_1GradientInterpolator.html',1,'mfem']]],
  ['gridfunction',['GridFunction',['../classmfem_1_1GridFunction.html',1,'mfem']]],
  ['gridfunctioncoefficient',['GridFunctionCoefficient',['../classmfem_1_1GridFunctionCoefficient.html',1,'mfem']]],
  ['groupcommunicator',['GroupCommunicator',['../classmfem_1_1GroupCommunicator.html',1,'mfem']]],
  ['groupconvectionintegrator',['GroupConvectionIntegrator',['../classmfem_1_1GroupConvectionIntegrator.html',1,'mfem']]],
  ['grouptopology',['GroupTopology',['../classmfem_1_1GroupTopology.html',1,'mfem']]],
  ['gssmoother',['GSSmoother',['../classmfem_1_1GSSmoother.html',1,'mfem']]]
];
