var searchData=
[
  ['gaussbilinear2dfiniteelement',['GaussBiLinear2DFiniteElement',['../classmfem_1_1GaussBiLinear2DFiniteElement.html',1,'mfem']]],
  ['gaussbiquad2dfiniteelement',['GaussBiQuad2DFiniteElement',['../classmfem_1_1GaussBiQuad2DFiniteElement.html',1,'mfem']]],
  ['gaussintegrationrule',['GaussIntegrationRule',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gaussintegrationrule_3c_201_2c_20order_2f2_2b1_2c_20real_5ft_20_3e',['GaussIntegrationRule&lt; 1, Order/2+1, real_t &gt;',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gaussintegrationrule_3c_202_2c_20order_2f2_2b1_2c_20real_5ft_20_3e',['GaussIntegrationRule&lt; 2, Order/2+1, real_t &gt;',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gaussintegrationrule_3c_203_2c_20order_2f2_2b1_2c_20real_5ft_20_3e',['GaussIntegrationRule&lt; 3, Order/2+1, real_t &gt;',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gausslinear2dfiniteelement',['GaussLinear2DFiniteElement',['../classmfem_1_1GaussLinear2DFiniteElement.html',1,'mfem']]],
  ['gausslineardiscont2dfecollection',['GaussLinearDiscont2DFECollection',['../classmfem_1_1GaussLinearDiscont2DFECollection.html',1,'mfem']]],
  ['gaussquad2dfiniteelement',['GaussQuad2DFiniteElement',['../classmfem_1_1GaussQuad2DFiniteElement.html',1,'mfem']]],
  ['gaussquadraticdiscont2dfecollection',['GaussQuadraticDiscont2DFECollection',['../classmfem_1_1GaussQuadraticDiscont2DFECollection.html',1,'mfem']]],
  ['generalams',['GeneralAMS',['../classmfem_1_1GeneralAMS.html',1,'mfem']]],
  ['generalizedalpha2solver',['GeneralizedAlpha2Solver',['../classmfem_1_1GeneralizedAlpha2Solver.html',1,'mfem']]],
  ['generalizedalphasolver',['GeneralizedAlphaSolver',['../classmfem_1_1GeneralizedAlphaSolver.html',1,'mfem']]],
  ['genericintegrationrule',['GenericIntegrationRule',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_201_2c_200_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 1, 0, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_201_2c_201_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 1, 1, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2011_2c_204_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 11, 4, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2014_2c_205_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 14, 5, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2024_2c_206_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 24, 6, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2031_2c_207_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 31, 7, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_204_2c_202_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 4, 2, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_205_2c_203_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 5, 3, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_201_2c_200_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 1, 0, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_201_2c_201_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 1, 1, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_2012_2c_206_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 12, 6, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_2012_2c_207_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 12, 7, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_203_2c_202_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 3, 2, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_204_2c_203_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 4, 3, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_206_2c_204_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 6, 4, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_207_2c_205_2c_20real_5ft_20_3e',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 7, 5, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['geometricfactors',['GeometricFactors',['../classmfem_1_1GeometricFactors.html',1,'mfem']]],
  ['geometricmultigrid',['GeometricMultigrid',['../classmfem_1_1GeometricMultigrid.html',1,'mfem']]],
  ['geometry',['Geometry',['../classmfem_1_1Geometry.html',1,'mfem']]],
  ['geometrylist',['GeometryList',['../classmfem_1_1Mesh_1_1GeometryList.html',1,'mfem::Mesh']]],
  ['geometryrefiner',['GeometryRefiner',['../classmfem_1_1GeometryRefiner.html',1,'mfem']]],
  ['geominfo',['GeomInfo',['../structmfem_1_1NCMesh_1_1GeomInfo.html',1,'mfem::NCMesh']]],
  ['get',['Get',['../structmfem_1_1TElementTransformation_1_1Get.html',1,'mfem::TElementTransformation']]],
  ['ginkgoexecutor',['GinkgoExecutor',['../classmfem_1_1Ginkgo_1_1GinkgoExecutor.html',1,'mfem::Ginkgo']]],
  ['ginkgoiterativesolver',['GinkgoIterativeSolver',['../classmfem_1_1Ginkgo_1_1GinkgoIterativeSolver.html',1,'mfem::Ginkgo']]],
  ['ginkgopreconditioner',['GinkgoPreconditioner',['../classmfem_1_1Ginkgo_1_1GinkgoPreconditioner.html',1,'mfem::Ginkgo']]],
  ['gko_5fmfem_5fdestroy',['gko_mfem_destroy',['../classmfem_1_1Ginkgo_1_1gko__mfem__destroy.html',1,'mfem::Ginkgo']]],
  ['gmressolver',['GMRESSolver',['../classmfem_1_1Ginkgo_1_1GMRESSolver.html',1,'mfem::Ginkgo::GMRESSolver'],['../classmfem_1_1GMRESSolver.html',1,'mfem::GMRESSolver']]],
  ['gnutls_5fglobal_5fstate',['GnuTLS_global_state',['../classmfem_1_1GnuTLS__global__state.html',1,'mfem']]],
  ['gnutls_5fsession_5fparams',['GnuTLS_session_params',['../classmfem_1_1GnuTLS__session__params.html',1,'mfem']]],
  ['gnutls_5fsocketbuf',['GnuTLS_socketbuf',['../classmfem_1_1GnuTLS__socketbuf.html',1,'mfem']]],
  ['gnutls_5fstatus',['GnuTLS_status',['../classmfem_1_1GnuTLS__status.html',1,'mfem']]],
  ['gradcomponentcoeff',['GradComponentCoeff',['../classmfem_1_1GradComponentCoeff.html',1,'mfem']]],
  ['gradientgridfunctioncoefficient',['GradientGridFunctionCoefficient',['../classmfem_1_1GradientGridFunctionCoefficient.html',1,'mfem']]],
  ['gradientintegrator',['GradientIntegrator',['../classmfem_1_1GradientIntegrator.html',1,'mfem']]],
  ['gradientinterpolator',['GradientInterpolator',['../classmfem_1_1GradientInterpolator.html',1,'mfem']]],
  ['graph',['Graph',['../classGecko_1_1Graph.html',1,'Gecko']]],
  ['gridfunction',['GridFunction',['../classmfem_1_1GridFunction.html',1,'mfem']]],
  ['gridfunctioncoefficient',['GridFunctionCoefficient',['../classmfem_1_1GridFunctionCoefficient.html',1,'mfem']]],
  ['gridfunctionpumi',['GridFunctionPumi',['../classmfem_1_1GridFunctionPumi.html',1,'mfem']]],
  ['gridtransfer',['GridTransfer',['../classmfem_1_1GridTransfer.html',1,'mfem']]],
  ['groupcommunicator',['GroupCommunicator',['../classmfem_1_1GroupCommunicator.html',1,'mfem']]],
  ['groupconvectionintegrator',['GroupConvectionIntegrator',['../classmfem_1_1GroupConvectionIntegrator.html',1,'mfem']]],
  ['grouptopology',['GroupTopology',['../classmfem_1_1GroupTopology.html',1,'mfem']]],
  ['gssmoother',['GSSmoother',['../classmfem_1_1GSSmoother.html',1,'mfem']]]
];
