var searchData=
[
  ['datacollection',['DataCollection',['../classmfem_1_1DataCollection.html',1,'mfem']]],
  ['deltacoefficient',['DeltaCoefficient',['../classmfem_1_1DeltaCoefficient.html',1,'mfem']]],
  ['densematrix',['DenseMatrix',['../classmfem_1_1DenseMatrix.html',1,'mfem']]],
  ['densematrixeigensystem',['DenseMatrixEigensystem',['../classmfem_1_1DenseMatrixEigensystem.html',1,'mfem']]],
  ['densematrixinverse',['DenseMatrixInverse',['../classmfem_1_1DenseMatrixInverse.html',1,'mfem']]],
  ['densematrixsvd',['DenseMatrixSVD',['../classmfem_1_1DenseMatrixSVD.html',1,'mfem']]],
  ['densetensor',['DenseTensor',['../classmfem_1_1DenseTensor.html',1,'mfem']]],
  ['derivativeintegrator',['DerivativeIntegrator',['../classmfem_1_1DerivativeIntegrator.html',1,'mfem']]],
  ['dg_5finterface_5ffecollection',['DG_Interface_FECollection',['../classmfem_1_1DG__Interface__FECollection.html',1,'mfem']]],
  ['dgdiffusionintegrator',['DGDiffusionIntegrator',['../classmfem_1_1DGDiffusionIntegrator.html',1,'mfem']]],
  ['dgdirichletlfintegrator',['DGDirichletLFIntegrator',['../classmfem_1_1DGDirichletLFIntegrator.html',1,'mfem']]],
  ['dgindexer',['DGIndexer',['../classmfem_1_1DGIndexer.html',1,'mfem']]],
  ['dgtraceintegrator',['DGTraceIntegrator',['../classmfem_1_1DGTraceIntegrator.html',1,'mfem']]],
  ['diffusionintegrator',['DiffusionIntegrator',['../classmfem_1_1DiffusionIntegrator.html',1,'mfem']]],
  ['dim',['Dim',['../structmfem_1_1TFunctionCoefficient_1_1Dim.html',1,'mfem::TFunctionCoefficient']]],
  ['dim_3c_201_2c_20dummy_20_3e',['Dim&lt; 1, dummy &gt;',['../structmfem_1_1TFunctionCoefficient_1_1Dim_3_011_00_01dummy_01_4.html',1,'mfem::TFunctionCoefficient']]],
  ['dim_3c_202_2c_20dummy_20_3e',['Dim&lt; 2, dummy &gt;',['../structmfem_1_1TFunctionCoefficient_1_1Dim_3_012_00_01dummy_01_4.html',1,'mfem::TFunctionCoefficient']]],
  ['dim_3c_203_2c_20dummy_20_3e',['Dim&lt; 3, dummy &gt;',['../structmfem_1_1TFunctionCoefficient_1_1Dim_3_013_00_01dummy_01_4.html',1,'mfem::TFunctionCoefficient']]],
  ['discreteinterpolator',['DiscreteInterpolator',['../classmfem_1_1DiscreteInterpolator.html',1,'mfem']]],
  ['discretelinearoperator',['DiscreteLinearOperator',['../classmfem_1_1DiscreteLinearOperator.html',1,'mfem']]],
  ['divdivintegrator',['DivDivIntegrator',['../classmfem_1_1DivDivIntegrator.html',1,'mfem']]],
  ['divergencefreeprojector',['DivergenceFreeProjector',['../classmfem_1_1miniapps_1_1DivergenceFreeProjector.html',1,'mfem::miniapps']]],
  ['divergenceinterpolator',['DivergenceInterpolator',['../classmfem_1_1DivergenceInterpolator.html',1,'mfem']]],
  ['domainlfintegrator',['DomainLFIntegrator',['../classmfem_1_1DomainLFIntegrator.html',1,'mfem']]],
  ['dsmoother',['DSmoother',['../classmfem_1_1DSmoother.html',1,'mfem']]],
  ['dstable',['DSTable',['../classmfem_1_1DSTable.html',1,'mfem']]],
  ['dynamicvectorlayout',['DynamicVectorLayout',['../classmfem_1_1DynamicVectorLayout.html',1,'mfem']]]
];
