MFEM: VectorRestrictedCoefficient Class Reference
VectorRestrictedCoefficient Class Reference
VectorCoefficient defined on a subset of domain or boundary attributes.
#include <coefficient.hpp>
Public Member Functions
VectorRestrictedCoefficient (VectorCoefficient &vc, Array< int > &attr)
virtual void Eval (Vector &V, ElementTransformation &T, const IntegrationPoint &ip)
Private Attributes
VectorCoefficient * c
Array< int > active_attr
Detailed Description
VectorCoefficient defined on a subset of domain or boundary attributes.
Definition at line 284 of file coefficient.hpp.
Constructor & Destructor Documentation
VectorRestrictedCoefficient::VectorRestrictedCoefficient (VectorCoefficient & vc, Array< int > & attr) [inline]
Definition at line 291 of file coefficient.hpp.
References active_attr, c, and Array< T >::Copy().
Member Function Documentation
void VectorRestrictedCoefficient::Eval (Vector & V, ElementTransformation & T, const IntegrationPoint & ip) [virtual]
Implements VectorCoefficient.
Definition at line 115 of file coefficient.cpp.
References active_attr, ElementTransformation::Attribute, c, VectorCoefficient::Eval(), Vector::SetSize(), and VectorCoefficient::vdim.
Member Data Documentation
Array<int> VectorRestrictedCoefficient::active_attr [private]
Definition at line 288 of file coefficient.hpp.
Referenced by Eval(), and VectorRestrictedCoefficient().
VectorCoefficient* VectorRestrictedCoefficient::c [private]
Definition at line 287 of file coefficient.hpp.
Referenced by Eval(), and VectorRestrictedCoefficient().
The documentation for this class was generated from the following files:
coefficient.hpp
coefficient.cpp