MFEM: VectorCoefficient Class Reference
VectorCoefficient Class Reference
#include <coefficient.hpp>
Public Member Functions
VectorCoefficient (int vd)
int GetVDim ()
Returns dimension of the vector.
void Eval (DenseMatrix &M, ElementTransformation &T, const IntegrationRule &ir)
virtual void Eval (Vector &V, ElementTransformation &T, const IntegrationPoint &ip)=0
virtual ~VectorCoefficient ()
Protected Attributes
int vdim
Detailed Description
Definition at line 187 of file coefficient.hpp.
Constructor & Destructor Documentation
VectorCoefficient::VectorCoefficient (int vd) [inline]
Definition at line 194 of file coefficient.hpp.
References vdim.
virtual VectorCoefficient::~VectorCoefficient () [inline, virtual]
Definition at line 205 of file coefficient.hpp.
Member Function Documentation
void VectorCoefficient::Eval (DenseMatrix & M, ElementTransformation & T, const IntegrationRule & ir)
Definition at line 52 of file coefficient.cpp.
References DenseMatrix::GetColumnReference(), IntegrationRule::GetNPoints(), IntegrationRule::IntPoint(), ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), and vdim.
Referenced by VectorFEMassIntegrator::AssembleElementMatrix(), ConvectionIntegrator::AssembleElementMatrix(), VectorFEDomainLFIntegrator::AssembleRHSElementVect(), VectorBoundaryLFIntegrator::AssembleRHSElementVect(), VectorDomainLFIntegrator::AssembleRHSElementVect(), GridFunction::ComputeH1Error(), GridFunction::ComputeL1Error(), GridFunction::ComputeL2Error(), GridFunction::ComputeMaxError(), GridFunction::ComputeW11Error(), VectorRestrictedCoefficient::Eval(), RT0TetFiniteElement::Project(), RT1HexFiniteElement::Project(), RT0HexFiniteElement::Project(), Nedelec1TetFiniteElement::Project(), Nedelec1HexFiniteElement::Project(), RT2QuadFiniteElement::Project(), RT1QuadFiniteElement::Project(), RT1TriangleFiniteElement::Project(), RT0QuadFiniteElement::Project(), RT0TriangleFiniteElement::Project(), BiQuadPos2DFiniteElement::Project(), NodalFiniteElement::Project(), VectorFiniteElement::Project_ND(), VectorFiniteElement::Project_RT(), and GridFunction::ProjectBdrCoefficientNormal().
virtual void VectorCoefficient::Eval (Vector & V, ElementTransformation & T, const IntegrationPoint & ip) [pure virtual]
Implemented in VectorConstantCoefficient, VectorFunctionCoefficient, VectorArrayCoefficient, VectorGridFunctionCoefficient, and VectorRestrictedCoefficient.
int VectorCoefficient::GetVDim () [inline]
Returns dimension of the vector.
Definition at line 197 of file coefficient.hpp.
References vdim.
Referenced by VectorFEMassIntegrator::AssembleElementMatrix(), VectorBoundaryLFIntegrator::AssembleRHSElementVect(), VectorDomainLFIntegrator::AssembleRHSElementVect(), BiQuadPos2DFiniteElement::Project(), NodalFiniteElement::Project(), VectorFiniteElement::Project_ND(), and GridFunction::ProjectBdrCoefficientNormal().
Member Data Documentation
int VectorCoefficient::vdim [protected]
Definition at line 190 of file coefficient.hpp.
Referenced by VectorRestrictedCoefficient::Eval(), VectorArrayCoefficient::Eval(), VectorFunctionCoefficient::Eval(), Eval(), GetVDim(), VectorCoefficient(), and VectorArrayCoefficient::~VectorArrayCoefficient().
The documentation for this class was generated from the following files:
coefficient.hpp
coefficient.cpp