MFEM: NURBSFECollection Class Reference
NURBSFECollection Class Reference
Arbitrary order non-uniform rational B-splines (NURBS) finite elements.
#include <fe_coll.hpp>
Public Member Functions
NURBSFECollection (int Order)
int GetOrder () const
void UpdateOrder (int Order)
Change the order of the collection.
void Reset () const
virtual const FiniteElement * FiniteElementForGeometry (int GeomType) const
virtual int DofForGeometry (int GeomType) const
virtual int * DofOrderForOrientation (int GeomType, int Or) const
virtual const char * Name () const
virtual ~NURBSFECollection ()
Private Member Functions
void Allocate (int Order)
void Deallocate ()
Private Attributes
NURBS1DFiniteElement * SegmentFE
NURBS2DFiniteElement * QuadrilateralFE
NURBS3DFiniteElement * ParallelepipedFE
char name [16]
Detailed Description
Arbitrary order non-uniform rational B-splines (NURBS) finite elements.
Definition at line 130 of file fe_coll.hpp.
Constructor & Destructor Documentation
NURBSFECollection::NURBSFECollection (int Order) [inline, explicit]
Definition at line 143 of file fe_coll.hpp.
References Allocate().
virtual NURBSFECollection::~NURBSFECollection () [inline, virtual]
Definition at line 166 of file fe_coll.hpp.
References Deallocate().
Member Function Documentation
void NURBSFECollection::Allocate (int Order) [private]
Definition at line 1472 of file fe_coll.cpp.
References name, ParallelepipedFE, QuadrilateralFE, and SegmentFE.
Referenced by NURBSFECollection(), and UpdateOrder().
void NURBSFECollection::Deallocate () [private]
Definition at line 1481 of file fe_coll.cpp.
References ParallelepipedFE, QuadrilateralFE, and SegmentFE.
Referenced by UpdateOrder(), and ~NURBSFECollection().
int NURBSFECollection::DofForGeometry (int GeomType) const [virtual]
Implements FiniteElementCollection.
Definition at line 1502 of file fe_coll.cpp.
References mfem_error().
int * NURBSFECollection::DofOrderForOrientation (int GeomType, int Or) const [virtual]
Implements FiniteElementCollection.
Definition at line 1508 of file fe_coll.cpp.
References mfem_error().
const FiniteElement * NURBSFECollection::FiniteElementForGeometry (int GeomType) const [virtual]
Implements FiniteElementCollection.
Definition at line 1489 of file fe_coll.cpp.
References Geometry::CUBE, mfem_error(), ParallelepipedFE, QuadrilateralFE, Geometry::SEGMENT, SegmentFE, and Geometry::SQUARE.
int NURBSFECollection::GetOrder () const [inline]
Definition at line 145 of file fe_coll.hpp.
References FiniteElement::GetOrder(), and SegmentFE.
Referenced by Mesh::DegreeElevate(), and FiniteElementSpace::FiniteElementSpace().
virtual const char* NURBSFECollection::Name () const [inline, virtual]
Reimplemented from FiniteElementCollection.
Definition at line 164 of file fe_coll.hpp.
References name.
void NURBSFECollection::Reset () const [inline]
Definition at line 150 of file fe_coll.hpp.
References ParallelepipedFE, QuadrilateralFE, NURBSFiniteElement::Reset(), and SegmentFE.
void NURBSFECollection::UpdateOrder (int Order) [inline]
Change the order of the collection.
Definition at line 148 of file fe_coll.hpp.
References Allocate(), and Deallocate().
Referenced by Mesh::DegreeElevate().
Member Data Documentation
char NURBSFECollection::name[16] [private]
Definition at line 137 of file fe_coll.hpp.
Referenced by Allocate(), and Name().
NURBS3DFiniteElement* NURBSFECollection::ParallelepipedFE [private]
Definition at line 135 of file fe_coll.hpp.
Referenced by Allocate(), Deallocate(), FiniteElementForGeometry(), and Reset().
NURBS2DFiniteElement* NURBSFECollection::QuadrilateralFE [private]
Definition at line 134 of file fe_coll.hpp.
Referenced by Allocate(), Deallocate(), FiniteElementForGeometry(), and Reset().
NURBS1DFiniteElement* NURBSFECollection::SegmentFE [private]
Definition at line 133 of file fe_coll.hpp.
Referenced by Allocate(), Deallocate(), FiniteElementForGeometry(), GetOrder(), and Reset().
The documentation for this class was generated from the following files:
fe_coll.hpp
fe_coll.cpp