MFEM: DomainLFIntegrator Class Reference
DomainLFIntegrator Class Reference
Class for domain integration L(v) := (f, v)
#include <lininteg.hpp>
Public Member Functions
DomainLFIntegrator (Coefficient &QF, int a=2, int b=0)
Constructs a domain integrator with a given Coefficient.
DomainLFIntegrator (Coefficient &QF, const IntegrationRule *ir)
Constructs a domain integrator with a given Coefficient.
virtual void AssembleRHSElementVect (const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
Private Attributes
Vector shape
Coefficient & Q
const IntegrationRule * IntRule
int oa
int ob
Detailed Description
Class for domain integration L(v) := (f, v)
Definition at line 32 of file lininteg.hpp.
Constructor & Destructor Documentation
DomainLFIntegrator::DomainLFIntegrator (Coefficient & QF, int a = 2, int b = 0) [inline]
Constructs a domain integrator with a given Coefficient.
Definition at line 40 of file lininteg.hpp.
References IntRule.
DomainLFIntegrator::DomainLFIntegrator (Coefficient & QF, const IntegrationRule * ir) [inline]
Constructs a domain integrator with a given Coefficient.
Definition at line 46 of file lininteg.hpp.
References IntRule.
Member Function Documentation
void DomainLFIntegrator::AssembleRHSElementVect (const FiniteElement & el, ElementTransformation & Tr, Vector & elvect) [virtual]
Given a particular Finite Element and a transformation (Tr) computes the element right hand side element vector, elvect.
Implements LinearFormIntegrator.
Definition at line 23 of file lininteg.cpp.
References add(), FiniteElement::CalcShape(), Coefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRule, IntRules, oa, ob, Q, ElementTransformation::SetIntPoint(), Vector::SetSize(), shape, IntegrationPoint::weight, and ElementTransformation::Weight().
Member Data Documentation
const IntegrationRule* DomainLFIntegrator::IntRule [private]
Definition at line 36 of file lininteg.hpp.
Referenced by AssembleRHSElementVect(), and DomainLFIntegrator().
int DomainLFIntegrator::oa [private]
Definition at line 37 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
int DomainLFIntegrator::ob [private]
Definition at line 37 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Coefficient& DomainLFIntegrator::Q [private]
Definition at line 35 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Vector DomainLFIntegrator::shape [private]
Definition at line 34 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
The documentation for this class was generated from the following files:
lininteg.hpp
lininteg.cpp