MFEM: error.cpp File Reference
error.cpp File Reference
#include "error.hpp"
Functions
void mfem_error (const char *msg)
Function Documentation
void mfem_error (const char * msg)
Definition at line 14 of file error.cpp.
Referenced by add(), Vector::Add(), SparseMatrix::Add(), DenseMatrix::AddMatrix(), SparseMatrix::AddMult(), DenseMatrix::AddMult(), AddMult_a_VVt(), AddMultABt(), SparseMatrix::AddMultTranspose(), AddMultVWt(), Mesh::AddQuadFaceElement(), SparseMatrix::AddRow(), Mesh::AddSegmentFaceElement(), SparseMatrix::AddSubMatrix(), Mesh::AddTriangleFaceElement(), DenseMatrix::AdjustDofDirection(), BilinearFormIntegrator::AssembleElementMatrix(), VectorFEMassIntegrator::AssembleElementMatrix2(), BilinearFormIntegrator::AssembleElementMatrix2(), BilinearFormIntegrator::AssembleFaceMatrix(), LinearFormIntegrator::AssembleRHSElementVect(), Mesh::Bisection(), CalcAdjugate(), CalcAdjugateTranspose(), ND_TriangleElement::CalcCurlShape(), ND_QuadrilateralElement::CalcCurlShape(), FiniteElement::CalcCurlShape(), FiniteElement::CalcDivShape(), KnotVector::CalcDShape(), VectorFiniteElement::CalcDShape(), DenseMatrix::CalcEigenvalues(), FiniteElement::CalcHessian(), CalcInverse(), CalcInverseTranspose(), KnotVector::CalcShape(), VectorFiniteElement::CalcShape(), DenseMatrix::CalcSingularvalue(), FiniteElement::CalcVShape(), NURBSExtension::CheckBdrPatches(), Mesh::CheckDisplacements(), NURBSExtension::CheckPatches(), BilinearForm::ComputeElementMatrices(), Tetrahedron::CreateRefinementFlag(), FiniteElementSpace::D2C_GlobalRestrictionMatrix(), FiniteElementSpace::D2Const_GlobalRestrictionMatrix(), NURBSPatch::DegreeElevate(), KnotVector::DegreeElevate(), Mesh::DegreeElevate(), DenseMatrix::Det(), DetOfLinComb(), KnotVector::Difference(), NURBSFECollection::DofForGeometry(), RT1_3DFECollection::DofForGeometry(), RT0_3DFECollection::DofForGeometry(), ND1_3DFECollection::DofForGeometry(), RefinedLinearFECollection::DofForGeometry(), QuadraticDiscont3DFECollection::DofForGeometry(), LinearDiscont3DFECollection::DofForGeometry(), Const3DFECollection::DofForGeometry(), LinearNonConf3DFECollection::DofForGeometry(), CubicDiscont2DFECollection::DofForGeometry(), GaussQuadraticDiscont2DFECollection::DofForGeometry(), QuadraticPosDiscont2DFECollection::DofForGeometry(), QuadraticDiscont2DFECollection::DofForGeometry(), P1OnQuadFECollection::DofForGeometry(), GaussLinearDiscont2DFECollection::DofForGeometry(), LinearDiscont2DFECollection::DofForGeometry(), Const2DFECollection::DofForGeometry(), RT2_2DFECollection::DofForGeometry(), RT1_2DFECollection::DofForGeometry(), RT0_2DFECollection::DofForGeometry(), CrouzeixRaviartFECollection::DofForGeometry(), CubicFECollection::DofForGeometry(), QuadraticPosFECollection::DofForGeometry(), QuadraticFECollection::DofForGeometry(), LinearFECollection::DofForGeometry(), NURBSFECollection::DofOrderForOrientation(), ND_FECollection::DofOrderForOrientation(), dsyev_Eigensystem(), dsyevr_Eigensystem(), OctasectedElement::Duplicate(), QuadrisectedElement::Duplicate(), BisectedElement::Duplicate(), DenseMatrix::Eigensystem(), Mesh::ElementToEdgeTable(), Mesh::ElementToElementTable(), Mesh::ElementToFaceTable(), SparseMatrix::EliminateCol(), SparseMatrix::EliminateCols(), SparseMatrix::EliminateRow(), SparseMatrix::EliminateRowCol(), SparseMatrix::EliminateRowColMultipleRHS(), DenseMatrixSVD::Eval(), DenseMatrixEigensystem::Eval(), DeltaCoefficient::Eval(), DenseMatrixInverse::Factor(), Table::Finalize(), FindPartitioningComponents(), FindRoots(), NURBSFECollection::FiniteElementForGeometry(), RT1_3DFECollection::FiniteElementForGeometry(), RT0_3DFECollection::FiniteElementForGeometry(), ND1_3DFECollection::FiniteElementForGeometry(), RefinedLinearFECollection::FiniteElementForGeometry(), QuadraticDiscont3DFECollection::FiniteElementForGeometry(), LinearDiscont3DFECollection::FiniteElementForGeometry(), Const3DFECollection::FiniteElementForGeometry(), LinearNonConf3DFECollection::FiniteElementForGeometry(), CubicDiscont2DFECollection::FiniteElementForGeometry(), GaussQuadraticDiscont2DFECollection::FiniteElementForGeometry(), QuadraticPosDiscont2DFECollection::FiniteElementForGeometry(), QuadraticDiscont2DFECollection::FiniteElementForGeometry(), P1OnQuadFECollection::FiniteElementForGeometry(), GaussLinearDiscont2DFECollection::FiniteElementForGeometry(), LinearDiscont2DFECollection::FiniteElementForGeometry(), Const2DFECollection::FiniteElementForGeometry(), RT2_2DFECollection::FiniteElementForGeometry(), RT1_2DFECollection::FiniteElementForGeometry(), RT0_2DFECollection::FiniteElementForGeometry(), CrouzeixRaviartFECollection::FiniteElementForGeometry(), CubicFECollection::FiniteElementForGeometry(), QuadraticPosFECollection::FiniteElementForGeometry(), QuadraticFECollection::FiniteElementForGeometry(), LinearFECollection::FiniteElementForGeometry(), FiniteElementSpace::FiniteElementSpace(), SparseMatrix::Gauss_Seidel_back(), SparseMatrix::Gauss_Seidel_forw(), Mesh::GeneratePartitioning(), IntegrationRules::Get(), Mesh::GetBdrElementEdges(), Mesh::GetBdrElementFace(), SparseMatrix::GetBlocks(), MixedBilinearForm::GetBlocks(), Mesh::GetElementEdges(), Mesh::GetElementFaces(), Mesh::GetElementToEdgeTable(), Mesh::GetFaceBaseGeometry(), FiniteElement::GetFaceDofs(), Mesh::GetFaceEdgeTable(), Mesh::GetFaceElementTransformations(), Mesh::GetFineElemTrans(), GridFunction::GetGradient(), SparseMatrix::GetJacobiScaling(), RT0TetFiniteElement::GetLocalInterpolation(), RT1HexFiniteElement::GetLocalInterpolation(), RT0HexFiniteElement::GetLocalInterpolation(), Nedelec1TetFiniteElement::GetLocalInterpolation(), Nedelec1HexFiniteElement::GetLocalInterpolation(), RT2QuadFiniteElement::GetLocalInterpolation(), RT1QuadFiniteElement::GetLocalInterpolation(), RT1TriangleFiniteElement::GetLocalInterpolation(), RT0QuadFiniteElement::GetLocalInterpolation(), RT0TriangleFiniteElement::GetLocalInterpolation(), FiniteElement::GetLocalInterpolation(), Geometry::GetPerfPointMat(), Mesh::GetQuadOrientation(), Mesh::GetRefinementType(), SparseMatrix::GetSubMatrix(), Mesh::GetTransformationFEforElementType(), Mesh::GetTriOrientation(), Geometry::GetVertices(), DenseMatrix::GradToCurl(), DenseMatrix::GradToDiv(), GridFunction::GridFunction(), FiniteElementCollection::HasFaceDofs(), DSTable::Index(), NURBSPatch::init(), DenseMatrixSVD::Init(), Interpolate(), DenseMatrix::Invert(), SparseMatrix::IsSymmetric(), SparseMatrix::Jacobi(), SparseMatrix::Jacobi2(), NURBSPatch::KnotInsert(), Mesh::KnotInsert(), L2_FECollection::L2_FECollection(), LagrangeHexFiniteElement::LagrangeHexFiniteElement(), Array< T >::Last(), Mesh::Load(), Local_FECollection::Local_FECollection(), Mesh::LocalRefinement(), ListOfIntegerSets::Lookup(), Array< T >::Max(), DenseMatrixInverse::Mult(), Mult(), DenseMatrix::Mult(), MultABt(), MultAtB(), Operator::MultTranspose(), DenseMatrix::MultTranspose(), MultVWt(), ND_FECollection::ND_FECollection(), FiniteElementCollection::New(), NURBSExtension::NURBSExtension(), Vector::operator()(), STable3D::operator()(), SparseMatrix::operator()(), NURBSPatchMap::operator()(), NURBSPatch::operator()(), DenseMatrix::operator()(), Array3D< T >::operator()(), Array2D< T >::operator()(), Vector::operator*(), DenseMatrix::operator*(), Vector::operator+=(), SparseMatrix::operator+=(), Vector::operator-=(), Array2D< T >::operator[](), Array< T >::operator[](), NURBSPatchMap::Or2D(), IsoparametricTransformation::OrderGrad(), IsoparametricTransformation::OrderJ(), IsoparametricTransformation::OrderW(), Tetrahedron::ParseRefinementFlag(), SparseMatrix::PartMult(), SparseMatrix::Print(), SparseMatrix::PrintCSR(), SparseMatrix::PrintCSR2(), Mesh::PrintVTK(), Mesh::PrintXG(), FiniteElement::Project(), VectorFiniteElement::Project_ND(), VectorFiniteElement::Project_RT(), FiniteElement::ProjectCurl(), FiniteElement::ProjectDelta(), FiniteElement::ProjectDiv(), FiniteElement::ProjectGrad(), VectorFiniteElement::ProjectGrad_RT(), Table::Push(), STable3D::Push(), STable3D::Push4(), DSTable::Push_(), GridFunctionCoefficient::Read(), GeometryRefiner::Refine(), GeometryRefiner::RefineInterior(), Revolve3D(), NURBSPatch::Rotate3D(), RT_FECollection::RT_FECollection(), SparseMatrix::SearchRow(), Vector::Set(), SparseMatrix::Set(), IntegrationRules::Set(), NURBSExtension::SetKnotsFromPatches(), NURBSPatch::SetLoopDirection(), Array< T >::SetSize(), Mesh::SetState(), SparseMatrix::SetSubMatrix(), SparseMatrix::SetSubMatrixTranspose(), Vector::SetVector(), DenseMatrix::SingularValues(), subtract(), NURBSPatch::SwapDirections(), SparseMatrix::Symmetrize(), DenseMatrix::Symmetrize(), IntegrationRules::TetrahedronIntegrationRules(), DenseMatrix::Trace(), IntegrationRules::TriangleIntegrationRules(), Mesh::UniformRefinement(), and DenseMatrix::Weight().