MFEM: ex2.cpp File Reference
ex2.cpp File Reference
#include <fstream>
#include "mfem.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 40 of file ex2.cpp.
References LinearForm::AddBoundaryIntegrator(), BilinearForm::AddDomainIntegrator(), BilinearForm::Assemble(), LinearForm::Assemble(), Mesh::attributes, Mesh::bdr_attributes, Mesh::DegreeElevate(), Mesh::Dimension(), BilinearForm::EliminateEssentialBC(), BilinearForm::Finalize(), Mesh::GetNE(), Mesh::GetNodes(), NURBSExtension::GetOrder(), FiniteElementSpace::GetVSize(), Array< T >::Max(), Mesh::NURBSext, PCG(), Mesh::Print(), GridFunction::Save(), osockstream::send(), VectorArrayCoefficient::Set(), Mesh::SetNodalFESpace(), BilinearForm::SpMat(), and Mesh::UniformRefinement().