var searchData=
[
  ['l2_5ffecollection_0',['L2_FECollection',['../classmfem_1_1L2__FECollection.html',1,'mfem']]],
  ['l2_5ffiniteelement_1',['L2_FiniteElement',['../classmfem_1_1L2__FiniteElement.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3acube_2c_20p_20_3e_2',['L2_FiniteElement&lt; Geometry::CUBE, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1CUBE_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3asegment_2c_20p_20_3e_3',['L2_FiniteElement&lt; Geometry::SEGMENT, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1SEGMENT_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3asquare_2c_20p_20_3e_4',['L2_FiniteElement&lt; Geometry::SQUARE, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1SQUARE_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3atetrahedron_2c_20p_20_3e_5',['L2_FiniteElement&lt; Geometry::TETRAHEDRON, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1TETRAHEDRON_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3atriangle_2c_20p_20_3e_6',['L2_FiniteElement&lt; Geometry::TRIANGLE, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1TRIANGLE_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_7',['L2_FiniteElement_base',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3acube_2c_20p_2c_20l2_5fhexahedronelement_2c_20l2pos_5fhexahedronelement_2c_28p_2b1_29_20_2a_28p_2b1_29_20_2a_28p_2b1_29_2c_20true_20_3e_8',['L2_FiniteElement_base&lt; Geometry::CUBE, P, L2_HexahedronElement, L2Pos_HexahedronElement,(P+1) *(P+1) *(P+1), true &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3asegment_2c_20p_2c_20l2_5fsegmentelement_2c_20l2pos_5fsegmentelement_2c_20p_2b1_2c_20true_20_3e_9',['L2_FiniteElement_base&lt; Geometry::SEGMENT, P, L2_SegmentElement, L2Pos_SegmentElement, P+1, true &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3asquare_2c_20p_2c_20l2_5fquadrilateralelement_2c_20l2pos_5fquadrilateralelement_2c_28p_2b1_29_20_2a_28p_2b1_29_2c_20true_20_3e_10',['L2_FiniteElement_base&lt; Geometry::SQUARE, P, L2_QuadrilateralElement, L2Pos_QuadrilateralElement,(P+1) *(P+1), true &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3atetrahedron_2c_20p_2c_20l2_5ftetrahedronelement_2c_20l2pos_5ftetrahedronelement_2c_28_28p_2b1_29_20_2a_28p_2b2_29_20_2a_28p_2b3_29_29_2f6_2c_20false_20_3e_11',['L2_FiniteElement_base&lt; Geometry::TETRAHEDRON, P, L2_TetrahedronElement, L2Pos_TetrahedronElement,((P+1) *(P+2) *(P+3))/6, false &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3atriangle_2c_20p_2c_20l2_5ftriangleelement_2c_20l2pos_5ftriangleelement_2c_28_28p_2b1_29_20_2a_28p_2b2_29_29_2f2_2c_20false_20_3e_12',['L2_FiniteElement_base&lt; Geometry::TRIANGLE, P, L2_TriangleElement, L2Pos_TriangleElement,((P+1) *(P+2))/2, false &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelementspace_13',['L2_FiniteElementSpace',['../classmfem_1_1L2__FiniteElementSpace.html',1,'mfem']]],
  ['l2_5fhexahedronelement_14',['L2_HexahedronElement',['../classmfem_1_1L2__HexahedronElement.html',1,'mfem']]],
  ['l2_5fparfespace_15',['L2_ParFESpace',['../classmfem_1_1common_1_1L2__ParFESpace.html',1,'mfem::common']]],
  ['l2_5fquadrilateralelement_16',['L2_QuadrilateralElement',['../classmfem_1_1L2__QuadrilateralElement.html',1,'mfem']]],
  ['l2_5fsegmentelement_17',['L2_SegmentElement',['../classmfem_1_1L2__SegmentElement.html',1,'mfem']]],
  ['l2_5ftetrahedronelement_18',['L2_TetrahedronElement',['../classmfem_1_1L2__TetrahedronElement.html',1,'mfem']]],
  ['l2_5ftriangleelement_19',['L2_TriangleElement',['../classmfem_1_1L2__TriangleElement.html',1,'mfem']]],
  ['l2_5fwedgeelement_20',['L2_WedgeElement',['../classmfem_1_1L2__WedgeElement.html',1,'mfem']]],
  ['l2elementrestriction_21',['L2ElementRestriction',['../classmfem_1_1L2ElementRestriction.html',1,'mfem']]],
  ['l2facerestriction_22',['L2FaceRestriction',['../classmfem_1_1L2FaceRestriction.html',1,'mfem']]],
  ['l2mortarintegrator_23',['L2MortarIntegrator',['../classmfem_1_1L2MortarIntegrator.html',1,'mfem']]],
  ['l2normalderivativefacerestriction_24',['L2NormalDerivativeFaceRestriction',['../classmfem_1_1L2NormalDerivativeFaceRestriction.html',1,'mfem']]],
  ['l2pos_5fhexahedronelement_25',['L2Pos_HexahedronElement',['../classmfem_1_1L2Pos__HexahedronElement.html',1,'mfem']]],
  ['l2pos_5fquadrilateralelement_26',['L2Pos_QuadrilateralElement',['../classmfem_1_1L2Pos__QuadrilateralElement.html',1,'mfem']]],
  ['l2pos_5fsegmentelement_27',['L2Pos_SegmentElement',['../classmfem_1_1L2Pos__SegmentElement.html',1,'mfem']]],
  ['l2pos_5ftetrahedronelement_28',['L2Pos_TetrahedronElement',['../classmfem_1_1L2Pos__TetrahedronElement.html',1,'mfem']]],
  ['l2pos_5ftriangleelement_29',['L2Pos_TriangleElement',['../classmfem_1_1L2Pos__TriangleElement.html',1,'mfem']]],
  ['l2pos_5fwedgeelement_30',['L2Pos_WedgeElement',['../classmfem_1_1L2Pos__WedgeElement.html',1,'mfem']]],
  ['l2projection_31',['L2Projection',['../classmfem_1_1L2ProjectionGridTransfer_1_1L2Projection.html',1,'mfem::L2ProjectionGridTransfer']]],
  ['l2projectiongridtransfer_32',['L2ProjectionGridTransfer',['../classmfem_1_1L2ProjectionGridTransfer.html',1,'mfem']]],
  ['l2projectionh1space_33',['L2ProjectionH1Space',['../classmfem_1_1L2ProjectionGridTransfer_1_1L2ProjectionH1Space.html',1,'mfem::L2ProjectionGridTransfer']]],
  ['l2projectionl2space_34',['L2ProjectionL2Space',['../classmfem_1_1L2ProjectionGridTransfer_1_1L2ProjectionL2Space.html',1,'mfem::L2ProjectionGridTransfer']]],
  ['l2prolongation_35',['L2Prolongation',['../classmfem_1_1L2ProjectionGridTransfer_1_1L2Prolongation.html',1,'mfem::L2ProjectionGridTransfer']]],
  ['l2zienkiewiczzhuestimator_36',['L2ZienkiewiczZhuEstimator',['../classmfem_1_1L2ZienkiewiczZhuEstimator.html',1,'mfem']]],
  ['lagrange1dfiniteelement_37',['Lagrange1DFiniteElement',['../classmfem_1_1Lagrange1DFiniteElement.html',1,'mfem']]],
  ['lagrangehexfiniteelement_38',['LagrangeHexFiniteElement',['../classmfem_1_1LagrangeHexFiniteElement.html',1,'mfem']]],
  ['lbfgssolver_39',['LBFGSSolver',['../classmfem_1_1LBFGSSolver.html',1,'mfem']]],
  ['levelsetnormalgradcoeff_40',['LevelSetNormalGradCoeff',['../classmfem_1_1LevelSetNormalGradCoeff.html',1,'mfem']]],
  ['levelsettransformer_41',['LevelSetTransformer',['../classmfem_1_1spde_1_1LevelSetTransformer.html',1,'mfem::spde']]],
  ['linear1dfiniteelement_42',['Linear1DFiniteElement',['../classmfem_1_1Linear1DFiniteElement.html',1,'mfem']]],
  ['linear2dfiniteelement_43',['Linear2DFiniteElement',['../classmfem_1_1Linear2DFiniteElement.html',1,'mfem']]],
  ['linear3dfiniteelement_44',['Linear3DFiniteElement',['../classmfem_1_1Linear3DFiniteElement.html',1,'mfem']]],
  ['linearaccelerationsolver_45',['LinearAccelerationSolver',['../classmfem_1_1LinearAccelerationSolver.html',1,'mfem']]],
  ['lineardiscont2dfecollection_46',['LinearDiscont2DFECollection',['../classmfem_1_1LinearDiscont2DFECollection.html',1,'mfem']]],
  ['lineardiscont3dfecollection_47',['LinearDiscont3DFECollection',['../classmfem_1_1LinearDiscont3DFECollection.html',1,'mfem']]],
  ['linearelasticitysolver_48',['LinearElasticitySolver',['../classmfem_1_1LinearElasticitySolver.html',1,'mfem']]],
  ['linearelasticmaterial_49',['LinearElasticMaterial',['../structLinearElasticMaterial.html',1,'']]],
  ['linearfecollection_50',['LinearFECollection',['../classmfem_1_1LinearFECollection.html',1,'mfem']]],
  ['linearform_51',['LinearForm',['../classmfem_1_1LinearForm.html',1,'mfem']]],
  ['linearformextension_52',['LinearFormExtension',['../classmfem_1_1LinearFormExtension.html',1,'mfem']]],
  ['linearformintegrator_53',['LinearFormIntegrator',['../classmfem_1_1LinearFormIntegrator.html',1,'mfem']]],
  ['linearnonconf3dfecollection_54',['LinearNonConf3DFECollection',['../classmfem_1_1LinearNonConf3DFECollection.html',1,'mfem']]],
  ['linearpyramidfiniteelement_55',['LinearPyramidFiniteElement',['../classmfem_1_1LinearPyramidFiniteElement.html',1,'mfem']]],
  ['linearspacingfunction_56',['LinearSpacingFunction',['../classmfem_1_1LinearSpacingFunction.html',1,'mfem']]],
  ['linearwedgefiniteelement_57',['LinearWedgeFiniteElement',['../classmfem_1_1LinearWedgeFiniteElement.html',1,'mfem']]],
  ['listofintegersets_58',['ListOfIntegerSets',['../classmfem_1_1ListOfIntegerSets.html',1,'mfem']]],
  ['local_5ffecollection_59',['Local_FECollection',['../classmfem_1_1Local__FECollection.html',1,'mfem']]],
  ['localsolver_60',['LocalSolver',['../classmfem_1_1blocksolvers_1_1LocalSolver.html',1,'mfem::blocksolvers']]],
  ['logarithmicspacingfunction_61',['LogarithmicSpacingFunction',['../classmfem_1_1LogarithmicSpacingFunction.html',1,'mfem']]],
  ['lorbase_62',['LORBase',['../classmfem_1_1LORBase.html',1,'mfem']]],
  ['lordiscretization_63',['LORDiscretization',['../classmfem_1_1LORDiscretization.html',1,'mfem']]],
  ['lorsolver_64',['LORSolver',['../classmfem_1_1LORSolver.html',1,'mfem']]],
  ['lorsolver_3c_20hypreads_20_3e_65',['LORSolver&lt; HypreADS &gt;',['../classmfem_1_1LORSolver_3_01HypreADS_01_4.html',1,'mfem']]],
  ['lorsolver_3c_20hypreams_20_3e_66',['LORSolver&lt; HypreAMS &gt;',['../classmfem_1_1LORSolver_3_01HypreAMS_01_4.html',1,'mfem']]],
  ['lperrorestimator_67',['LpErrorEstimator',['../classmfem_1_1LpErrorEstimator.html',1,'mfem']]],
  ['lszienkiewiczzhuestimator_68',['LSZienkiewiczZhuEstimator',['../classmfem_1_1LSZienkiewiczZhuEstimator.html',1,'mfem']]],
  ['lufactors_69',['LUFactors',['../classmfem_1_1LUFactors.html',1,'mfem']]],
  ['lumpedintegrator_70',['LumpedIntegrator',['../classmfem_1_1LumpedIntegrator.html',1,'mfem']]]
];
