var searchData=
[
  ['rajacuwrap_0',['RajaCuWrap',['../structmfem_1_1RajaCuWrap.html',1,'mfem']]],
  ['rajacuwrap_3c_201_20_3e_1',['RajaCuWrap&lt; 1 &gt;',['../structmfem_1_1RajaCuWrap_3_011_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_202_20_3e_2',['RajaCuWrap&lt; 2 &gt;',['../structmfem_1_1RajaCuWrap_3_012_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_203_20_3e_3',['RajaCuWrap&lt; 3 &gt;',['../structmfem_1_1RajaCuWrap_3_013_01_4.html',1,'mfem']]],
  ['rajahipwrap_4',['RajaHipWrap',['../structmfem_1_1RajaHipWrap.html',1,'mfem']]],
  ['rajahipwrap_3c_201_20_3e_5',['RajaHipWrap&lt; 1 &gt;',['../structmfem_1_1RajaHipWrap_3_011_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_202_20_3e_6',['RajaHipWrap&lt; 2 &gt;',['../structmfem_1_1RajaHipWrap_3_012_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_203_20_3e_7',['RajaHipWrap&lt; 3 &gt;',['../structmfem_1_1RajaHipWrap_3_013_01_4.html',1,'mfem']]],
  ['rapoperator_8',['RAPOperator',['../classmfem_1_1RAPOperator.html',1,'mfem']]],
  ['ratiocoefficient_9',['RatioCoefficient',['../classmfem_1_1RatioCoefficient.html',1,'mfem']]],
  ['rebalancedofmessage_10',['RebalanceDofMessage',['../classmfem_1_1ParNCMesh_1_1RebalanceDofMessage.html',1,'mfem::ParNCMesh']]],
  ['rebalancemessage_11',['RebalanceMessage',['../classmfem_1_1ParNCMesh_1_1RebalanceMessage.html',1,'mfem::ParNCMesh']]],
  ['rebalancer_12',['Rebalancer',['../classmfem_1_1Rebalancer.html',1,'mfem']]],
  ['rectangularconstrainedoperator_13',['RectangularConstrainedOperator',['../classmfem_1_1RectangularConstrainedOperator.html',1,'mfem']]],
  ['refinedbilinear2dfiniteelement_14',['RefinedBiLinear2DFiniteElement',['../classmfem_1_1RefinedBiLinear2DFiniteElement.html',1,'mfem']]],
  ['refinedgeometry_15',['RefinedGeometry',['../classmfem_1_1RefinedGeometry.html',1,'mfem']]],
  ['refinedlinear1dfiniteelement_16',['RefinedLinear1DFiniteElement',['../classmfem_1_1RefinedLinear1DFiniteElement.html',1,'mfem']]],
  ['refinedlinear2dfiniteelement_17',['RefinedLinear2DFiniteElement',['../classmfem_1_1RefinedLinear2DFiniteElement.html',1,'mfem']]],
  ['refinedlinear3dfiniteelement_18',['RefinedLinear3DFiniteElement',['../classmfem_1_1RefinedLinear3DFiniteElement.html',1,'mfem']]],
  ['refinedlinearfecollection_19',['RefinedLinearFECollection',['../classmfem_1_1RefinedLinearFECollection.html',1,'mfem']]],
  ['refinedtrilinear3dfiniteelement_20',['RefinedTriLinear3DFiniteElement',['../classmfem_1_1RefinedTriLinear3DFiniteElement.html',1,'mfem']]],
  ['refinement_21',['Refinement',['../structmfem_1_1Refinement.html',1,'mfem']]],
  ['refinementoperator_22',['RefinementOperator',['../classmfem_1_1FiniteElementSpace_1_1RefinementOperator.html',1,'mfem::FiniteElementSpace']]],
  ['residualbcmonitor_23',['ResidualBCMonitor',['../classmfem_1_1ResidualBCMonitor.html',1,'mfem']]],
  ['residuallogger_24',['ResidualLogger',['../structmfem_1_1Ginkgo_1_1ResidualLogger.html',1,'mfem::Ginkgo']]],
  ['restrhash_25',['RestrHash',['../structmfem_1_1ceed_1_1RestrHash.html',1,'mfem::ceed']]],
  ['restrictedcoefficient_26',['RestrictedCoefficient',['../classmfem_1_1RestrictedCoefficient.html',1,'mfem']]],
  ['result_27',['Result',['../structmfem_1_1TElementTransformation_1_1Result.html',1,'mfem::TElementTransformation']]],
  ['result_3c_200_2c_20it_5ft_20_3e_28',['Result&lt; 0, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_010_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_201_2c_20it_5ft_20_3e_29',['Result&lt; 1, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_011_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_2010_2c_20it_5ft_20_3e_30',['Result&lt; 10, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_0110_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_202_2c_20it_5ft_20_3e_31',['Result&lt; 2, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_012_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_203_2c_20it_5ft_20_3e_32',['Result&lt; 3, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_013_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_206_2c_20it_5ft_20_3e_33',['Result&lt; 6, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_016_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_5ft_34',['result_t',['../structmfem_1_1IntRuleCoefficient_1_1Aux_3_01true_00_01dummy_01_4_1_1result__t.html',1,'mfem::IntRuleCoefficient::Aux&lt; true, dummy &gt;']]],
  ['riemannsolver_35',['RiemannSolver',['../classmfem_1_1RiemannSolver.html',1,'mfem']]],
  ['rk2solver_36',['RK2Solver',['../classmfem_1_1RK2Solver.html',1,'mfem']]],
  ['rk3sspsolver_37',['RK3SSPSolver',['../classmfem_1_1RK3SSPSolver.html',1,'mfem']]],
  ['rk4solver_38',['RK4Solver',['../classmfem_1_1RK4Solver.html',1,'mfem']]],
  ['rk6solver_39',['RK6Solver',['../classmfem_1_1RK6Solver.html',1,'mfem']]],
  ['rk8solver_40',['RK8Solver',['../classmfem_1_1RK8Solver.html',1,'mfem']]],
  ['rottrilinearhexfiniteelement_41',['RotTriLinearHexFiniteElement',['../classmfem_1_1RotTriLinearHexFiniteElement.html',1,'mfem']]],
  ['rowiterator_42',['RowIterator',['../classmfem_1_1DSTable_1_1RowIterator.html',1,'mfem::DSTable']]],
  ['rownode_43',['RowNode',['../classmfem_1_1RowNode.html',1,'mfem']]],
  ['rt0_5f2dfecollection_44',['RT0_2DFECollection',['../classmfem_1_1RT0__2DFECollection.html',1,'mfem']]],
  ['rt0_5f3dfecollection_45',['RT0_3DFECollection',['../classmfem_1_1RT0__3DFECollection.html',1,'mfem']]],
  ['rt0hexfiniteelement_46',['RT0HexFiniteElement',['../classmfem_1_1RT0HexFiniteElement.html',1,'mfem']]],
  ['rt0pyrfiniteelement_47',['RT0PyrFiniteElement',['../classmfem_1_1RT0PyrFiniteElement.html',1,'mfem']]],
  ['rt0quadfiniteelement_48',['RT0QuadFiniteElement',['../classmfem_1_1RT0QuadFiniteElement.html',1,'mfem']]],
  ['rt0tetfiniteelement_49',['RT0TetFiniteElement',['../classmfem_1_1RT0TetFiniteElement.html',1,'mfem']]],
  ['rt0trianglefiniteelement_50',['RT0TriangleFiniteElement',['../classmfem_1_1RT0TriangleFiniteElement.html',1,'mfem']]],
  ['rt0wdgfiniteelement_51',['RT0WdgFiniteElement',['../classmfem_1_1RT0WdgFiniteElement.html',1,'mfem']]],
  ['rt1_5f2dfecollection_52',['RT1_2DFECollection',['../classmfem_1_1RT1__2DFECollection.html',1,'mfem']]],
  ['rt1_5f3dfecollection_53',['RT1_3DFECollection',['../classmfem_1_1RT1__3DFECollection.html',1,'mfem']]],
  ['rt1hexfiniteelement_54',['RT1HexFiniteElement',['../classmfem_1_1RT1HexFiniteElement.html',1,'mfem']]],
  ['rt1quadfiniteelement_55',['RT1QuadFiniteElement',['../classmfem_1_1RT1QuadFiniteElement.html',1,'mfem']]],
  ['rt1trianglefiniteelement_56',['RT1TriangleFiniteElement',['../classmfem_1_1RT1TriangleFiniteElement.html',1,'mfem']]],
  ['rt2_5f2dfecollection_57',['RT2_2DFECollection',['../classmfem_1_1RT2__2DFECollection.html',1,'mfem']]],
  ['rt2quadfiniteelement_58',['RT2QuadFiniteElement',['../classmfem_1_1RT2QuadFiniteElement.html',1,'mfem']]],
  ['rt2trianglefiniteelement_59',['RT2TriangleFiniteElement',['../classmfem_1_1RT2TriangleFiniteElement.html',1,'mfem']]],
  ['rt_5ffecollection_60',['RT_FECollection',['../classmfem_1_1RT__FECollection.html',1,'mfem']]],
  ['rt_5ffespace_61',['RT_FESpace',['../classmfem_1_1common_1_1RT__FESpace.html',1,'mfem::common']]],
  ['rt_5fhexahedronelement_62',['RT_HexahedronElement',['../classmfem_1_1RT__HexahedronElement.html',1,'mfem']]],
  ['rt_5fparfespace_63',['RT_ParFESpace',['../classmfem_1_1common_1_1RT__ParFESpace.html',1,'mfem::common']]],
  ['rt_5fquadrilateralelement_64',['RT_QuadrilateralElement',['../classmfem_1_1RT__QuadrilateralElement.html',1,'mfem']]],
  ['rt_5fr1d_5ffecollection_65',['RT_R1D_FECollection',['../classmfem_1_1RT__R1D__FECollection.html',1,'mfem']]],
  ['rt_5fr1d_5fsegmentelement_66',['RT_R1D_SegmentElement',['../classmfem_1_1RT__R1D__SegmentElement.html',1,'mfem']]],
  ['rt_5fr2d_5ffecollection_67',['RT_R2D_FECollection',['../classmfem_1_1RT__R2D__FECollection.html',1,'mfem']]],
  ['rt_5fr2d_5ffiniteelement_68',['RT_R2D_FiniteElement',['../classmfem_1_1RT__R2D__FiniteElement.html',1,'mfem']]],
  ['rt_5fr2d_5fquadrilateralelement_69',['RT_R2D_QuadrilateralElement',['../classmfem_1_1RT__R2D__QuadrilateralElement.html',1,'mfem']]],
  ['rt_5fr2d_5fsegmentelement_70',['RT_R2D_SegmentElement',['../classmfem_1_1RT__R2D__SegmentElement.html',1,'mfem']]],
  ['rt_5fr2d_5ftrace_5ffecollection_71',['RT_R2D_Trace_FECollection',['../classmfem_1_1RT__R2D__Trace__FECollection.html',1,'mfem']]],
  ['rt_5fr2d_5ftriangleelement_72',['RT_R2D_TriangleElement',['../classmfem_1_1RT__R2D__TriangleElement.html',1,'mfem']]],
  ['rt_5ftetrahedronelement_73',['RT_TetrahedronElement',['../classmfem_1_1RT__TetrahedronElement.html',1,'mfem']]],
  ['rt_5ftrace_5ffecollection_74',['RT_Trace_FECollection',['../classmfem_1_1RT__Trace__FECollection.html',1,'mfem']]],
  ['rt_5ftriangleelement_75',['RT_TriangleElement',['../classmfem_1_1RT__TriangleElement.html',1,'mfem']]],
  ['rt_5fwedgeelement_76',['RT_WedgeElement',['../classmfem_1_1RT__WedgeElement.html',1,'mfem']]],
  ['rusanovflux_77',['RusanovFlux',['../classmfem_1_1RusanovFlux.html',1,'mfem']]]
];
