var searchData=
[
  ['gaussbilinear2dfiniteelement_0',['GaussBiLinear2DFiniteElement',['../classmfem_1_1GaussBiLinear2DFiniteElement.html',1,'mfem']]],
  ['gaussbiquad2dfiniteelement_1',['GaussBiQuad2DFiniteElement',['../classmfem_1_1GaussBiQuad2DFiniteElement.html',1,'mfem']]],
  ['gaussianspacingfunction_2',['GaussianSpacingFunction',['../classmfem_1_1GaussianSpacingFunction.html',1,'mfem']]],
  ['gaussintegrationrule_3',['GaussIntegrationRule',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gaussintegrationrule_3c_201_2c_20order_2f2_2b1_2c_20real_5ft_20_3e_4',['GaussIntegrationRule&lt; 1, Order/2+1, real_t &gt;',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gaussintegrationrule_3c_202_2c_20order_2f2_2b1_2c_20real_5ft_20_3e_5',['GaussIntegrationRule&lt; 2, Order/2+1, real_t &gt;',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gaussintegrationrule_3c_203_2c_20order_2f2_2b1_2c_20real_5ft_20_3e_6',['GaussIntegrationRule&lt; 3, Order/2+1, real_t &gt;',['../classmfem_1_1GaussIntegrationRule.html',1,'mfem']]],
  ['gausslinear2dfiniteelement_7',['GaussLinear2DFiniteElement',['../classmfem_1_1GaussLinear2DFiniteElement.html',1,'mfem']]],
  ['gausslineardiscont2dfecollection_8',['GaussLinearDiscont2DFECollection',['../classmfem_1_1GaussLinearDiscont2DFECollection.html',1,'mfem']]],
  ['gaussquad2dfiniteelement_9',['GaussQuad2DFiniteElement',['../classmfem_1_1GaussQuad2DFiniteElement.html',1,'mfem']]],
  ['gaussquadraticdiscont2dfecollection_10',['GaussQuadraticDiscont2DFECollection',['../classmfem_1_1GaussQuadraticDiscont2DFECollection.html',1,'mfem']]],
  ['generalams_11',['GeneralAMS',['../classmfem_1_1GeneralAMS.html',1,'mfem']]],
  ['generalizedalpha2solver_12',['GeneralizedAlpha2Solver',['../classmfem_1_1GeneralizedAlpha2Solver.html',1,'mfem']]],
  ['generalizedalphasolver_13',['GeneralizedAlphaSolver',['../classmfem_1_1GeneralizedAlphaSolver.html',1,'mfem']]],
  ['genericintegrationrule_14',['GenericIntegrationRule',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_201_2c_200_2c_20real_5ft_20_3e_15',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 1, 0, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_201_2c_201_2c_20real_5ft_20_3e_16',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 1, 1, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2011_2c_204_2c_20real_5ft_20_3e_17',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 11, 4, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2014_2c_205_2c_20real_5ft_20_3e_18',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 14, 5, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2024_2c_206_2c_20real_5ft_20_3e_19',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 24, 6, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_2031_2c_207_2c_20real_5ft_20_3e_20',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 31, 7, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_204_2c_202_2c_20real_5ft_20_3e_21',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 4, 2, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atetrahedron_2c_205_2c_203_2c_20real_5ft_20_3e_22',['GenericIntegrationRule&lt; Geometry::TETRAHEDRON, 5, 3, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_201_2c_200_2c_20real_5ft_20_3e_23',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 1, 0, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_201_2c_201_2c_20real_5ft_20_3e_24',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 1, 1, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_2012_2c_206_2c_20real_5ft_20_3e_25',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 12, 6, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_2012_2c_207_2c_20real_5ft_20_3e_26',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 12, 7, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_203_2c_202_2c_20real_5ft_20_3e_27',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 3, 2, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_204_2c_203_2c_20real_5ft_20_3e_28',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 4, 3, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_206_2c_204_2c_20real_5ft_20_3e_29',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 6, 4, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['genericintegrationrule_3c_20geometry_3a_3atriangle_2c_207_2c_205_2c_20real_5ft_20_3e_30',['GenericIntegrationRule&lt; Geometry::TRIANGLE, 7, 5, real_t &gt;',['../classmfem_1_1GenericIntegrationRule.html',1,'mfem']]],
  ['geometricfactors_31',['GeometricFactors',['../classmfem_1_1GeometricFactors.html',1,'mfem']]],
  ['geometricmultigrid_32',['GeometricMultigrid',['../classmfem_1_1GeometricMultigrid.html',1,'mfem']]],
  ['geometricspacingfunction_33',['GeometricSpacingFunction',['../classmfem_1_1GeometricSpacingFunction.html',1,'mfem']]],
  ['geometry_34',['Geometry',['../classmfem_1_1Geometry.html',1,'mfem']]],
  ['geometrylist_35',['GeometryList',['../classmfem_1_1Mesh_1_1GeometryList.html',1,'mfem::Mesh']]],
  ['geometryrefiner_36',['GeometryRefiner',['../classmfem_1_1GeometryRefiner.html',1,'mfem']]],
  ['geominfo_37',['GeomInfo',['../structmfem_1_1NCMesh_1_1GeomInfo.html',1,'mfem::NCMesh']]],
  ['get_38',['Get',['../structmfem_1_1TElementTransformation_1_1Get.html',1,'mfem::TElementTransformation']]],
  ['gftransformer_39',['GFTransformer',['../classmfem_1_1spde_1_1GFTransformer.html',1,'mfem::spde']]],
  ['ginkgoexecutor_40',['GinkgoExecutor',['../classmfem_1_1Ginkgo_1_1GinkgoExecutor.html',1,'mfem::Ginkgo']]],
  ['ginkgoiterativesolver_41',['GinkgoIterativeSolver',['../classmfem_1_1Ginkgo_1_1GinkgoIterativeSolver.html',1,'mfem::Ginkgo']]],
  ['ginkgopreconditioner_42',['GinkgoPreconditioner',['../classmfem_1_1Ginkgo_1_1GinkgoPreconditioner.html',1,'mfem::Ginkgo']]],
  ['gko_5fmfem_5fdestroy_43',['gko_mfem_destroy',['../classmfem_1_1Ginkgo_1_1gko__mfem__destroy.html',1,'mfem::Ginkgo']]],
  ['gmressolver_44',['GMRESSolver',['../classmfem_1_1Ginkgo_1_1GMRESSolver.html',1,'mfem::Ginkgo::GMRESSolver'],['../classmfem_1_1GMRESSolver.html',1,'mfem::GMRESSolver']]],
  ['gnutls_5fglobal_5fstate_45',['GnuTLS_global_state',['../classmfem_1_1GnuTLS__global__state.html',1,'mfem']]],
  ['gnutls_5fsession_5fparams_46',['GnuTLS_session_params',['../classmfem_1_1GnuTLS__session__params.html',1,'mfem']]],
  ['gnutls_5fsocketbuf_47',['GnuTLS_socketbuf',['../classmfem_1_1GnuTLS__socketbuf.html',1,'mfem']]],
  ['gnutls_5fstatus_48',['GnuTLS_status',['../classmfem_1_1GnuTLS__status.html',1,'mfem']]],
  ['gradcomponentcoeff_49',['GradComponentCoeff',['../classmfem_1_1GradComponentCoeff.html',1,'mfem']]],
  ['gradientgridfunctioncoefficient_50',['GradientGridFunctionCoefficient',['../classmfem_1_1GradientGridFunctionCoefficient.html',1,'mfem']]],
  ['gradientintegrator_51',['GradientIntegrator',['../classmfem_1_1GradientIntegrator.html',1,'mfem']]],
  ['gradientinterpolator_52',['GradientInterpolator',['../classmfem_1_1GradientInterpolator.html',1,'mfem']]],
  ['graph_53',['Graph',['../classGecko_1_1Graph.html',1,'Gecko']]],
  ['gridcoefficient_54',['GridCoefficient',['../structmfem_1_1ceed_1_1GridCoefficient.html',1,'mfem::ceed']]],
  ['gridfunction_55',['GridFunction',['../classmfem_1_1GridFunction.html',1,'mfem']]],
  ['gridfunctioncoefficient_56',['GridFunctionCoefficient',['../classmfem_1_1GridFunctionCoefficient.html',1,'mfem']]],
  ['gridfunctionpumi_57',['GridFunctionPumi',['../classmfem_1_1GridFunctionPumi.html',1,'mfem']]],
  ['gridtransfer_58',['GridTransfer',['../classmfem_1_1GridTransfer.html',1,'mfem']]],
  ['groupcommunicator_59',['GroupCommunicator',['../classmfem_1_1GroupCommunicator.html',1,'mfem']]],
  ['groupconvectionintegrator_60',['GroupConvectionIntegrator',['../classmfem_1_1GroupConvectionIntegrator.html',1,'mfem']]],
  ['grouptopology_61',['GroupTopology',['../classmfem_1_1GroupTopology.html',1,'mfem']]],
  ['gssmoother_62',['GSSmoother',['../classmfem_1_1GSSmoother.html',1,'mfem']]]
];
