var searchData=
[
  ['s_5fspec',['S_spec',['../structmfem_1_1TBilinearForm_1_1S__spec.html',1,'mfem::TBilinearForm']]],
  ['saddleschwarzsmoother',['SaddleSchwarzSmoother',['../classmfem_1_1blocksolvers_1_1SaddleSchwarzSmoother.html',1,'mfem::blocksolvers']]],
  ['sbm2dirichletintegrator',['SBM2DirichletIntegrator',['../classmfem_1_1SBM2DirichletIntegrator.html',1,'mfem']]],
  ['sbm2dirichletlfintegrator',['SBM2DirichletLFIntegrator',['../classmfem_1_1SBM2DirichletLFIntegrator.html',1,'mfem']]],
  ['sbm2neumannintegrator',['SBM2NeumannIntegrator',['../classmfem_1_1SBM2NeumannIntegrator.html',1,'mfem']]],
  ['sbm2neumannlfintegrator',['SBM2NeumannLFIntegrator',['../classmfem_1_1SBM2NeumannLFIntegrator.html',1,'mfem']]],
  ['scalarcrossproductinterpolator',['ScalarCrossProductInterpolator',['../classmfem_1_1ScalarCrossProductInterpolator.html',1,'mfem']]],
  ['scalarfiniteelement',['ScalarFiniteElement',['../classmfem_1_1ScalarFiniteElement.html',1,'mfem']]],
  ['scalarlayout',['ScalarLayout',['../classmfem_1_1ScalarLayout.html',1,'mfem']]],
  ['scalarmatrixproductcoefficient',['ScalarMatrixProductCoefficient',['../classmfem_1_1ScalarMatrixProductCoefficient.html',1,'mfem']]],
  ['scalarops',['ScalarOps',['../structmfem_1_1ScalarOps.html',1,'mfem']]],
  ['scalarproductinterpolator',['ScalarProductInterpolator',['../classmfem_1_1ScalarProductInterpolator.html',1,'mfem']]],
  ['scalarvectorproductcoefficient',['ScalarVectorProductCoefficient',['../classmfem_1_1ScalarVectorProductCoefficient.html',1,'mfem']]],
  ['scalarvectorproductinterpolator',['ScalarVectorProductInterpolator',['../classmfem_1_1ScalarVectorProductInterpolator.html',1,'mfem']]],
  ['scaledgfcoefficient',['ScaledGFCoefficient',['../classmfem_1_1electromagnetics_1_1ScaledGFCoefficient.html',1,'mfem::electromagnetics']]],
  ['scaledoperator',['ScaledOperator',['../classmfem_1_1ScaledOperator.html',1,'mfem']]],
  ['schurconstrainedhypresolver',['SchurConstrainedHypreSolver',['../classmfem_1_1SchurConstrainedHypreSolver.html',1,'mfem']]],
  ['schurconstrainedsolver',['SchurConstrainedSolver',['../classmfem_1_1SchurConstrainedSolver.html',1,'mfem']]],
  ['screenedpoisson',['ScreenedPoisson',['../classmfem_1_1ScreenedPoisson.html',1,'mfem']]],
  ['sdirk23solver',['SDIRK23Solver',['../classmfem_1_1SDIRK23Solver.html',1,'mfem']]],
  ['sdirk33solver',['SDIRK33Solver',['../classmfem_1_1SDIRK33Solver.html',1,'mfem']]],
  ['sdirk34solver',['SDIRK34Solver',['../classmfem_1_1SDIRK34Solver.html',1,'mfem']]],
  ['secondorderodesolver',['SecondOrderODESolver',['../classmfem_1_1SecondOrderODESolver.html',1,'mfem']]],
  ['secondordertimedependentoperator',['SecondOrderTimeDependentOperator',['../classmfem_1_1SecondOrderTimeDependentOperator.html',1,'mfem']]],
  ['segment',['Segment',['../classmfem_1_1Segment.html',1,'mfem']]],
  ['serialadvectorcgoper',['SerialAdvectorCGOper',['../classmfem_1_1SerialAdvectorCGOper.html',1,'mfem']]],
  ['sesquilinearform',['SesquilinearForm',['../classmfem_1_1SesquilinearForm.html',1,'mfem']]],
  ['shapeevaluator',['ShapeEvaluator',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_3c_20fe_5ftype_2c_20ir_2c_20real_5ft_20_3e',['ShapeEvaluator&lt; FE_type, IR, real_t &gt;',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_3c_20meshfe_5ftype_2c_20ir_2c_20real_5ft_20_3e',['ShapeEvaluator&lt; meshFE_type, IR, real_t &gt;',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_3c_20solfe_5ftype_2c_20ir_2c_20real_5ft_20_3e',['ShapeEvaluator&lt; solFE_type, IR, real_t &gt;',['../classmfem_1_1ShapeEvaluator.html',1,'mfem']]],
  ['shapeevaluator_5fbase',['ShapeEvaluator_base',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_2c_20ir_2c_20false_2c_20real_5ft_20_3e',['ShapeEvaluator_base&lt; FE, IR, false, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base_3_01FE_00_01IR_00_01false_00_01real__t_01_4.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_2c_20ir_2c_20fe_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e',['ShapeEvaluator_base&lt; FE, IR, FE::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_2c_20ir_2c_20true_2c_20real_5ft_20_3e',['ShapeEvaluator_base&lt; FE, IR, true, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base_3_01FE_00_01IR_00_01true_00_01real__t_01_4.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20fe_5ftype_2c_20ir_2c_20fe_5ftype_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e',['ShapeEvaluator_base&lt; FE_type, IR, FE_type::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20meshfe_5ftype_2c_20ir_2c_20meshfe_5ftype_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e',['ShapeEvaluator_base&lt; meshFE_type, IR, meshFE_type::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shapeevaluator_5fbase_3c_20solfe_5ftype_2c_20ir_2c_20solfe_5ftype_3a_3atensor_5fprod_20_26_26ir_3a_3atensor_5fprod_2c_20real_5ft_20_3e',['ShapeEvaluator_base&lt; solFE_type, IR, solFE_type::tensor_prod &amp;&amp;IR::tensor_prod, real_t &gt;',['../classmfem_1_1ShapeEvaluator__base.html',1,'mfem']]],
  ['shiftedfacemarker',['ShiftedFaceMarker',['../classmfem_1_1ShiftedFaceMarker.html',1,'mfem']]],
  ['shiftedfunctioncoefficient',['ShiftedFunctionCoefficient',['../classmfem_1_1ShiftedFunctionCoefficient.html',1,'mfem']]],
  ['shiftedvectorfunctioncoefficient',['ShiftedVectorFunctionCoefficient',['../classmfem_1_1ShiftedVectorFunctionCoefficient.html',1,'mfem']]],
  ['sia1solver',['SIA1Solver',['../classmfem_1_1SIA1Solver.html',1,'mfem']]],
  ['sia2solver',['SIA2Solver',['../classmfem_1_1SIA2Solver.html',1,'mfem']]],
  ['siasolver',['SIASolver',['../classmfem_1_1SIASolver.html',1,'mfem']]],
  ['siavsolver',['SIAVSolver',['../classmfem_1_1SIAVSolver.html',1,'mfem']]],
  ['sidredatacollection',['SidreDataCollection',['../classmfem_1_1SidreDataCollection.html',1,'mfem']]],
  ['skewsymmetricvectorconvectionnlfintegrator',['SkewSymmetricVectorConvectionNLFIntegrator',['../classmfem_1_1SkewSymmetricVectorConvectionNLFIntegrator.html',1,'mfem']]],
  ['slave',['Slave',['../structmfem_1_1NCMesh_1_1Slave.html',1,'mfem::NCMesh']]],
  ['slbqpoptimizer',['SLBQPOptimizer',['../classmfem_1_1SLBQPOptimizer.html',1,'mfem']]],
  ['slepceigensolver',['SlepcEigenSolver',['../classmfem_1_1SlepcEigenSolver.html',1,'mfem']]],
  ['slisolver',['SLISolver',['../classmfem_1_1SLISolver.html',1,'mfem']]],
  ['socketbuf',['socketbuf',['../classmfem_1_1socketbuf.html',1,'mfem']]],
  ['socketserver',['socketserver',['../classmfem_1_1socketserver.html',1,'mfem']]],
  ['socketstream',['socketstream',['../classmfem_1_1socketstream.html',1,'mfem']]],
  ['solver',['Solver',['../classmfem_1_1Solver.html',1,'mfem']]],
  ['sparsematrix',['SparseMatrix',['../classmfem_1_1SparseMatrix.html',1,'mfem']]],
  ['sparsesmoother',['SparseSmoother',['../classmfem_1_1SparseSmoother.html',1,'mfem']]],
  ['spec',['Spec',['../structmfem_1_1FieldEvaluator_1_1Spec.html',1,'mfem::FieldEvaluator']]],
  ['stable',['STable',['../classmfem_1_1STable.html',1,'mfem']]],
  ['stable3d',['STable3D',['../classmfem_1_1STable3D.html',1,'mfem']]],
  ['stable3dnode',['STable3DNode',['../classmfem_1_1STable3DNode.html',1,'mfem']]],
  ['stack',['Stack',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20elem_20_2a_2c_20num_20_3e',['Stack&lt; Elem *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20mfem_3a_3astable3dnode_20_2a_2c_20num_20_3e',['Stack&lt; mfem::STable3DNode *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20mfem_3a_3atetrahedron_20_2a_2c_20num_20_3e',['Stack&lt; mfem::Tetrahedron *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stack_3c_20node_20_2a_2c_20num_20_3e',['Stack&lt; Node *, Num &gt;',['../classmfem_1_1Stack.html',1,'mfem']]],
  ['stackpart',['StackPart',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['stackpart_3c_20elem_20_2a_2c_20num_20_3e',['StackPart&lt; Elem *, Num &gt;',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['stackpart_3c_20mfem_3a_3astable3dnode_20_2a_2c_20num_20_3e',['StackPart&lt; mfem::STable3DNode *, Num &gt;',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['stackpart_3c_20mfem_3a_3atetrahedron_20_2a_2c_20num_20_3e',['StackPart&lt; mfem::Tetrahedron *, Num &gt;',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['stackpart_3c_20node_20_2a_2c_20num_20_3e',['StackPart&lt; Node *, Num &gt;',['../classmfem_1_1StackPart.html',1,'mfem']]],
  ['static_5fmethod_5fholder',['static_method_holder',['../structstrict__fstream_1_1detail_1_1static__method__holder.html',1,'strict_fstream::detail']]],
  ['staticcondensation',['StaticCondensation',['../classmfem_1_1StaticCondensation.html',1,'mfem']]],
  ['stopwatch',['StopWatch',['../classmfem_1_1StopWatch.html',1,'mfem']]],
  ['strict_5ffstream_5fholder',['strict_fstream_holder',['../structzstr_1_1detail_1_1strict__fstream__holder.html',1,'zstr::detail']]],
  ['strict_5ffstream_5fholder_3c_20strict_5ffstream_3a_3aifstream_20_3e',['strict_fstream_holder&lt; strict_fstream::ifstream &gt;',['../structzstr_1_1detail_1_1strict__fstream__holder.html',1,'zstr::detail']]],
  ['strict_5ffstream_5fholder_3c_20strict_5ffstream_3a_3aofstream_20_3e',['strict_fstream_holder&lt; strict_fstream::ofstream &gt;',['../structzstr_1_1detail_1_1strict__fstream__holder.html',1,'zstr::detail']]],
  ['stridedlayout1d',['StridedLayout1D',['../structmfem_1_1StridedLayout1D.html',1,'mfem']]],
  ['stridedlayout2d',['StridedLayout2D',['../structmfem_1_1StridedLayout2D.html',1,'mfem']]],
  ['stridedlayout2d_3c_20n1_2c_201_2c_20n2_2c_20n1_20_3e',['StridedLayout2D&lt; N1, 1, N2, N1 &gt;',['../structmfem_1_1StridedLayout2D.html',1,'mfem']]],
  ['stridedlayout3d',['StridedLayout3D',['../structmfem_1_1StridedLayout3D.html',1,'mfem']]],
  ['stridedlayout3d_3c_20n1_2c_201_2c_20n2_2c_20n1_2c_20n3_2c_20n1_20_2an2_20_3e',['StridedLayout3D&lt; N1, 1, N2, N1, N3, N1 *N2 &gt;',['../structmfem_1_1StridedLayout3D.html',1,'mfem']]],
  ['stridedlayout4d',['StridedLayout4D',['../structmfem_1_1StridedLayout4D.html',1,'mfem']]],
  ['stridedlayout4d_3c_20n1_2c_201_2c_20n2_2c_20n1_2c_20n3_2c_20n1_20_2an2_2c_20n4_2c_20n1_20_2an2_20_2an3_20_3e',['StridedLayout4D&lt; N1, 1, N2, N1, N3, N1 *N2, N4, N1 *N2 *N3 &gt;',['../structmfem_1_1StridedLayout4D.html',1,'mfem']]],
  ['strumpackrowlocmatrix',['STRUMPACKRowLocMatrix',['../classmfem_1_1STRUMPACKRowLocMatrix.html',1,'mfem']]],
  ['strumpacksolver',['STRUMPACKSolver',['../classmfem_1_1STRUMPACKSolver.html',1,'mfem']]],
  ['sumcoefficient',['SumCoefficient',['../classmfem_1_1SumCoefficient.html',1,'mfem']]],
  ['sumintegrator',['SumIntegrator',['../classmfem_1_1SumIntegrator.html',1,'mfem']]],
  ['sundialsnvector',['SundialsNVector',['../classmfem_1_1SundialsNVector.html',1,'mfem']]],
  ['sundialssolver',['SundialsSolver',['../classmfem_1_1SundialsSolver.html',1,'mfem']]],
  ['superlurowlocmatrix',['SuperLURowLocMatrix',['../classmfem_1_1SuperLURowLocMatrix.html',1,'mfem']]],
  ['superlusolver',['SuperLUSolver',['../classmfem_1_1SuperLUSolver.html',1,'mfem']]],
  ['surfacecurrent',['SurfaceCurrent',['../classmfem_1_1electromagnetics_1_1SurfaceCurrent.html',1,'mfem::electromagnetics']]],
  ['symdirectsubblocksolver',['SymDirectSubBlockSolver',['../classmfem_1_1blocksolvers_1_1SymDirectSubBlockSolver.html',1,'mfem::blocksolvers']]],
  ['symmetricmatrixcoefficient',['SymmetricMatrixCoefficient',['../classmfem_1_1SymmetricMatrixCoefficient.html',1,'mfem']]],
  ['symmetricmatrixconstantcoefficient',['SymmetricMatrixConstantCoefficient',['../classmfem_1_1SymmetricMatrixConstantCoefficient.html',1,'mfem']]],
  ['symmetricmatrixfunctioncoefficient',['SymmetricMatrixFunctionCoefficient',['../classmfem_1_1SymmetricMatrixFunctionCoefficient.html',1,'mfem']]]
];
