var searchData=
[
  ['rajacuwrap',['RajaCuWrap',['../structmfem_1_1RajaCuWrap.html',1,'mfem']]],
  ['rajacuwrap_3c_201_20_3e',['RajaCuWrap&lt; 1 &gt;',['../structmfem_1_1RajaCuWrap_3_011_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_202_20_3e',['RajaCuWrap&lt; 2 &gt;',['../structmfem_1_1RajaCuWrap_3_012_01_4.html',1,'mfem']]],
  ['rajacuwrap_3c_203_20_3e',['RajaCuWrap&lt; 3 &gt;',['../structmfem_1_1RajaCuWrap_3_013_01_4.html',1,'mfem']]],
  ['rajahipwrap',['RajaHipWrap',['../structmfem_1_1RajaHipWrap.html',1,'mfem']]],
  ['rajahipwrap_3c_201_20_3e',['RajaHipWrap&lt; 1 &gt;',['../structmfem_1_1RajaHipWrap_3_011_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_202_20_3e',['RajaHipWrap&lt; 2 &gt;',['../structmfem_1_1RajaHipWrap_3_012_01_4.html',1,'mfem']]],
  ['rajahipwrap_3c_203_20_3e',['RajaHipWrap&lt; 3 &gt;',['../structmfem_1_1RajaHipWrap_3_013_01_4.html',1,'mfem']]],
  ['rapoperator',['RAPOperator',['../classmfem_1_1RAPOperator.html',1,'mfem']]],
  ['ratiocoefficient',['RatioCoefficient',['../classmfem_1_1RatioCoefficient.html',1,'mfem']]],
  ['rebalancedofmessage',['RebalanceDofMessage',['../classmfem_1_1ParNCMesh_1_1RebalanceDofMessage.html',1,'mfem::ParNCMesh']]],
  ['rebalancemessage',['RebalanceMessage',['../classmfem_1_1ParNCMesh_1_1RebalanceMessage.html',1,'mfem::ParNCMesh']]],
  ['rebalancer',['Rebalancer',['../classmfem_1_1Rebalancer.html',1,'mfem']]],
  ['rectangularconstrainedoperator',['RectangularConstrainedOperator',['../classmfem_1_1RectangularConstrainedOperator.html',1,'mfem']]],
  ['refinedbilinear2dfiniteelement',['RefinedBiLinear2DFiniteElement',['../classmfem_1_1RefinedBiLinear2DFiniteElement.html',1,'mfem']]],
  ['refinedgeometry',['RefinedGeometry',['../classmfem_1_1RefinedGeometry.html',1,'mfem']]],
  ['refinedlinear1dfiniteelement',['RefinedLinear1DFiniteElement',['../classmfem_1_1RefinedLinear1DFiniteElement.html',1,'mfem']]],
  ['refinedlinear2dfiniteelement',['RefinedLinear2DFiniteElement',['../classmfem_1_1RefinedLinear2DFiniteElement.html',1,'mfem']]],
  ['refinedlinear3dfiniteelement',['RefinedLinear3DFiniteElement',['../classmfem_1_1RefinedLinear3DFiniteElement.html',1,'mfem']]],
  ['refinedlinearfecollection',['RefinedLinearFECollection',['../classmfem_1_1RefinedLinearFECollection.html',1,'mfem']]],
  ['refinedtrilinear3dfiniteelement',['RefinedTriLinear3DFiniteElement',['../classmfem_1_1RefinedTriLinear3DFiniteElement.html',1,'mfem']]],
  ['refinement',['Refinement',['../structmfem_1_1Refinement.html',1,'mfem']]],
  ['refinementoperator',['RefinementOperator',['../classmfem_1_1FiniteElementSpace_1_1RefinementOperator.html',1,'mfem::FiniteElementSpace']]],
  ['residualbcmonitor',['ResidualBCMonitor',['../classmfem_1_1ResidualBCMonitor.html',1,'mfem']]],
  ['residuallogger',['ResidualLogger',['../structmfem_1_1Ginkgo_1_1ResidualLogger.html',1,'mfem::Ginkgo']]],
  ['restrictedcoefficient',['RestrictedCoefficient',['../classmfem_1_1RestrictedCoefficient.html',1,'mfem']]],
  ['result',['Result',['../structmfem_1_1TElementTransformation_1_1Result.html',1,'mfem::TElementTransformation']]],
  ['result_3c_200_2c_20it_5ft_20_3e',['Result&lt; 0, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_010_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_201_2c_20it_5ft_20_3e',['Result&lt; 1, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_011_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_2010_2c_20it_5ft_20_3e',['Result&lt; 10, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_0110_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_202_2c_20it_5ft_20_3e',['Result&lt; 2, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_012_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_203_2c_20it_5ft_20_3e',['Result&lt; 3, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_013_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_3c_206_2c_20it_5ft_20_3e',['Result&lt; 6, it_t &gt;',['../structmfem_1_1TElementTransformation_1_1Result_3_016_00_01it__t_01_4.html',1,'mfem::TElementTransformation']]],
  ['result_5ft',['result_t',['../structmfem_1_1IntRuleCoefficient_1_1Aux_3_01true_00_01dummy_01_4_1_1result__t.html',1,'mfem::IntRuleCoefficient::Aux&lt; true, dummy &gt;']]],
  ['riemannsolver',['RiemannSolver',['../classRiemannSolver.html',1,'']]],
  ['rk2solver',['RK2Solver',['../classmfem_1_1RK2Solver.html',1,'mfem']]],
  ['rk3sspsolver',['RK3SSPSolver',['../classmfem_1_1RK3SSPSolver.html',1,'mfem']]],
  ['rk4solver',['RK4Solver',['../classmfem_1_1RK4Solver.html',1,'mfem']]],
  ['rk6solver',['RK6Solver',['../classmfem_1_1RK6Solver.html',1,'mfem']]],
  ['rk8solver',['RK8Solver',['../classmfem_1_1RK8Solver.html',1,'mfem']]],
  ['rottrilinearhexfiniteelement',['RotTriLinearHexFiniteElement',['../classmfem_1_1RotTriLinearHexFiniteElement.html',1,'mfem']]],
  ['rowiterator',['RowIterator',['../classmfem_1_1DSTable_1_1RowIterator.html',1,'mfem::DSTable']]],
  ['rt0_5f2dfecollection',['RT0_2DFECollection',['../classmfem_1_1RT0__2DFECollection.html',1,'mfem']]],
  ['rt0_5f3dfecollection',['RT0_3DFECollection',['../classmfem_1_1RT0__3DFECollection.html',1,'mfem']]],
  ['rt0hexfiniteelement',['RT0HexFiniteElement',['../classmfem_1_1RT0HexFiniteElement.html',1,'mfem']]],
  ['rt0pyrfiniteelement',['RT0PyrFiniteElement',['../classmfem_1_1RT0PyrFiniteElement.html',1,'mfem']]],
  ['rt0quadfiniteelement',['RT0QuadFiniteElement',['../classmfem_1_1RT0QuadFiniteElement.html',1,'mfem']]],
  ['rt0tetfiniteelement',['RT0TetFiniteElement',['../classmfem_1_1RT0TetFiniteElement.html',1,'mfem']]],
  ['rt0trianglefiniteelement',['RT0TriangleFiniteElement',['../classmfem_1_1RT0TriangleFiniteElement.html',1,'mfem']]],
  ['rt0wdgfiniteelement',['RT0WdgFiniteElement',['../classmfem_1_1RT0WdgFiniteElement.html',1,'mfem']]],
  ['rt1_5f2dfecollection',['RT1_2DFECollection',['../classmfem_1_1RT1__2DFECollection.html',1,'mfem']]],
  ['rt1_5f3dfecollection',['RT1_3DFECollection',['../classmfem_1_1RT1__3DFECollection.html',1,'mfem']]],
  ['rt1hexfiniteelement',['RT1HexFiniteElement',['../classmfem_1_1RT1HexFiniteElement.html',1,'mfem']]],
  ['rt1quadfiniteelement',['RT1QuadFiniteElement',['../classmfem_1_1RT1QuadFiniteElement.html',1,'mfem']]],
  ['rt1trianglefiniteelement',['RT1TriangleFiniteElement',['../classmfem_1_1RT1TriangleFiniteElement.html',1,'mfem']]],
  ['rt2_5f2dfecollection',['RT2_2DFECollection',['../classmfem_1_1RT2__2DFECollection.html',1,'mfem']]],
  ['rt2quadfiniteelement',['RT2QuadFiniteElement',['../classmfem_1_1RT2QuadFiniteElement.html',1,'mfem']]],
  ['rt2trianglefiniteelement',['RT2TriangleFiniteElement',['../classmfem_1_1RT2TriangleFiniteElement.html',1,'mfem']]],
  ['rt_5ffecollection',['RT_FECollection',['../classmfem_1_1RT__FECollection.html',1,'mfem']]],
  ['rt_5ffespace',['RT_FESpace',['../classmfem_1_1common_1_1RT__FESpace.html',1,'mfem::common']]],
  ['rt_5fhexahedronelement',['RT_HexahedronElement',['../classmfem_1_1RT__HexahedronElement.html',1,'mfem']]],
  ['rt_5fparfespace',['RT_ParFESpace',['../classmfem_1_1common_1_1RT__ParFESpace.html',1,'mfem::common']]],
  ['rt_5fquadrilateralelement',['RT_QuadrilateralElement',['../classmfem_1_1RT__QuadrilateralElement.html',1,'mfem']]],
  ['rt_5fr1d_5ffecollection',['RT_R1D_FECollection',['../classmfem_1_1RT__R1D__FECollection.html',1,'mfem']]],
  ['rt_5fr1d_5fsegmentelement',['RT_R1D_SegmentElement',['../classmfem_1_1RT__R1D__SegmentElement.html',1,'mfem']]],
  ['rt_5fr2d_5ffecollection',['RT_R2D_FECollection',['../classmfem_1_1RT__R2D__FECollection.html',1,'mfem']]],
  ['rt_5fr2d_5ffiniteelement',['RT_R2D_FiniteElement',['../classmfem_1_1RT__R2D__FiniteElement.html',1,'mfem']]],
  ['rt_5fr2d_5fquadrilateralelement',['RT_R2D_QuadrilateralElement',['../classmfem_1_1RT__R2D__QuadrilateralElement.html',1,'mfem']]],
  ['rt_5fr2d_5fsegmentelement',['RT_R2D_SegmentElement',['../classmfem_1_1RT__R2D__SegmentElement.html',1,'mfem']]],
  ['rt_5fr2d_5ftrace_5ffecollection',['RT_R2D_Trace_FECollection',['../classmfem_1_1RT__R2D__Trace__FECollection.html',1,'mfem']]],
  ['rt_5fr2d_5ftriangleelement',['RT_R2D_TriangleElement',['../classmfem_1_1RT__R2D__TriangleElement.html',1,'mfem']]],
  ['rt_5ftetrahedronelement',['RT_TetrahedronElement',['../classmfem_1_1RT__TetrahedronElement.html',1,'mfem']]],
  ['rt_5ftrace_5ffecollection',['RT_Trace_FECollection',['../classmfem_1_1RT__Trace__FECollection.html',1,'mfem']]],
  ['rt_5ftriangleelement',['RT_TriangleElement',['../classmfem_1_1RT__TriangleElement.html',1,'mfem']]],
  ['rt_5fwedgeelement',['RT_WedgeElement',['../classmfem_1_1RT__WedgeElement.html',1,'mfem']]]
];
