var searchData=
[
  ['l2_5ffecollection',['L2_FECollection',['../classmfem_1_1L2__FECollection.html',1,'mfem']]],
  ['l2_5ffiniteelement',['L2_FiniteElement',['../classmfem_1_1L2__FiniteElement.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3acube_2c_20p_20_3e',['L2_FiniteElement&lt; Geometry::CUBE, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1CUBE_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3asegment_2c_20p_20_3e',['L2_FiniteElement&lt; Geometry::SEGMENT, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1SEGMENT_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3asquare_2c_20p_20_3e',['L2_FiniteElement&lt; Geometry::SQUARE, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1SQUARE_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3atetrahedron_2c_20p_20_3e',['L2_FiniteElement&lt; Geometry::TETRAHEDRON, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1TETRAHEDRON_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_3c_20geometry_3a_3atriangle_2c_20p_20_3e',['L2_FiniteElement&lt; Geometry::TRIANGLE, P &gt;',['../classmfem_1_1L2__FiniteElement_3_01Geometry_1_1TRIANGLE_00_01P_01_4.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase',['L2_FiniteElement_base',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3acube_2c_20p_2c_20l2_5fhexahedronelement_2c_20l2pos_5fhexahedronelement_2c_28p_2b1_29_2a_28p_2b1_29_2a_28p_2b1_29_2c_20true_20_3e',['L2_FiniteElement_base&lt; Geometry::CUBE, P, L2_HexahedronElement, L2Pos_HexahedronElement,(P+1)*(P+1)*(P+1), true &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3asegment_2c_20p_2c_20l2_5fsegmentelement_2c_20l2pos_5fsegmentelement_2c_20p_2b1_2c_20true_20_3e',['L2_FiniteElement_base&lt; Geometry::SEGMENT, P, L2_SegmentElement, L2Pos_SegmentElement, P+1, true &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3asquare_2c_20p_2c_20l2_5fquadrilateralelement_2c_20l2pos_5fquadrilateralelement_2c_28p_2b1_29_2a_28p_2b1_29_2c_20true_20_3e',['L2_FiniteElement_base&lt; Geometry::SQUARE, P, L2_QuadrilateralElement, L2Pos_QuadrilateralElement,(P+1)*(P+1), true &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3atetrahedron_2c_20p_2c_20l2_5ftetrahedronelement_2c_20l2pos_5ftetrahedronelement_2c_28_28p_2b1_29_2a_28p_2b2_29_2a_28p_2b3_29_29_2f6_2c_20false_20_3e',['L2_FiniteElement_base&lt; Geometry::TETRAHEDRON, P, L2_TetrahedronElement, L2Pos_TetrahedronElement,((P+1)*(P+2)*(P+3))/6, false &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelement_5fbase_3c_20geometry_3a_3atriangle_2c_20p_2c_20l2_5ftriangleelement_2c_20l2pos_5ftriangleelement_2c_28_28p_2b1_29_2a_28p_2b2_29_29_2f2_2c_20false_20_3e',['L2_FiniteElement_base&lt; Geometry::TRIANGLE, P, L2_TriangleElement, L2Pos_TriangleElement,((P+1)*(P+2))/2, false &gt;',['../classmfem_1_1L2__FiniteElement__base.html',1,'mfem']]],
  ['l2_5ffiniteelementspace',['L2_FiniteElementSpace',['../classmfem_1_1L2__FiniteElementSpace.html',1,'mfem']]],
  ['l2_5fhexahedronelement',['L2_HexahedronElement',['../classmfem_1_1L2__HexahedronElement.html',1,'mfem']]],
  ['l2_5fparfespace',['L2_ParFESpace',['../classmfem_1_1common_1_1L2__ParFESpace.html',1,'mfem::common']]],
  ['l2_5fquadrilateralelement',['L2_QuadrilateralElement',['../classmfem_1_1L2__QuadrilateralElement.html',1,'mfem']]],
  ['l2_5fsegmentelement',['L2_SegmentElement',['../classmfem_1_1L2__SegmentElement.html',1,'mfem']]],
  ['l2_5ftetrahedronelement',['L2_TetrahedronElement',['../classmfem_1_1L2__TetrahedronElement.html',1,'mfem']]],
  ['l2_5ftriangleelement',['L2_TriangleElement',['../classmfem_1_1L2__TriangleElement.html',1,'mfem']]],
  ['l2_5fwedgeelement',['L2_WedgeElement',['../classmfem_1_1L2__WedgeElement.html',1,'mfem']]],
  ['l2elementrestriction',['L2ElementRestriction',['../classmfem_1_1L2ElementRestriction.html',1,'mfem']]],
  ['l2facerestriction',['L2FaceRestriction',['../classmfem_1_1L2FaceRestriction.html',1,'mfem']]],
  ['l2pos_5fhexahedronelement',['L2Pos_HexahedronElement',['../classmfem_1_1L2Pos__HexahedronElement.html',1,'mfem']]],
  ['l2pos_5fquadrilateralelement',['L2Pos_QuadrilateralElement',['../classmfem_1_1L2Pos__QuadrilateralElement.html',1,'mfem']]],
  ['l2pos_5fsegmentelement',['L2Pos_SegmentElement',['../classmfem_1_1L2Pos__SegmentElement.html',1,'mfem']]],
  ['l2pos_5ftetrahedronelement',['L2Pos_TetrahedronElement',['../classmfem_1_1L2Pos__TetrahedronElement.html',1,'mfem']]],
  ['l2pos_5ftriangleelement',['L2Pos_TriangleElement',['../classmfem_1_1L2Pos__TriangleElement.html',1,'mfem']]],
  ['l2pos_5fwedgeelement',['L2Pos_WedgeElement',['../classmfem_1_1L2Pos__WedgeElement.html',1,'mfem']]],
  ['l2projection',['L2Projection',['../classmfem_1_1L2ProjectionGridTransfer_1_1L2Projection.html',1,'mfem::L2ProjectionGridTransfer']]],
  ['l2projectiongridtransfer',['L2ProjectionGridTransfer',['../classmfem_1_1L2ProjectionGridTransfer.html',1,'mfem']]],
  ['l2prolongation',['L2Prolongation',['../classmfem_1_1L2ProjectionGridTransfer_1_1L2Prolongation.html',1,'mfem::L2ProjectionGridTransfer']]],
  ['l2zienkiewiczzhuestimator',['L2ZienkiewiczZhuEstimator',['../classmfem_1_1L2ZienkiewiczZhuEstimator.html',1,'mfem']]],
  ['lagrange1dfiniteelement',['Lagrange1DFiniteElement',['../classmfem_1_1Lagrange1DFiniteElement.html',1,'mfem']]],
  ['lagrangehexfiniteelement',['LagrangeHexFiniteElement',['../classmfem_1_1LagrangeHexFiniteElement.html',1,'mfem']]],
  ['linear1dfiniteelement',['Linear1DFiniteElement',['../classmfem_1_1Linear1DFiniteElement.html',1,'mfem']]],
  ['linear2dfiniteelement',['Linear2DFiniteElement',['../classmfem_1_1Linear2DFiniteElement.html',1,'mfem']]],
  ['linear3dfiniteelement',['Linear3DFiniteElement',['../classmfem_1_1Linear3DFiniteElement.html',1,'mfem']]],
  ['linearaccelerationsolver',['LinearAccelerationSolver',['../classmfem_1_1LinearAccelerationSolver.html',1,'mfem']]],
  ['lineardiscont2dfecollection',['LinearDiscont2DFECollection',['../classmfem_1_1LinearDiscont2DFECollection.html',1,'mfem']]],
  ['lineardiscont3dfecollection',['LinearDiscont3DFECollection',['../classmfem_1_1LinearDiscont3DFECollection.html',1,'mfem']]],
  ['linearfecollection',['LinearFECollection',['../classmfem_1_1LinearFECollection.html',1,'mfem']]],
  ['linearform',['LinearForm',['../classmfem_1_1LinearForm.html',1,'mfem']]],
  ['linearformintegrator',['LinearFormIntegrator',['../classmfem_1_1LinearFormIntegrator.html',1,'mfem']]],
  ['linearnonconf3dfecollection',['LinearNonConf3DFECollection',['../classmfem_1_1LinearNonConf3DFECollection.html',1,'mfem']]],
  ['listofintegersets',['ListOfIntegerSets',['../classmfem_1_1ListOfIntegerSets.html',1,'mfem']]],
  ['local_5ffecollection',['Local_FECollection',['../classmfem_1_1Local__FECollection.html',1,'mfem']]],
  ['lufactors',['LUFactors',['../classmfem_1_1LUFactors.html',1,'mfem']]],
  ['lumpedintegrator',['LumpedIntegrator',['../classmfem_1_1LumpedIntegrator.html',1,'mfem']]]
];
