MFEM: array.hpp File Reference
array.hpp File Reference
#include <iostream>
#include <cstdlib>
#include <cstring>
#include "error.hpp"
Classes
class BaseArray
Base class for array container.
class Array< T >
class Array2D< T >
class Array3D< T >
Functions
template<class T >
void Swap (Array< T > &, Array< T > &)
template<class T >
void Swap (Array2D< T > &, Array2D< T > &)
template<class T >
void Swap (T &a, T &b)
Function Documentation
template<class T > void Swap (Array< T > & a, Array< T > & b) [inline]
Definition at line 243 of file array.hpp.
References BaseArray::allocsize, BaseArray::data, BaseArray::inc, and BaseArray::size.
Referenced by FiniteElementSpace::FiniteElementSpace(), Mesh::HexUniformRefinement(), Mesh::LocalRefinement(), Mesh::QuadUniformRefinement(), Mesh::SetState(), and Swap().
template<class T > void Swap (Array2D< T > & a, Array2D< T > & b) [inline]
Definition at line 461 of file array.hpp.
References Array2D< T >::array1d, Array2D< T >::N, and Swap().
template<class T > void Swap (T & a, T & b) [inline]
Definition at line 235 of file array.hpp.