MFEM: bicgstab.cpp File Reference
bicgstab.cpp File Reference
#include <iostream>
#include <iomanip>
#include "vector.hpp"
#include "matrix.hpp"
Functions
int BiCGSTAB (const Operator &A, Vector &x, const Vector &b, const Operator &M, int &max_iter, double &tol, double atol, int printit)
A BiCG-Stab solver.
Function Documentation
int BiCGSTAB (const Operator & A, Vector & x, const Vector & b, const Operator & M, int & max_iter, double & tol, double atol, int printit)
A BiCG-Stab solver.
Definition at line 39 of file bicgstab.cpp.
References Vector::Add(), add(), Operator::Mult(), Operator::Size(), and subtract().