MFEM: ElementTransformation Class Reference
ElementTransformation Class Reference
#include <eltrans.hpp>
Public Member Functions
void SetIntPoint (const IntegrationPoint *ip)
const IntegrationPoint & GetIntPoint ()
virtual void Transform (const IntegrationPoint &, Vector &)=0
virtual void Transform (const IntegrationRule &, DenseMatrix &)=0
virtual const DenseMatrix & Jacobian ()=0
virtual double Weight ()=0
virtual int OrderJ ()=0
virtual int OrderW ()=0
virtual int OrderGrad (const FiniteElement *fe)=0
order of adj(J)^t.grad(fi)
virtual ~ElementTransformation ()
Public Attributes
int Attribute
int ElementNo
Protected Attributes
int JacobianIsEvaluated
int WeightIsEvaluated
const IntegrationPoint * IntPoint
Detailed Description
Definition at line 15 of file eltrans.hpp.
Constructor & Destructor Documentation
virtual ElementTransformation::~ElementTransformation () [inline, virtual]
Definition at line 40 of file eltrans.hpp.
Member Function Documentation
const IntegrationPoint& ElementTransformation::GetIntPoint () [inline]
Definition at line 26 of file eltrans.hpp.
References IntPoint.
Referenced by VectorFiniteElement::CalcVShape_ND(), VectorFiniteElement::CalcVShape_RT(), GridFunction::GetDivergence(), and GridFunction::GetVectorGradientHat().
virtual const DenseMatrix& ElementTransformation::Jacobian () [pure virtual]
Return the jacobian of the transformation at the IntPoint. The first column contains the x derivatives of the transformation, the second -- the y derivatives, etc.
Implemented in IsoparametricTransformation.
Referenced by DiffusionIntegrator::AssembleElementMatrix(), ConvectionIntegrator::AssembleElementMatrix(), CurlCurlIntegrator::AssembleElementMatrix(), VectorDiffusionIntegrator::AssembleElementMatrix(), ElasticityIntegrator::AssembleElementMatrix(), VectorFECurlIntegrator::AssembleElementMatrix2(), DerivativeIntegrator::AssembleElementMatrix2(), VectorDivergenceIntegrator::AssembleElementMatrix2(), VectorBoundaryFluxLFIntegrator::AssembleRHSElementVect(), VectorFiniteElement::CalcVShape_ND(), VectorFiniteElement::CalcVShape_RT(), DiffusionIntegrator::ComputeElementFlux(), GridFunction::ComputeH1Error(), GridFunction::ComputeW11Error(), GridFunction::GetDerivative(), GridFunction::GetDivergence(), Mesh::GetElementJacobian(), GridFunction::GetGradients(), RT0TriangleFiniteElement::GetLocalInterpolation(), RT0QuadFiniteElement::GetLocalInterpolation(), RT1TriangleFiniteElement::GetLocalInterpolation(), RT1QuadFiniteElement::GetLocalInterpolation(), RT2QuadFiniteElement::GetLocalInterpolation(), Nedelec1HexFiniteElement::GetLocalInterpolation(), Nedelec1TetFiniteElement::GetLocalInterpolation(), RT0HexFiniteElement::GetLocalInterpolation(), RT1HexFiniteElement::GetLocalInterpolation(), RT0TetFiniteElement::GetLocalInterpolation(), GridFunction::GetVectorGradient(), VectorFiniteElement::LocalInterpolation_ND(), VectorFiniteElement::LocalInterpolation_RT(), RT0TriangleFiniteElement::Project(), RT0QuadFiniteElement::Project(), RT1TriangleFiniteElement::Project(), RT1QuadFiniteElement::Project(), RT2QuadFiniteElement::Project(), Nedelec1HexFiniteElement::Project(), Nedelec1TetFiniteElement::Project(), RT0HexFiniteElement::Project(), RT1HexFiniteElement::Project(), RT0TetFiniteElement::Project(), VectorFiniteElement::Project_ND(), VectorFiniteElement::Project_RT(), GridFunction::ProjectBdrCoefficientNormal(), and NodalFiniteElement::ProjectGrad().
virtual int ElementTransformation::OrderGrad (const FiniteElement * fe) [pure virtual]
order of adj(J)^t.grad(fi)
Implemented in IsoparametricTransformation.
Referenced by VectorDiffusionIntegrator::AssembleElementMatrix(), ElasticityIntegrator::AssembleElementMatrix(), and VectorDivergenceIntegrator::AssembleElementMatrix2().
virtual int ElementTransformation::OrderJ () [pure virtual]
Implemented in IsoparametricTransformation.
Referenced by Mesh::GetElementVolume().
virtual int ElementTransformation::OrderW () [pure virtual]
Implemented in IsoparametricTransformation.
Referenced by MassIntegrator::AssembleElementMatrix(), VectorMassIntegrator::AssembleElementMatrix(), VectorFEMassIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix2(), and VectorFEMassIntegrator::AssembleElementMatrix2().
void ElementTransformation::SetIntPoint (const IntegrationPoint * ip) [inline]
Definition at line 24 of file eltrans.hpp.
References IntPoint, JacobianIsEvaluated, and WeightIsEvaluated.
Referenced by DiffusionIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix(), ConvectionIntegrator::AssembleElementMatrix(), VectorMassIntegrator::AssembleElementMatrix(), CurlCurlIntegrator::AssembleElementMatrix(), VectorFEMassIntegrator::AssembleElementMatrix(), DivDivIntegrator::AssembleElementMatrix(), VectorDiffusionIntegrator::AssembleElementMatrix(), ElasticityIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix2(), VectorFEDivergenceIntegrator::AssembleElementMatrix2(), VectorFECurlIntegrator::AssembleElementMatrix2(), DerivativeIntegrator::AssembleElementMatrix2(), VectorFEMassIntegrator::AssembleElementMatrix2(), VectorDivergenceIntegrator::AssembleElementMatrix2(), DomainLFIntegrator::AssembleRHSElementVect(), BoundaryLFIntegrator::AssembleRHSElementVect(), VectorDomainLFIntegrator::AssembleRHSElementVect(), VectorBoundaryLFIntegrator::AssembleRHSElementVect(), VectorFEDomainLFIntegrator::AssembleRHSElementVect(), VectorBoundaryFluxLFIntegrator::AssembleRHSElementVect(), VectorFEBoundaryFluxLFIntegrator::AssembleRHSElementVect(), DiffusionIntegrator::ComputeElementFlux(), DiffusionIntegrator::ComputeFluxEnergy(), GridFunction::ComputeH1Error(), GridFunction::ComputeL1Error(), GridFunction::ComputeL2Error(), ComputeLpNorm(), GridFunction::ComputeMaxError(), GridFunction::ComputeW11Error(), VectorCoefficient::Eval(), Geometry::Geometry(), GridFunction::GetDerivative(), Mesh::GetElementJacobian(), Mesh::GetElementVolume(), GridFunction::GetGradients(), RT0TriangleFiniteElement::GetLocalInterpolation(), RT0QuadFiniteElement::GetLocalInterpolation(), RT1TriangleFiniteElement::GetLocalInterpolation(), RT1QuadFiniteElement::GetLocalInterpolation(), RT2QuadFiniteElement::GetLocalInterpolation(), Nedelec1HexFiniteElement::GetLocalInterpolation(), Nedelec1TetFiniteElement::GetLocalInterpolation(), RT0HexFiniteElement::GetLocalInterpolation(), RT1HexFiniteElement::GetLocalInterpolation(), RT0TetFiniteElement::GetLocalInterpolation(), GridFunction::GetNodalValues(), GridFunction::GetVectorFieldValues(), GridFunction::GetVectorValue(), GridFunction::GetVectorValues(), VectorFiniteElement::LocalInterpolation_ND(), VectorFiniteElement::LocalInterpolation_RT(), NodalFiniteElement::Project(), BiQuadPos2DFiniteElement::Project(), RT0TriangleFiniteElement::Project(), RT0QuadFiniteElement::Project(), RT1TriangleFiniteElement::Project(), RT1QuadFiniteElement::Project(), RT2QuadFiniteElement::Project(), Nedelec1HexFiniteElement::Project(), Nedelec1TetFiniteElement::Project(), RT0HexFiniteElement::Project(), RT1HexFiniteElement::Project(), RT0TetFiniteElement::Project(), VectorFiniteElement::Project_ND(), VectorFiniteElement::Project_RT(), GridFunction::ProjectBdrCoefficient(), GridFunction::ProjectBdrCoefficientNormal(), GridFunction::ProjectCoefficient(), NodalFiniteElement::ProjectDiv(), and NodalFiniteElement::ProjectGrad().
virtual void ElementTransformation::Transform (const IntegrationPoint & , Vector &) [pure virtual]
Implemented in IsoparametricTransformation.
Referenced by FunctionCoefficient::Eval(), VectorFunctionCoefficient::Eval(), MatrixFunctionCoefficient::Eval(), RT0TriangleFiniteElement::GetLocalInterpolation(), RT0QuadFiniteElement::GetLocalInterpolation(), RT1TriangleFiniteElement::GetLocalInterpolation(), RT1QuadFiniteElement::GetLocalInterpolation(), RT2QuadFiniteElement::GetLocalInterpolation(), Nedelec1HexFiniteElement::GetLocalInterpolation(), Nedelec1TetFiniteElement::GetLocalInterpolation(), RT0HexFiniteElement::GetLocalInterpolation(), RT1HexFiniteElement::GetLocalInterpolation(), RT0TetFiniteElement::GetLocalInterpolation(), GridFunction::GetValues(), GridFunction::GetVectorFieldValues(), GridFunction::GetVectorValues(), VectorFiniteElement::LocalInterpolation_ND(), VectorFiniteElement::LocalInterpolation_RT(), and NodalFiniteElement::NodalLocalInterpolation().
virtual void ElementTransformation::Transform (const IntegrationRule & , DenseMatrix &) [pure virtual]
Implemented in IsoparametricTransformation.
virtual double ElementTransformation::Weight () [pure virtual]
Implemented in IsoparametricTransformation.
Referenced by DiffusionIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix(), ConvectionIntegrator::AssembleElementMatrix(), VectorMassIntegrator::AssembleElementMatrix(), CurlCurlIntegrator::AssembleElementMatrix(), VectorFEMassIntegrator::AssembleElementMatrix(), DivDivIntegrator::AssembleElementMatrix(), VectorDiffusionIntegrator::AssembleElementMatrix(), ElasticityIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix2(), DerivativeIntegrator::AssembleElementMatrix2(), VectorFEMassIntegrator::AssembleElementMatrix2(), DomainLFIntegrator::AssembleRHSElementVect(), BoundaryLFIntegrator::AssembleRHSElementVect(), VectorDomainLFIntegrator::AssembleRHSElementVect(), VectorBoundaryLFIntegrator::AssembleRHSElementVect(), VectorFEDomainLFIntegrator::AssembleRHSElementVect(), VectorFiniteElement::CalcVShape_RT(), DiffusionIntegrator::ComputeFluxEnergy(), GridFunction::ComputeH1Error(), GridFunction::ComputeL1Error(), GridFunction::ComputeL2Error(), ComputeLpNorm(), GridFunction::ComputeW11Error(), GridFunction::GetDivergence(), Mesh::GetElementVolume(), and NodalFiniteElement::ProjectDiv().
Member Data Documentation
int ElementTransformation::Attribute
Definition at line 23 of file eltrans.hpp.
Referenced by PWConstCoefficient::Eval(), RestrictedCoefficient::Eval(), VectorRestrictedCoefficient::Eval(), Mesh::GetBdrElementTransformation(), Mesh::GetBdrFaceTransformations(), Mesh::GetElementTransformation(), Mesh::GetFaceTransformation(), and Mesh::GetFineElemTrans().
int ElementTransformation::ElementNo
Definition at line 23 of file eltrans.hpp.
Referenced by GridFunctionCoefficient::Eval(), VectorGridFunctionCoefficient::Eval(), Mesh::GetBdrElementTransformation(), GridFunction::GetDivergence(), Mesh::GetElementTransformation(), Mesh::GetFaceTransformation(), Mesh::GetFineElemTrans(), and GridFunction::GetVectorGradientHat().
const IntegrationPoint* ElementTransformation::IntPoint [protected]
Definition at line 20 of file eltrans.hpp.
Referenced by GetIntPoint(), IsoparametricTransformation::Jacobian(), and SetIntPoint().
int ElementTransformation::JacobianIsEvaluated [protected]
Definition at line 18 of file eltrans.hpp.
Referenced by IsoparametricTransformation::Jacobian(), and SetIntPoint().
int ElementTransformation::WeightIsEvaluated [protected]
Definition at line 19 of file eltrans.hpp.
Referenced by SetIntPoint(), and IsoparametricTransformation::Weight().
The documentation for this class was generated from the following file:
eltrans.hpp