MFEM: VectorDomainLFIntegrator Class Reference
VectorDomainLFIntegrator Class Reference
#include <lininteg.hpp>
Public Member Functions
VectorDomainLFIntegrator (VectorCoefficient &QF)
Constructs a domain integrator with a given VectorCoefficient.
virtual void AssembleRHSElementVect (const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
Private Attributes
Vector shape
Vector Qvec
VectorCoefficient & Q
Detailed Description
Class for domain integration of L(v) := (f, v), where f=(f1,...,fn) and v=(v1,...,vn).
Definition at line 80 of file lininteg.hpp.
Constructor & Destructor Documentation
VectorDomainLFIntegrator::VectorDomainLFIntegrator (VectorCoefficient & QF) [inline]
Constructs a domain integrator with a given VectorCoefficient.
Definition at line 88 of file lininteg.hpp.
Member Function Documentation
void VectorDomainLFIntegrator::AssembleRHSElementVect (const FiniteElement & el, ElementTransformation & Tr, Vector & elvect) [virtual]
Given a particular Finite Element and a transformation (Tr) computes the element right hand side element vector, elvect.
Implements LinearFormIntegrator.
Definition at line 83 of file lininteg.cpp.
References FiniteElement::CalcShape(), VectorCoefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), VectorCoefficient::GetVDim(), IntegrationRule::IntPoint(), IntRules, Q, Qvec, ElementTransformation::SetIntPoint(), Vector::SetSize(), shape, IntegrationPoint::weight, and ElementTransformation::Weight().
Member Data Documentation
VectorCoefficient& VectorDomainLFIntegrator::Q [private]
Definition at line 84 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Vector VectorDomainLFIntegrator::Qvec [private]
Definition at line 83 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Vector VectorDomainLFIntegrator::shape [private]
Definition at line 83 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
The documentation for this class was generated from the following files:
lininteg.hpp
lininteg.cpp