MFEM: Hexahedron Class Reference
Hexahedron Class Reference
Data type hexahedron element.
#include <hexahedron.hpp>
Public Member Functions
Hexahedron ()
Hexahedron (const int *ind, int attr=1)
Constructs hexahedron by specifying the indices and the attribute.
Hexahedron (int ind1, int ind2, int ind3, int ind4, int ind5, int ind6, int ind7, int ind8, int attr=1)
Constructs hexahedron by specifying the indices and the attribute.
int GetType () const
Return element's type.
virtual void GetVertices (Array< int > &v) const
Returns the indices of the element's vertices.
virtual int * GetVertices ()
virtual int GetNVertices () const
virtual int GetNEdges () const
virtual const int * GetEdgeVertices (int ei) const
virtual Element * Duplicate (Mesh *m) const
virtual ~Hexahedron ()
Protected Attributes
int indices [8]
Static Protected Attributes
static const int edges [12][2]
Detailed Description
Data type hexahedron element.
Definition at line 16 of file hexahedron.hpp.
Constructor & Destructor Documentation
Hexahedron::Hexahedron () [inline]
Definition at line 24 of file hexahedron.hpp.
Referenced by Duplicate().
Hexahedron::Hexahedron (const int * ind, int attr = 1)
Constructs hexahedron by specifying the indices and the attribute.
Definition at line 20 of file hexahedron.cpp.
References Element::attribute, and indices.
Hexahedron::Hexahedron (int ind1, int ind2, int ind3, int ind4, int ind5, int ind6, int ind7, int ind8, int attr = 1)
Constructs hexahedron by specifying the indices and the attribute.
Definition at line 28 of file hexahedron.cpp.
References Element::attribute, and indices.
virtual Hexahedron::~Hexahedron () [inline, virtual]
Definition at line 51 of file hexahedron.hpp.
Member Function Documentation
virtual Element* Hexahedron::Duplicate (Mesh * m) const [inline, virtual]
Implements Element.
Definition at line 48 of file hexahedron.hpp.
References Element::attribute, Hexahedron(), and indices.
virtual const int* Hexahedron::GetEdgeVertices (int ei) const [inline, virtual]
Implements Element.
Definition at line 45 of file hexahedron.hpp.
References edges.
virtual int Hexahedron::GetNEdges () const [inline, virtual]
Implements Element.
Definition at line 43 of file hexahedron.hpp.
virtual int Hexahedron::GetNVertices () const [inline, virtual]
Implements Element.
Definition at line 41 of file hexahedron.hpp.
int Hexahedron::GetType () const [inline, virtual]
Return element's type.
Implements Element.
Definition at line 34 of file hexahedron.hpp.
References Element::HEXAHEDRON.
void Hexahedron::GetVertices (Array< int > & v) const [virtual]
Returns the indices of the element's vertices.
Implements Element.
Definition at line 43 of file hexahedron.cpp.
References indices, and Array< T >::SetSize().
virtual int* Hexahedron::GetVertices () [inline, virtual]
Implements Element.
Definition at line 39 of file hexahedron.hpp.
References indices.
Member Data Documentation
const int Hexahedron::edges [static, protected]
Initial value:
{{0, 1}, {1, 2}, {3, 2}, {0, 3},
 {4, 5}, {5, 6}, {7, 6}, {4, 7},
 {0, 4}, {1, 5}, {2, 6}, {3, 7}}
Definition at line 20 of file hexahedron.hpp.
Referenced by GetEdgeVertices().
int Hexahedron::indices[8] [protected]
Definition at line 19 of file hexahedron.hpp.
Referenced by Duplicate(), GetVertices(), and Hexahedron().
The documentation for this class was generated from the following files:
hexahedron.hpp
hexahedron.cpp