MFEM: socketserver Class Reference
socketserver Class Reference
#include <socketstream.hpp>
Public Member Functions
socketserver (int port)
bool good ()
int close ()
int accept (socketstream &sockstr)
~socketserver ()
Private Attributes
int listen_socket
Detailed Description
Definition at line 99 of file socketstream.hpp.
Constructor & Destructor Documentation
socketserver::socketserver (int port) [explicit]
Definition at line 185 of file socketstream.cpp.
References close(), and listen_socket.
socketserver::~socketserver () [inline]
Definition at line 113 of file socketstream.hpp.
References close().
Member Function Documentation
int socketserver::accept (socketstream & sockstr)
Definition at line 229 of file socketstream.cpp.
References socketbuf::attach(), socketbuf::close(), good(), listen_socket, and socketstream::rdbuf().
int socketserver::close ()
Definition at line 220 of file socketstream.cpp.
References good(), and listen_socket.
Referenced by socketserver(), and ~socketserver().
bool socketserver::good () [inline]
Definition at line 107 of file socketstream.hpp.
References listen_socket.
Referenced by accept(), and close().
Member Data Documentation
int socketserver::listen_socket [private]
Definition at line 102 of file socketstream.hpp.
Referenced by accept(), close(), good(), and socketserver().
The documentation for this class was generated from the following files:
socketstream.hpp
socketstream.cpp