MFEM: DivDivIntegrator Class Reference
DivDivIntegrator Class Reference
(Q div u, div v) for RT elements
#include <bilininteg.hpp>
Public Member Functions
DivDivIntegrator ()
DivDivIntegrator (Coefficient &q)
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
Private Attributes
Coefficient * Q
Vector divshape
Detailed Description
(Q div u, div v) for RT elements
Definition at line 354 of file bilininteg.hpp.
Constructor & Destructor Documentation
DivDivIntegrator::DivDivIntegrator () [inline]
Definition at line 364 of file bilininteg.hpp.
References Q.
DivDivIntegrator::DivDivIntegrator (Coefficient & q) [inline]
Definition at line 365 of file bilininteg.hpp.
Member Function Documentation
void DivDivIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 735 of file bilininteg.cpp.
References AddMult_a_VVt(), FiniteElement::CalcDivShape(), divshape, IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, Q, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), IntegrationPoint::weight, and ElementTransformation::Weight().
Member Data Documentation
Vector DivDivIntegrator::divshape [private]
Definition at line 360 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
Coefficient* DivDivIntegrator::Q [private]
Definition at line 357 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), and DivDivIntegrator().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp