MFEM: Poly_1D::Basis Class Reference
Poly_1D::Basis Class Reference
#include <fe.hpp>
Public Member Functions
Basis (const int p, const double *nodes)
void Eval (const double x, Vector &u) const
void Eval (const double x, Vector &u, Vector &d) const
Private Attributes
DenseMatrix A
Vector a
Vector b
Detailed Description
Definition at line 1158 of file fe.hpp.
Constructor & Destructor Documentation
Poly_1D::Basis::Basis (const int p, const double * nodes)
Definition at line 5576 of file fe.cpp.
References A, a, b, Poly_1D::CalcBasis(), DenseMatrix::Invert(), and Vector::SetSize().
Member Function Documentation
void Poly_1D::Basis::Eval (const double x, Vector & u) const
Definition at line 5596 of file fe.cpp.
References Poly_1D::CalcBasis(), and Vector::Size().
Referenced by ND_HexahedronElement::CalcCurlShape(), RT_QuadrilateralElement::CalcDivShape(), RT_HexahedronElement::CalcDivShape(), H1_SegmentElement::CalcDShape(), H1_QuadrilateralElement::CalcDShape(), H1_HexahedronElement::CalcDShape(), L2_SegmentElement::CalcDShape(), L2_QuadrilateralElement::CalcDShape(), L2_HexahedronElement::CalcDShape(), H1_SegmentElement::CalcShape(), H1_QuadrilateralElement::CalcShape(), H1_HexahedronElement::CalcShape(), L2_SegmentElement::CalcShape(), L2_QuadrilateralElement::CalcShape(), L2_HexahedronElement::CalcShape(), RT_QuadrilateralElement::CalcVShape(), RT_HexahedronElement::CalcVShape(), ND_HexahedronElement::CalcVShape(), and ND_QuadrilateralElement::CalcVShape().
void Poly_1D::Basis::Eval (const double x, Vector & u, Vector & d) const
Definition at line 5606 of file fe.cpp.
References Poly_1D::CalcBasis(), and Vector::Size().
Member Data Documentation
DenseMatrix Poly_1D::Basis::A [private]
Definition at line 1161 of file fe.hpp.
Referenced by Basis().
Vector Poly_1D::Basis::a [mutable, private]
Definition at line 1163 of file fe.hpp.
Referenced by Basis().
Vector Poly_1D::Basis::b [mutable, private]
Definition at line 1163 of file fe.hpp.
Referenced by Basis().
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp