MFEM: STable3D Class Reference
STable3D Class Reference
Symmetric 3D Table.
#include <stable3d.hpp>
Public Member Functions
STable3D (int nr)
int Push (int r, int c, int f)
int operator() (int r, int c, int f) const
int Index (int r, int c, int f) const
int Push4 (int r, int c, int f, int t)
int operator() (int r, int c, int f, int t) const
int NumberOfElements ()
~STable3D ()
Private Attributes
int Size
int NElem
STable3DNode ** Rows
Detailed Description
Symmetric 3D Table.
Definition at line 25 of file stable3d.hpp.
Constructor & Destructor Documentation
STable3D::STable3D (int nr) [explicit]
Definition at line 18 of file stable3d.cpp.
STable3D::~STable3D ()
Definition at line 189 of file stable3d.cpp.
References STable3DNode::Prev.
Member Function Documentation
int STable3D::Index (int r, int c, int f) const
Definition at line 118 of file stable3d.cpp.
References STable3DNode::Column, STable3DNode::Floor, STable3DNode::Number, STable3DNode::Prev, and Sort3().
int STable3D::NumberOfElements () [inline]
Definition at line 48 of file stable3d.hpp.
References NElem.
Referenced by Mesh::GetElementToFaceTable().
int STable3D::operator() (int r, int c, int f) const
Definition at line 98 of file stable3d.cpp.
References STable3DNode::Column, STable3DNode::Floor, mfem_error(), STable3DNode::Number, STable3DNode::Prev, and Sort3().
int STable3D::operator() (int r, int c, int f, int t) const
Definition at line 166 of file stable3d.cpp.
int STable3D::Push (int r, int c, int f)
Definition at line 61 of file stable3d.cpp.
References STable3DNode::Column, STable3DNode::Floor, mfem_error(), STable3DNode::Number, STable3DNode::Prev, and Sort3().
Referenced by Mesh::GetElementToFaceTable(), and Mesh::GetFacesTable().
int STable3D::Push4 (int r, int c, int f, int t)
Definition at line 134 of file stable3d.cpp.
References mfem_error().
Referenced by Mesh::GetElementToFaceTable(), and Mesh::GetFacesTable().
Member Data Documentation
int STable3D::NElem [private]
Definition at line 28 of file stable3d.hpp.
Referenced by NumberOfElements().
STable3DNode** STable3D::Rows [private]
Definition at line 29 of file stable3d.hpp.
int STable3D::Size [private]
Definition at line 28 of file stable3d.hpp.
The documentation for this class was generated from the following files:
stable3d.hpp
stable3d.cpp