MFEM: Operator Class Reference
Operator Class Reference
Abstract operator.
#include <operator.hpp>
Public Member Functions
Operator (int s=0)
Construct Operator with given size s (default 0)
int Size () const
Returns the size of the input.
virtual void Mult (const Vector &x, Vector &y) const =0
Operator application.
virtual void MultTranspose (const Vector &x, Vector &y) const
Action of the transpose operator.
void PrintMatlab (ostream &out, int n=0, int m=0)
Prints operator with input size n and output size m in matlab format.
virtual ~Operator ()
Protected Attributes
int size
Detailed Description
Abstract operator.
Definition at line 18 of file operator.hpp.
Constructor & Destructor Documentation
Operator::Operator (int s = 0) [inline, explicit]
Construct Operator with given size s (default 0)
Definition at line 25 of file operator.hpp.
References size.
virtual Operator::~Operator () [inline, virtual]
Definition at line 40 of file operator.hpp.
Member Function Documentation
virtual void Operator::Mult (const Vector & x, Vector & y) const [pure virtual]
Operator application.
Implemented in DenseMatrixInverse, HypreSolver, MixedBilinearForm, HypreParMatrix, SparseMatrix, DenseMatrix, BilinearForm, TransposeOperator, IdentityOperator, DSmoother, and GSSmoother.
Referenced by aGMRES(), BiCGSTAB(), CG(), GMRES(), PCG(), PrintMatlab(), and SLI().
virtual void Operator::MultTranspose (const Vector & x, Vector & y) const [inline, virtual]
Action of the transpose operator.
Reimplemented in MixedBilinearForm, HypreParMatrix, SparseMatrix, DenseMatrix, and TransposeOperator.
Definition at line 34 of file operator.hpp.
References mfem_error().
void Operator::PrintMatlab (ostream & out, int n = 0, int m = 0)
Prints operator with input size n and output size m in matlab format.
Definition at line 18 of file operator.cpp.
References Mult(), and size.
int Operator::Size () const [inline]
Returns the size of the input.
Definition at line 28 of file operator.hpp.
References size.
Referenced by DenseMatrix::Add(), Add(), aGMRES(), BiCGSTAB(), CalcAdjugate(), CalcAdjugateTranspose(), CalcInverseTranspose(), DenseMatrix::CopyMN(), DenseMatrix::CopyMNt(), DenseMatrix::CopyRows(), DenseMatrixEigensystem::DenseMatrixEigensystem(), DetOfLinComb(), dsyev_Eigensystem(), dsyevr_Eigensystem(), DenseMatrixEigensystem::Eval(), DenseMatrix::FNorm(), GridFunction::GetDivergence(), GridFunction::GetVectorGradient(), GMRES(), DenseMatrix::Invert(), Mult(), MultAAt(), MultAtB(), MultVWt(), DenseMatrix::Neg(), DenseMatrix::Norm2(), DenseMatrix::operator*=(), DenseMatrix::operator=(), DenseMatrix::SetSize(), DenseMatrix::Transpose(), Transpose(), and TransposeOperator::TransposeOperator().
Member Data Documentation
int Operator::size [protected]
Definition at line 21 of file operator.hpp.
Referenced by SparseMatrix::Add(), DenseMatrix::AddMult(), SparseMatrix::AddMult(), SparseMatrix::AddMultTranspose(), SparseMatrix::AddRow(), SparseMatrix::AddSubMatrix(), DenseMatrix::AddToVector(), BilinearForm::Assemble(), MixedBilinearForm::Assemble(), DiscreteLinearOperator::Assemble(), BilinearForm::AssembleElementMatrix(), BilinearForm::BilinearForm(), DenseMatrix::ClearExternalData(), SparseMatrix::CountSmallElems(), DenseMatrix::DenseMatrix(), DenseMatrixInverse::DenseMatrixInverse(), SparseMatrix::EliminateCol(), SparseMatrix::EliminateCols(), SparseMatrix::EliminateRow(), SparseMatrix::EliminateRowCol(), SparseMatrix::EliminateRowColMultipleRHS(), BilinearForm::EliminateVDofs(), SparseMatrix::EliminateZeroRows(), DenseMatrixInverse::Factor(), SparseMatrix::Finalize(), SparseMatrix::Gauss_Seidel_back(), SparseMatrix::Gauss_Seidel_forw(), SparseMatrix::GetBlocks(), DenseMatrix::GetFromVector(), SparseMatrix::GetJacobiScaling(), SparseMatrix::GetRowSums(), SparseMatrix::GetSubMatrix(), DenseMatrix::GradToDiv(), IdentityOperator::IdentityOperator(), DenseMatrix::InnerProduct(), SparseMatrix::InnerProduct(), DenseMatrix::Invert(), SparseMatrix::IsSymmetric(), SparseMatrix::Jacobi(), SparseMatrix::Jacobi2(), Matrix::Matrix(), MatrixInverse::MatrixInverse(), SparseMatrix::MaxNorm(), DenseMatrix::Mult(), Mult(), DenseMatrixInverse::Mult(), DenseMatrix::MultTranspose(), SparseMatrix::NumNonZeroElems(), Operator(), DenseMatrix::operator()(), SparseMatrix::operator()(), DenseMatrix::operator*(), DenseMatrix::operator+=(), SparseMatrix::operator+=(), DenseMatrix::operator-=(), DenseMatrix::operator=(), SparseMatrix::operator=(), Matrix::Print(), SparseMatrix::Print(), DenseMatrix::Print(), SparseMatrix::PrintCSR(), SparseMatrix::PrintCSR2(), PrintMatlab(), SparseMatrix::PrintMatlab(), SparseMatrix::PrintMM(), DenseMatrix::PrintT(), SparseMatrix::Set(), SparseMatrix::SetDiagIdentity(), DenseMatrix::SetSize(), SparseMatrix::SetSubMatrix(), SparseMatrix::SetSubMatrixTranspose(), Size(), SparseMatrix::Symmetrize(), DenseMatrix::TestInversion(), DenseMatrix::Trace(), TransposeOperator::TransposeOperator(), BilinearForm::Update(), MixedBilinearForm::Update(), DenseMatrix::UseExternalData(), DenseMatrix::Width(), and SparseMatrix::~SparseMatrix().
The documentation for this class was generated from the following files:
operator.hpp
operator.cpp