MFEM: ParBilinearForm Class Reference
ParBilinearForm Class Reference
Class for parallel bilinear form.
#include <pbilinearform.hpp>
Public Member Functions
ParBilinearForm (ParFiniteElementSpace *pf)
ParBilinearForm (ParFiniteElementSpace *pf, ParBilinearForm *bf)
HypreParMatrix * ParallelAssemble ()
Returns the matrix assembled on the true dofs, i.e. P^t A P.
HypreParMatrix * ParallelAssembleElim ()
Returns the eliminated matrix assembled on the true dofs, i.e. P^t A_e P.
virtual ~ParBilinearForm ()
Protected Member Functions
HypreParMatrix * ParallelAssemble (SparseMatrix *m)
Protected Attributes
ParFiniteElementSpace * pfes
Detailed Description
Class for parallel bilinear form.
Definition at line 16 of file pbilinearform.hpp.
Constructor & Destructor Documentation
ParBilinearForm::ParBilinearForm (ParFiniteElementSpace * pf) [inline]
Definition at line 24 of file pbilinearform.hpp.
References pfes.
ParBilinearForm::ParBilinearForm (ParFiniteElementSpace * pf, ParBilinearForm * bf) [inline]
Definition at line 27 of file pbilinearform.hpp.
References pfes.
virtual ParBilinearForm::~ParBilinearForm () [inline, virtual]
Definition at line 36 of file pbilinearform.hpp.
Member Function Documentation
HypreParMatrix* ParBilinearForm::ParallelAssemble (SparseMatrix * m) [protected]
Referenced by main().
HypreParMatrix* ParBilinearForm::ParallelAssemble () [inline]
Returns the matrix assembled on the true dofs, i.e. P^t A P.
Definition at line 31 of file pbilinearform.hpp.
References BilinearForm::mat, and ParallelAssemble().
Referenced by ParallelAssemble(), and ParallelAssembleElim().
HypreParMatrix* ParBilinearForm::ParallelAssembleElim () [inline]
Returns the eliminated matrix assembled on the true dofs, i.e. P^t A_e P.
Definition at line 34 of file pbilinearform.hpp.
References BilinearForm::mat_e, and ParallelAssemble().
Member Data Documentation
ParFiniteElementSpace* ParBilinearForm::pfes [protected]
Definition at line 19 of file pbilinearform.hpp.
Referenced by ParBilinearForm().
The documentation for this class was generated from the following file:
pbilinearform.hpp