MFEM: DenseMatrixEigensystem Class Reference
DenseMatrixEigensystem Class Reference
#include <densemat.hpp>
Public Member Functions
DenseMatrixEigensystem (DenseMatrix &m)
void Eval ()
double Eigenvalue (int i)
const Vector & Eigenvector (int i)
~DenseMatrixEigensystem ()
Private Attributes
DenseMatrix & mat
Vector EVal
DenseMatrix EVect
Vector ev
double * work
char jobz
char uplo
int n
int lwork
int info
Detailed Description
Definition at line 316 of file densemat.hpp.
Constructor & Destructor Documentation
DenseMatrixEigensystem::DenseMatrixEigensystem (DenseMatrix & m)
Definition at line 2447 of file densemat.cpp.
References DenseMatrix::Data(), ev, EVal, EVect, Vector::GetData(), info, jobz, lwork, n, Vector::SetDataAndSize(), Vector::SetSize(), DenseMatrix::SetSize(), Operator::Size(), uplo, and work.
DenseMatrixEigensystem::~DenseMatrixEigensystem ()
Definition at line 2491 of file densemat.cpp.
References work.
Member Function Documentation
double DenseMatrixEigensystem::Eigenvalue (int i) [inline]
Definition at line 333 of file densemat.hpp.
References EVal.
const Vector& DenseMatrixEigensystem::Eigenvector (int i) [inline]
Definition at line 334 of file densemat.hpp.
References DenseMatrix::Data(), ev, EVect, DenseMatrix::Height(), and Vector::SetData().
void DenseMatrixEigensystem::Eval ()
Definition at line 2468 of file densemat.cpp.
References DenseMatrix::Data(), EVal, EVect, Vector::GetData(), info, jobz, lwork, mat, mfem_error(), n, Operator::Size(), uplo, and work.
Member Data Documentation
Vector DenseMatrixEigensystem::ev [private]
Definition at line 323 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), and Eigenvector().
Vector DenseMatrixEigensystem::EVal [private]
Definition at line 320 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), Eigenvalue(), and Eval().
DenseMatrix DenseMatrixEigensystem::EVect [private]
Definition at line 321 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), Eigenvector(), and Eval().
int DenseMatrixEigensystem::info [private]
Definition at line 327 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), and Eval().
char DenseMatrixEigensystem::jobz [private]
Definition at line 326 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), and Eval().
int DenseMatrixEigensystem::lwork [private]
Definition at line 327 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), and Eval().
DenseMatrix& DenseMatrixEigensystem::mat [private]
Definition at line 318 of file densemat.hpp.
Referenced by Eval().
int DenseMatrixEigensystem::n [private]
Definition at line 327 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), and Eval().
char DenseMatrixEigensystem::uplo [private]
Definition at line 326 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), and Eval().
double* DenseMatrixEigensystem::work [private]
Definition at line 325 of file densemat.hpp.
Referenced by DenseMatrixEigensystem(), Eval(), and ~DenseMatrixEigensystem().
The documentation for this class was generated from the following files:
densemat.hpp
densemat.cpp