MFEM: intrules.cpp File Reference
intrules.cpp File Reference
#include <math.h>
#include "fem.hpp"
Variables
IntegrationRules IntRules (0)
A global object with all integration rules (defined in intrules.cpp)
IntegrationRules RefinedIntRules (1)
A global object with all refined integration rules.
Variable Documentation
IntegrationRules IntRules(0)
A global object with all integration rules (defined in intrules.cpp)
Referenced by DiffusionIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix(), ConvectionIntegrator::AssembleElementMatrix(), VectorMassIntegrator::AssembleElementMatrix(), CurlCurlIntegrator::AssembleElementMatrix(), VectorFEMassIntegrator::AssembleElementMatrix(), DivDivIntegrator::AssembleElementMatrix(), VectorDiffusionIntegrator::AssembleElementMatrix(), ElasticityIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix2(), VectorFEDivergenceIntegrator::AssembleElementMatrix2(), VectorFECurlIntegrator::AssembleElementMatrix2(), DerivativeIntegrator::AssembleElementMatrix2(), VectorFEMassIntegrator::AssembleElementMatrix2(), VectorDivergenceIntegrator::AssembleElementMatrix2(), DomainLFIntegrator::AssembleRHSElementVect(), BoundaryLFIntegrator::AssembleRHSElementVect(), VectorDomainLFIntegrator::AssembleRHSElementVect(), VectorBoundaryLFIntegrator::AssembleRHSElementVect(), VectorFEDomainLFIntegrator::AssembleRHSElementVect(), VectorBoundaryFluxLFIntegrator::AssembleRHSElementVect(), VectorFEBoundaryFluxLFIntegrator::AssembleRHSElementVect(), DiffusionIntegrator::ComputeFluxEnergy(), GridFunction::ComputeH1Error(), GridFunction::ComputeL1Error(), GridFunction::ComputeL2Error(), GridFunction::ComputeMaxError(), GridFunction::ComputeW11Error(), Mesh::GetElementVolume(), and GridFunction::ProjectBdrCoefficientNormal().
IntegrationRules RefinedIntRules(1)
A global object with all refined integration rules.
Referenced by DiffusionIntegrator::AssembleElementMatrix(), MassIntegrator::AssembleElementMatrix(), VectorMassIntegrator::AssembleElementMatrix(), VectorDiffusionIntegrator::AssembleElementMatrix(), and DerivativeIntegrator::AssembleElementMatrix2().