MFEM: nurbs.cpp File Reference
nurbs.cpp File Reference
#include "../fem/fem.hpp"
Functions
NURBSPatch * Interpolate (NURBSPatch &p1, NURBSPatch &p2)
NURBSPatch * Revolve3D (NURBSPatch &patch, double n[], double ang, int times)
void skip_comment_lines (istream &, const char)
Function Documentation
NURBSPatch* Interpolate (NURBSPatch & p1, NURBSPatch & p2)
Definition at line 935 of file nurbs.cpp.
References NURBSPatch::data, NURBSPatch::Dim, KnotVector::GetElements(), NURBSPatch::KnotInsert(), NURBSPatch::kv, Array< T >::Last(), mfem_error(), and Array< T >::Size().
NURBSPatch* Revolve3D (NURBSPatch & patch, double n[], double ang, int times)
Definition at line 980 of file nurbs.cpp.
References NURBSPatch::data, NURBSPatch::Dim, NURBSPatch::Get3DRotationMatrix(), KnotVector::GetElements(), NURBSPatch::kv, Array< T >::Last(), mfem_error(), DenseMatrix::Mult, Vector::SetData(), and Array< T >::Size().
void skip_comment_lines (istream & , const char)
Definition at line 1109 of file mesh.cpp.
Referenced by Mesh::Load(), Mesh::LoadPatchTopo(), and NURBSExtension::NURBSExtension().