MFEM: stable3d.cpp File Reference
stable3d.cpp File Reference
#include "error.hpp"
#include "stable3d.hpp"
Functions
void Sort3 (int &r, int &c, int &f)
Function Documentation
void Sort3 (int & r, int & c, int & f) [inline]
Definition at line 29 of file stable3d.cpp.
Referenced by STable3D::Index(), STable3D::operator()(), and STable3D::Push().