MFEM: Matrix Class Reference
Matrix Class Reference
Abstract data type matrix.
#include <matrix.hpp>
Public Member Functions
Matrix (int s)
Creates matrix of width s.
virtual double & Elem (int i, int j)=0
Returns reference to a_{ij}. Index i, j = 0 .. size-1.
virtual const double & Elem (int i, int j) const =0
Returns constant reference to a_{ij}. Index i, j = 0 .. size-1.
virtual MatrixInverse * Inverse () const =0
Returns a pointer to (approximation) of the matrix inverse.
virtual void Finalize (int)
Finalizes the matrix initialization.
virtual void Print (ostream &out=cout, int width=4) const
Prints matrix to stream out.
virtual ~Matrix ()
Destroys matrix.
Friends
class MatrixInverse
Detailed Description
Abstract data type matrix.
Definition at line 23 of file matrix.hpp.
Constructor & Destructor Documentation
Matrix::Matrix (int s) [inline]
Creates matrix of width s.
Definition at line 28 of file matrix.hpp.
References Operator::size.
virtual Matrix::~Matrix () [inline, virtual]
Destroys matrix.
Definition at line 46 of file matrix.hpp.
Member Function Documentation
virtual double& Matrix::Elem (int i, int j) [pure virtual]
Returns reference to a_{ij}. Index i, j = 0 .. size-1.
Implemented in BilinearForm, MixedBilinearForm, DenseMatrix, and SparseMatrix.
Referenced by DSmoother::Mult(), and Print().
virtual const double& Matrix::Elem (int i, int j) const [pure virtual]
Returns constant reference to a_{ij}. Index i, j = 0 .. size-1.
Implemented in BilinearForm, MixedBilinearForm, DenseMatrix, and SparseMatrix.
virtual void Matrix::Finalize (int) [inline, virtual]
Finalizes the matrix initialization.
Reimplemented in BilinearForm, MixedBilinearForm, and SparseMatrix.
Definition at line 40 of file matrix.hpp.
virtual MatrixInverse* Matrix::Inverse () const [pure virtual]
Returns a pointer to (approximation) of the matrix inverse.
Implemented in BilinearForm, MixedBilinearForm, DenseMatrix, and SparseMatrix.
void Matrix::Print (ostream & out = cout, int width = 4) const [virtual]
Prints matrix to stream out.
Reimplemented in DenseMatrix, and SparseMatrix.
Definition at line 19 of file matrix.cpp.
References Elem(), and Operator::size.
Friends And Related Function Documentation
friend class MatrixInverse [friend]
Definition at line 25 of file matrix.hpp.
The documentation for this class was generated from the following files:
matrix.hpp
matrix.cpp