MFEM: IntegrationPointTransformation Class Reference
IntegrationPointTransformation Class Reference
#include <eltrans.hpp>
Public Member Functions
void Transform (const IntegrationPoint &, IntegrationPoint &)
void Transform (const IntegrationRule &, IntegrationRule &)
Public Attributes
IsoparametricTransformation Transf
Detailed Description
Definition at line 68 of file eltrans.hpp.
Member Function Documentation
void IntegrationPointTransformation::Transform (const IntegrationPoint & ip1, IntegrationPoint & ip2)
Definition at line 123 of file eltrans.cpp.
References IsoparametricTransformation::GetPointMat(), DenseMatrix::Height(), Transf, IsoparametricTransformation::Transform(), IntegrationPoint::x, IntegrationPoint::y, and IntegrationPoint::z.
Referenced by GridFunction::ComputeH1Error(), GridFunction::GetFaceValues(), GridFunction::GetFaceVectorValues(), and Transform().
void IntegrationPointTransformation::Transform (const IntegrationRule & ir1, IntegrationRule & ir2)
Definition at line 135 of file eltrans.cpp.
References IntegrationRule::GetNPoints(), IntegrationRule::IntPoint(), and Transform().
Member Data Documentation
IsoparametricTransformation IntegrationPointTransformation::Transf
Definition at line 71 of file eltrans.hpp.
Referenced by Mesh::GetFaceElementTransformations(), and Transform().
The documentation for this class was generated from the following files:
eltrans.hpp
eltrans.cpp