MFEM: Poly_1D Class Reference
Poly_1D Class Reference
#include <fe.hpp>
Classes
class Basis
Public Member Functions
Poly_1D ()
const double * OpenPoints (const int p)
const double * ClosedPoints (const int p)
Basis & OpenBasis (const int p)
Basis & ClosedBasis (const int p)
~Poly_1D ()
Static Public Member Functions
static void CalcBasis (const int p, const double x, double *u)
static void CalcBasis (const int p, const double x, double *u, double *d)
static double CalcDelta (const int p, const double x)
Static Private Member Functions
static void UniformPoints (const int p, double *x)
static void GaussPoints (const int p, double *x)
static void GaussLobattoPoints (const int p, double *x)
static void ChebyshevPoints (const int p, double *x)
static void CalcMono (const int p, const double x, double *u)
static void CalcMono (const int p, const double x, double *u, double *d)
static void CalcBernstein (const int p, const double x, double *u)
static void CalcBernstein (const int p, const double x, double *u, double *d)
static void CalcLegendre (const int p, const double x, double *u)
static void CalcLegendre (const int p, const double x, double *u, double *d)
static void CalcChebyshev (const int p, const double x, double *u)
static void CalcChebyshev (const int p, const double x, double *u, double *d)
Private Attributes
Array< double * > open_pts
Array< double * > closed_pts
Array< Basis * > open_basis
Array< Basis * > closed_basis
Detailed Description
Definition at line 1155 of file fe.hpp.
Constructor & Destructor Documentation
Poly_1D::Poly_1D () [inline]
Definition at line 1194 of file fe.hpp.
Poly_1D::~Poly_1D ()
Definition at line 5973 of file fe.cpp.
References closed_basis, closed_pts, open_basis, open_pts, and Array< T >::Size().
Member Function Documentation
static void Poly_1D::CalcBasis (const int p, const double x, double * u) [inline, static]
Definition at line 1204 of file fe.hpp.
References CalcChebyshev().
Referenced by Poly_1D::Basis::Basis(), ND_TetrahedronElement::CalcCurlShape(), RT_TriangleElement::CalcDivShape(), RT_TetrahedronElement::CalcDivShape(), H1_TriangleElement::CalcDShape(), H1_TetrahedronElement::CalcDShape(), L2_TriangleElement::CalcDShape(), L2_TetrahedronElement::CalcDShape(), H1_TriangleElement::CalcShape(), H1_TetrahedronElement::CalcShape(), L2_TriangleElement::CalcShape(), L2_TetrahedronElement::CalcShape(), RT_TriangleElement::CalcVShape(), RT_TetrahedronElement::CalcVShape(), ND_TetrahedronElement::CalcVShape(), ND_TriangleElement::CalcVShape(), Poly_1D::Basis::Eval(), H1_TetrahedronElement::H1_TetrahedronElement(), H1_TriangleElement::H1_TriangleElement(), L2_TetrahedronElement::L2_TetrahedronElement(), L2_TriangleElement::L2_TriangleElement(), ND_TetrahedronElement::ND_TetrahedronElement(), ND_TriangleElement::ND_TriangleElement(), RT_TetrahedronElement::RT_TetrahedronElement(), and RT_TriangleElement::RT_TriangleElement().
static void Poly_1D::CalcBasis (const int p, const double x, double * u, double * d) [inline, static]
Definition at line 1213 of file fe.hpp.
References CalcChebyshev().
void Poly_1D::CalcBernstein (const int p, const double x, double * u) [static, private]
Definition at line 5790 of file fe.cpp.
void Poly_1D::CalcBernstein (const int p, const double x, double * u, double * d) [static, private]
Definition at line 5803 of file fe.cpp.
void Poly_1D::CalcChebyshev (const int p, const double x, double * u) [static, private]
Definition at line 5855 of file fe.cpp.
Referenced by CalcBasis().
void Poly_1D::CalcChebyshev (const int p, const double x, double * u, double * d) [static, private]
Definition at line 5870 of file fe.cpp.
static double Poly_1D::CalcDelta (const int p, const double x) [inline, static]
Definition at line 1220 of file fe.hpp.
Referenced by L2_SegmentElement::ProjectDelta(), L2_QuadrilateralElement::ProjectDelta(), and L2_HexahedronElement::ProjectDelta().
void Poly_1D::CalcLegendre (const int p, const double x, double * u) [static, private]
Definition at line 5822 of file fe.cpp.
void Poly_1D::CalcLegendre (const int p, const double x, double * u, double * d) [static, private]
Definition at line 5836 of file fe.cpp.
void Poly_1D::CalcMono (const int p, const double x, double * u) [static, private]
Definition at line 5770 of file fe.cpp.
void Poly_1D::CalcMono (const int p, const double x, double * u, double * d) [static, private]
Definition at line 5778 of file fe.cpp.
void Poly_1D::ChebyshevPoints (const int p, double * x) [static, private]
Definition at line 5760 of file fe.cpp.
Poly_1D::Basis & Poly_1D::ClosedBasis (const int p)
Definition at line 5954 of file fe.cpp.
References closed_basis, ClosedPoints(), Array< T >::SetSize(), and Array< T >::Size().
const double * Poly_1D::ClosedPoints (const int p)
Definition at line 5914 of file fe.cpp.
References closed_pts, GaussLobattoPoints(), Array< T >::SetSize(), and Array< T >::Size().
Referenced by ClosedBasis(), H1_HexahedronElement::H1_HexahedronElement(), H1_QuadrilateralElement::H1_QuadrilateralElement(), H1_SegmentElement::H1_SegmentElement(), H1_TetrahedronElement::H1_TetrahedronElement(), H1_TriangleElement::H1_TriangleElement(), ND_HexahedronElement::ND_HexahedronElement(), ND_QuadrilateralElement::ND_QuadrilateralElement(), GeometryRefiner::Refine(), RT_HexahedronElement::RT_HexahedronElement(), and RT_QuadrilateralElement::RT_QuadrilateralElement().
void Poly_1D::GaussLobattoPoints (const int p, double * x) [static, private]
Definition at line 5686 of file fe.cpp.
Referenced by ClosedPoints().
void Poly_1D::GaussPoints (const int p, double * x) [static, private]
Definition at line 5630 of file fe.cpp.
Referenced by OpenPoints().
Poly_1D::Basis & Poly_1D::OpenBasis (const int p)
Definition at line 5935 of file fe.cpp.
References open_basis, OpenPoints(), Array< T >::SetSize(), and Array< T >::Size().
const double * Poly_1D::OpenPoints (const int p)
Definition at line 5893 of file fe.cpp.
References GaussPoints(), open_pts, Array< T >::SetSize(), and Array< T >::Size().
Referenced by L2_HexahedronElement::L2_HexahedronElement(), L2_QuadrilateralElement::L2_QuadrilateralElement(), L2_SegmentElement::L2_SegmentElement(), L2_TetrahedronElement::L2_TetrahedronElement(), L2_TriangleElement::L2_TriangleElement(), ND_HexahedronElement::ND_HexahedronElement(), ND_QuadrilateralElement::ND_QuadrilateralElement(), ND_TetrahedronElement::ND_TetrahedronElement(), ND_TriangleElement::ND_TriangleElement(), OpenBasis(), L2_SegmentElement::ProjectDelta(), L2_QuadrilateralElement::ProjectDelta(), L2_HexahedronElement::ProjectDelta(), RT_HexahedronElement::RT_HexahedronElement(), RT_QuadrilateralElement::RT_QuadrilateralElement(), RT_TetrahedronElement::RT_TetrahedronElement(), and RT_TriangleElement::RT_TriangleElement().
void Poly_1D::UniformPoints (const int p, double * x) [static, private]
Definition at line 5617 of file fe.cpp.
Member Data Documentation
Array<Basis *> Poly_1D::closed_basis [private]
Definition at line 1174 of file fe.hpp.
Referenced by ClosedBasis(), and ~Poly_1D().
Array<double *> Poly_1D::closed_pts [private]
Definition at line 1173 of file fe.hpp.
Referenced by ClosedPoints(), and ~Poly_1D().
Array<Basis *> Poly_1D::open_basis [private]
Definition at line 1174 of file fe.hpp.
Referenced by OpenBasis(), and ~Poly_1D().
Array<double *> Poly_1D::open_pts [private]
Definition at line 1173 of file fe.hpp.
Referenced by OpenPoints(), and ~Poly_1D().
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp