MFEM: VectorFunctionCoefficient Class Reference
VectorFunctionCoefficient Class Reference
#include <coefficient.hpp>
Public Member Functions
VectorFunctionCoefficient (int dim, void(*F)(const Vector &, Vector &), Coefficient *q=NULL)
virtual void Eval (Vector &V, ElementTransformation &T, const IntegrationPoint &ip)
virtual ~VectorFunctionCoefficient ()
Private Attributes
void(* Function)(const Vector &, Vector &)
Coefficient * Q
Vector transip
Detailed Description
Definition at line 199 of file coefficient.hpp.
Constructor & Destructor Documentation
VectorFunctionCoefficient::VectorFunctionCoefficient (int dim, void(*)(const Vector &, Vector &) F, Coefficient * q = NULL) [inline]
Definition at line 207 of file coefficient.hpp.
References Function.
virtual VectorFunctionCoefficient::~VectorFunctionCoefficient () [inline, virtual]
Definition at line 214 of file coefficient.hpp.
Member Function Documentation
void VectorFunctionCoefficient::Eval (Vector & V, ElementTransformation & T, const IntegrationPoint & ip) [virtual]
Implements VectorCoefficient.
Definition at line 63 of file coefficient.cpp.
References Q, Vector::SetSize(), ElementTransformation::Transform(), transip, and VectorCoefficient::vdim.
Member Data Documentation
void(* VectorFunctionCoefficient::Function)(const Vector &, Vector &) [private]
Definition at line 202 of file coefficient.hpp.
Referenced by VectorFunctionCoefficient().
Coefficient* VectorFunctionCoefficient::Q [private]
Definition at line 203 of file coefficient.hpp.
Referenced by Eval().
Vector VectorFunctionCoefficient::transip [private]
Definition at line 204 of file coefficient.hpp.
Referenced by Eval().
The documentation for this class was generated from the following files:
coefficient.hpp
coefficient.cpp