MFEM: ListOfIntegerSets Class Reference
ListOfIntegerSets Class Reference
List of integer sets.
#include <sets.hpp>
Public Member Functions
int Size ()
int PickElementInSet (int i)
int PickRandomElementInSet (int i)
int Insert (IntegerSet &s)
int Lookup (IntegerSet &s)
void AsTable (Table &t)
~ListOfIntegerSets ()
Private Attributes
Array< IntegerSet * > TheList
Detailed Description
List of integer sets.
Definition at line 42 of file sets.hpp.
Constructor & Destructor Documentation
ListOfIntegerSets::~ListOfIntegerSets ()
Definition at line 110 of file sets.cpp.
References Array< T >::Size(), and TheList.
Member Function Documentation
void ListOfIntegerSets::AsTable (Table & t)
Definition at line 90 of file sets.cpp.
References Table::AddColumnsInRow(), Table::AddConnections(), Array< T >::GetData(), Table::MakeI(), Table::MakeJ(), Table::ShiftUpI(), Array< T >::Size(), Size(), and TheList.
int ListOfIntegerSets::Insert (IntegerSet & s)
Definition at line 69 of file sets.cpp.
References Array< T >::Append(), Array< T >::Size(), and TheList.
int ListOfIntegerSets::Lookup (IntegerSet & s)
Definition at line 80 of file sets.cpp.
References mfem_error(), Array< T >::Size(), and TheList.
int ListOfIntegerSets::PickElementInSet (int i) [inline]
Definition at line 51 of file sets.hpp.
References TheList.
int ListOfIntegerSets::PickRandomElementInSet (int i) [inline]
Definition at line 53 of file sets.hpp.
References TheList.
int ListOfIntegerSets::Size () [inline]
Definition at line 49 of file sets.hpp.
References Array< T >::Size(), and TheList.
Referenced by AsTable().
Member Data Documentation
Array<IntegerSet *> ListOfIntegerSets::TheList [private]
Definition at line 45 of file sets.hpp.
Referenced by AsTable(), Insert(), Lookup(), PickElementInSet(), PickRandomElementInSet(), Size(), and ~ListOfIntegerSets().
The documentation for this class was generated from the following files:
sets.hpp
sets.cpp