MFEM: socketstream Class Reference
socketstream Class Reference
#include <socketstream.hpp>
Public Member Functions
socketstream ()
socketstream (int s)
socketstream (const char hostname[], int port)
socketbuf * rdbuf ()
int open (const char hostname[], int port)
int close ()
bool is_open ()
virtual ~socketstream ()
Private Attributes
socketbuf __buf
Detailed Description
Definition at line 71 of file socketstream.hpp.
Constructor & Destructor Documentation
socketstream::socketstream () [inline]
Definition at line 77 of file socketstream.hpp.
socketstream::socketstream (int s) [inline, explicit]
Definition at line 79 of file socketstream.hpp.
socketstream::socketstream (const char hostname[], int port) [inline]
Definition at line 81 of file socketstream.hpp.
virtual socketstream::~socketstream () [inline, virtual]
Definition at line 95 of file socketstream.hpp.
Member Function Documentation
int socketstream::close () [inline]
Definition at line 91 of file socketstream.hpp.
References __buf, and socketbuf::close().
bool socketstream::is_open () [inline]
Definition at line 93 of file socketstream.hpp.
References __buf, and socketbuf::is_open().
Referenced by osockstream::osockstream().
int socketstream::open (const char hostname[], int port) [inline]
Definition at line 86 of file socketstream.hpp.
References __buf, and socketbuf::open().
socketbuf* socketstream::rdbuf () [inline]
Definition at line 84 of file socketstream.hpp.
References __buf.
Referenced by socketserver::accept().
Member Data Documentation
socketbuf socketstream::__buf [private]
Definition at line 74 of file socketstream.hpp.
Referenced by close(), is_open(), open(), and rdbuf().
The documentation for this class was generated from the following file:
socketstream.hpp