MFEM: RT2QuadFiniteElement Class Reference
RT2QuadFiniteElement Class Reference
#include <fe.hpp>
Public Member Functions
RT2QuadFiniteElement ()
virtual void CalcVShape (const IntegrationPoint &ip, DenseMatrix &shape) const
virtual void CalcVShape (ElementTransformation &Trans, DenseMatrix &shape) const
virtual void CalcDivShape (const IntegrationPoint &ip, Vector &divshape) const
virtual void GetLocalInterpolation (ElementTransformation &Trans, DenseMatrix &I) const
virtual void Project (VectorCoefficient &vc, ElementTransformation &Trans, Vector &dofs) const
Static Private Attributes
static const double nk [24][2]
static const double pt [4] = {0.,1./3.,2./3.,1.}
static const double dpt [3] = {0.25,0.5,0.75}
Detailed Description
Definition at line 808 of file fe.hpp.
Constructor & Destructor Documentation
RT2QuadFiniteElement::RT2QuadFiniteElement ()
Definition at line 2852 of file fe.cpp.
References dpt, IntegrationRule::IntPoint(), FiniteElement::Nodes, pt, IntegrationPoint::x, and IntegrationPoint::y.
Member Function Documentation
void RT2QuadFiniteElement::CalcDivShape (const IntegrationPoint & ip, Vector & divshape) const [virtual]
This virtual function evaluates the divergence of all shape functions at the given IntegrationPoint. The result is stored in the Vector divshape (of size Dof).
Reimplemented from FiniteElement.
Definition at line 2989 of file fe.cpp.
References dpt, pt, IntegrationPoint::x, and IntegrationPoint::y.
virtual void RT2QuadFiniteElement::CalcVShape (ElementTransformation & Trans, DenseMatrix & shape) const [inline, virtual]
Reimplemented from FiniteElement.
Definition at line 821 of file fe.hpp.
References VectorFiniteElement::CalcVShape_RT().
void RT2QuadFiniteElement::CalcVShape (const IntegrationPoint & ip, DenseMatrix & shape) const [virtual]
This virtual function evaluates the values of all components of all shape functions at the given IntegrationPoint. The result is stored in the DenseMatrix shape (Dof x Dim) so that each row contains the components of one shape function.
Reimplemented from FiniteElement.
Definition at line 2889 of file fe.cpp.
References dpt, pt, IntegrationPoint::x, and IntegrationPoint::y.
Referenced by GetLocalInterpolation().
void RT2QuadFiniteElement::GetLocalInterpolation (ElementTransformation & Trans, DenseMatrix & I) const [virtual]
Return the local interpolation matrix I (Dof x Dof) where the fine element is the image of the base geometry under the given transformation.
Reimplemented from FiniteElement.
Definition at line 3087 of file fe.cpp.
References CalcAdjugateTranspose(), CalcVShape(), FiniteElement::Dim, FiniteElement::Dof, IntegrationRule::IntPoint(), ElementTransformation::Jacobian(), VectorFiniteElement::Jinv, mfem_error(), nk, FiniteElement::Nodes, ElementTransformation::SetIntPoint(), ElementTransformation::Transform(), VectorFiniteElement::vshape, IntegrationPoint::x, and IntegrationPoint::y.
void RT2QuadFiniteElement::Project (VectorCoefficient & vc, ElementTransformation & Trans, Vector & dofs) const [virtual]
Given a vector coefficient and a transformation, compute its projection (approximation) in the local finite dimensional space in terms of the degrees of freedom. (VectorFiniteElements)
Reimplemented from FiniteElement.
Definition at line 3137 of file fe.cpp.
References CalcAdjugateTranspose(), FiniteElement::Dim, VectorCoefficient::Eval(), IntegrationRule::IntPoint(), ElementTransformation::Jacobian(), VectorFiniteElement::Jinv, nk, FiniteElement::Nodes, and ElementTransformation::SetIntPoint().
Member Data Documentation
const double RT2QuadFiniteElement::dpt = {0.25,0.5,0.75} [static, private]
Definition at line 813 of file fe.hpp.
Referenced by CalcDivShape(), CalcVShape(), and RT2QuadFiniteElement().
const double RT2QuadFiniteElement::nk [static, private]
Initial value:
{
   {0,-1}, {0,-1}, {0,-1},
   {1, 0}, {1, 0}, {1, 0},
   {0, 1}, {0, 1}, {0, 1},
   {-1,0}, {-1,0}, {-1,0},
   {1, 0}, {1, 0}, {1, 0},
   {1, 0}, {1, 0}, {1, 0},
   {0, 1}, {0, 1}, {0, 1},
   {0, 1}, {0, 1}, {0, 1}
}
Definition at line 811 of file fe.hpp.
Referenced by GetLocalInterpolation(), and Project().
const double RT2QuadFiniteElement::pt = {0.,1./3.,2./3.,1.} [static, private]
Definition at line 812 of file fe.hpp.
Referenced by CalcDivShape(), CalcVShape(), and RT2QuadFiniteElement().
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp