MFEM: DenseMatrixInverse Class Reference
DenseMatrixInverse Class Reference
#include <densemat.hpp>
Public Member Functions
DenseMatrixInverse (const DenseMatrix &mat)
DenseMatrixInverse (const DenseMatrix *mat)
Same as above but does not factorize the matrix.
void Factor ()
Factor the current DenseMatrix, *a.
void Factor (const DenseMatrix &mat)
Factor a new DenseMatrix of the same size.
virtual void Mult (const Vector &x, Vector &y) const
Matrix vector multiplication with inverse of dense matrix.
virtual ~DenseMatrixInverse ()
Destroys dense inverse matrix.
Private Attributes
double * data
Detailed Description
Data type for inverse of square dense matrix. Stores LU factors
Definition at line 286 of file densemat.hpp.
Constructor & Destructor Documentation
DenseMatrixInverse::DenseMatrixInverse (const DenseMatrix & mat)
Creates square dense matrix. Computes factorization of mat and stores LU factors.
Definition at line 2326 of file densemat.cpp.
References data, Factor(), and Operator::size.
DenseMatrixInverse::DenseMatrixInverse (const DenseMatrix * mat)
Same as above but does not factorize the matrix.
Definition at line 2336 of file densemat.cpp.
References data, and Operator::size.
DenseMatrixInverse::~DenseMatrixInverse () [virtual]
Destroys dense inverse matrix.
Definition at line 2438 of file densemat.cpp.
References data.
Member Function Documentation
void DenseMatrixInverse::Factor ()
Factor the current DenseMatrix, *a.
Definition at line 2345 of file densemat.cpp.
References MatrixInverse::a, data, mfem_error(), and Operator::size.
Referenced by DenseMatrixInverse(), and Factor().
void DenseMatrixInverse::Factor (const DenseMatrix & mat)
Factor a new DenseMatrix of the same size.
Definition at line 2387 of file densemat.cpp.
References MatrixInverse::a, Factor(), DenseMatrix::height, mfem_error(), and Operator::size.
void DenseMatrixInverse::Mult (const Vector & x, Vector & y) const [virtual]
Matrix vector multiplication with inverse of dense matrix.
Implements Operator.
Definition at line 2400 of file densemat.cpp.
References data, Vector::GetData(), mfem_error(), and Operator::size.
Member Data Documentation
double* DenseMatrixInverse::data [private]
Definition at line 289 of file densemat.hpp.
Referenced by DenseMatrixInverse(), Factor(), Mult(), and ~DenseMatrixInverse().
The documentation for this class was generated from the following files:
densemat.hpp
densemat.cpp