MFEM: CurlCurlIntegrator Class Reference
CurlCurlIntegrator Class Reference
Integrator for (curl u, curl v) for Nedelec elements.
#include <bilininteg.hpp>
Public Member Functions
CurlCurlIntegrator ()
CurlCurlIntegrator (Coefficient &q)
Construct a bilinear form integrator for Nedelec elements.
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
Private Attributes
DenseMatrix Curlshape
DenseMatrix Curlshape_dFt
Coefficient * Q
Detailed Description
Integrator for (curl u, curl v) for Nedelec elements.
Definition at line 249 of file bilininteg.hpp.
Constructor & Destructor Documentation
CurlCurlIntegrator::CurlCurlIntegrator () [inline]
Definition at line 256 of file bilininteg.hpp.
References Q.
CurlCurlIntegrator::CurlCurlIntegrator (Coefficient & q) [inline]
Construct a bilinear form integrator for Nedelec elements.
Definition at line 258 of file bilininteg.hpp.
Member Function Documentation
void CurlCurlIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 473 of file bilininteg.cpp.
References AddMult_a_AAt(), FiniteElement::CalcCurlShape(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, ElementTransformation::Jacobian(), MultABt(), FunctionSpace::Pk, ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), FiniteElement::Space(), ElementTransformation::Weight(), and IntegrationPoint::weight.
Member Data Documentation
DenseMatrix CurlCurlIntegrator::Curlshape [private]
Definition at line 252 of file bilininteg.hpp.
DenseMatrix CurlCurlIntegrator::Curlshape_dFt [private]
Definition at line 252 of file bilininteg.hpp.
Coefficient* CurlCurlIntegrator::Q [private]
Definition at line 253 of file bilininteg.hpp.
Referenced by CurlCurlIntegrator().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp