MFEM: FunctionCoefficient Class Reference
FunctionCoefficient Class Reference
class for C-function coefficient
#include <coefficient.hpp>
Public Member Functions
FunctionCoefficient (double(*f)(Vector &))
f should be a pointer to a c function
virtual double Eval (ElementTransformation &T, const IntegrationPoint &ip)
Evaluate coefficient.
virtual void Read (istream &in)
Private Attributes
double(* Function)(Vector &)
Vector transip
Detailed Description
class for C-function coefficient
Definition at line 80 of file coefficient.hpp.
Constructor & Destructor Documentation
FunctionCoefficient::FunctionCoefficient (double(*)(Vector &) f) [inline]
f should be a pointer to a c function
Definition at line 89 of file coefficient.hpp.
References Function.
Member Function Documentation
double FunctionCoefficient::Eval (ElementTransformation & T, const IntegrationPoint & ip) [virtual]
Evaluate coefficient.
Implements Coefficient.
Definition at line 35 of file coefficient.cpp.
References Function, ElementTransformation::Transform(), and transip.
virtual void FunctionCoefficient::Read (istream & in) [inline, virtual]
Implements Coefficient.
Definition at line 95 of file coefficient.hpp.
Member Data Documentation
double(* FunctionCoefficient::Function)(Vector &) [private]
Definition at line 83 of file coefficient.hpp.
Referenced by Eval(), and FunctionCoefficient().
Vector FunctionCoefficient::transip [private]
Definition at line 84 of file coefficient.hpp.
Referenced by Eval().
The documentation for this class was generated from the following files:
coefficient.hpp
coefficient.cpp