MFEM: DerivativeIntegrator Class Reference
DerivativeIntegrator Class Reference
Class for integrating (Q D_i(u), v); u and v are scalars.
#include <bilininteg.hpp>
Public Member Functions
DerivativeIntegrator (Coefficient &q, int i)
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
virtual void AssembleElementMatrix2 (const FiniteElement &trial_fe, const FiniteElement &test_fe, ElementTransformation &Trans, DenseMatrix &elmat)
Private Attributes
Coefficient & Q
int xi
DenseMatrix dshape
DenseMatrix dshapedxt
DenseMatrix invdfdx
Vector shape
Vector dshapedxi
Detailed Description
Class for integrating (Q D_i(u), v); u and v are scalars.
Definition at line 259 of file bilininteg.hpp.
Constructor & Destructor Documentation
DerivativeIntegrator::DerivativeIntegrator (Coefficient & q, int i) [inline]
Definition at line 267 of file bilininteg.hpp.
Member Function Documentation
virtual void DerivativeIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [inline, virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 268 of file bilininteg.hpp.
References AssembleElementMatrix2().
void DerivativeIntegrator::AssembleElementMatrix2 (const FiniteElement & trial_fe, const FiniteElement & test_fe, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Compute the local matrix representation of a bilinear form a(u,v) defined on different trial (given by u) and test (given by v) spaces. The rows in the local matrix correspond to the test dofs and the columns -- to the trial dofs.
Reimplemented from BilinearFormIntegrator.
Definition at line 481 of file bilininteg.cpp.
References AddMultVWt(), FiniteElement::CalcDShape(), CalcInverse(), FiniteElement::CalcShape(), dshape, dshapedxi, dshapedxt, Coefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, invdfdx, ElementTransformation::Jacobian(), Mult(), FunctionSpace::Pk, Q, RefinedIntRules, FunctionSpace::rQk, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), shape, FiniteElement::Space(), IntegrationPoint::weight, ElementTransformation::Weight(), and xi.
Referenced by AssembleElementMatrix().
Member Data Documentation
DenseMatrix DerivativeIntegrator::dshape [private]
Definition at line 264 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
Vector DerivativeIntegrator::dshapedxi [private]
Definition at line 265 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
DenseMatrix DerivativeIntegrator::dshapedxt [private]
Definition at line 264 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
DenseMatrix DerivativeIntegrator::invdfdx [private]
Definition at line 264 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
Coefficient& DerivativeIntegrator::Q [private]
Definition at line 262 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
Vector DerivativeIntegrator::shape [private]
Definition at line 265 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
int DerivativeIntegrator::xi [private]
Definition at line 263 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp