MFEM: H1_SegmentElement Class Reference
H1_SegmentElement Class Reference
#include <fe.hpp>
Public Member Functions
H1_SegmentElement (const int p)
virtual void CalcShape (const IntegrationPoint &ip, Vector &shape) const
virtual void CalcDShape (const IntegrationPoint &ip, DenseMatrix &dshape) const
Private Attributes
Poly_1D::Basis & basis1d
Vector shape_x
Vector dshape_x
Detailed Description
Definition at line 1228 of file fe.hpp.
Constructor & Destructor Documentation
H1_SegmentElement::H1_SegmentElement (const int p)
Definition at line 5988 of file fe.cpp.
References Poly_1D::ClosedPoints(), dshape_x, IntegrationRule::IntPoint(), FiniteElement::Nodes, Vector::SetSize(), shape_x, and IntegrationPoint::x.
Member Function Documentation
void H1_SegmentElement::CalcDShape (const IntegrationPoint & ip, DenseMatrix & dshape) const [virtual]
pure virtual function which evaluates the values of all partial derivatives of all shape functions at a given point ip and stores them in the matrix dshape (Dof x Dim) so that each row contains the derivatives of one shape function
Implements FiniteElement.
Definition at line 6022 of file fe.cpp.
References basis1d, dshape_x, Poly_1D::Basis::Eval(), FiniteElement::Order, shape_x, and IntegrationPoint::x.
void H1_SegmentElement::CalcShape (const IntegrationPoint & ip, Vector & shape) const [virtual]
pure virtual function which evaluates the values of all shape functions at a given point ip and stores them in the vector shape of dimension Dof
Implements FiniteElement.
Definition at line 6005 of file fe.cpp.
References basis1d, Poly_1D::Basis::Eval(), FiniteElement::Order, shape_x, and IntegrationPoint::x.
Member Data Documentation
Poly_1D::Basis& H1_SegmentElement::basis1d [private]
Definition at line 1231 of file fe.hpp.
Referenced by CalcDShape(), and CalcShape().
Vector H1_SegmentElement::dshape_x [mutable, private]
Definition at line 1233 of file fe.hpp.
Referenced by CalcDShape(), and H1_SegmentElement().
Vector H1_SegmentElement::shape_x [mutable, private]
Definition at line 1233 of file fe.hpp.
Referenced by CalcDShape(), CalcShape(), and H1_SegmentElement().
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp