MFEM: DSTable Class Reference
DSTable Class Reference
#include <table.hpp>
Classes
class Node
class RowIterator
Public Member Functions
DSTable (int nrows)
int NumberOfRows () const
int NumberOfEntries () const
int Push (int a, int b)
int operator() (int a, int b) const
~DSTable ()
Private Member Functions
int Push_ (int r, int c)
int Index (int r, int c) const
Private Attributes
int NumRows
int NumEntries
Node ** Rows
Detailed Description
Definition at line 156 of file table.hpp.
Constructor & Destructor Documentation
DSTable::DSTable (int nrows)
Definition at line 389 of file table.cpp.
References NumEntries, NumRows, and Rows.
DSTable::~DSTable ()
Definition at line 444 of file table.cpp.
References NumRows, DSTable::Node::Prev, and Rows.
Member Function Documentation
int DSTable::Index (int r, int c) const [private]
Definition at line 426 of file table.cpp.
References mfem_error(), NumRows, DSTable::Node::Prev, and Rows.
Referenced by operator()().
int DSTable::NumberOfEntries () const [inline]
Definition at line 178 of file table.hpp.
References NumEntries.
Referenced by Mesh::GetEdgeVertexTable(), Mesh::GetElementToEdgeTable(), Mesh::LocalRefinement(), and Mesh::MarkTetMeshForRefinement().
int DSTable::NumberOfRows () const [inline]
Definition at line 177 of file table.hpp.
References NumRows.
Referenced by Mesh::Bisection().
int DSTable::operator() (int a, int b) const [inline]
Definition at line 181 of file table.hpp.
References Index().
int DSTable::Push (int a, int b) [inline]
Definition at line 179 of file table.hpp.
References Push_().
Referenced by Mesh::GetVertexToVertexTable().
int DSTable::Push_ (int r, int c) [private]
Definition at line 400 of file table.cpp.
References DSTable::Node::Column, DSTable::Node::Index, mfem_error(), NumEntries, NumRows, DSTable::Node::Prev, and Rows.
Referenced by Push().
Member Data Documentation
int DSTable::NumEntries [private]
Definition at line 166 of file table.hpp.
Referenced by DSTable(), NumberOfEntries(), and Push_().
int DSTable::NumRows [private]
Definition at line 166 of file table.hpp.
Referenced by DSTable(), Index(), NumberOfRows(), Push_(), and ~DSTable().
Node** DSTable::Rows [private]
Definition at line 167 of file table.hpp.
Referenced by DSTable(), Index(), Push_(), DSTable::RowIterator::RowIterator(), and ~DSTable().
The documentation for this class was generated from the following files:
table.hpp
table.cpp