MFEM: Segment Class Reference
Segment Class Reference
Data type line segment element.
#include <segment.hpp>
Public Member Functions
Segment ()
Segment (const int *ind, int attr=1)
Constructs triangle by specifying the indices and the attribute.
Segment (int ind1, int ind2, int attr=1)
Constructs triangle by specifying the indices and the attribute.
virtual void SetVertices (const int *ind)
Set the indices the element according to the input.
virtual int GetType () const
Return element's type.
virtual void GetVertices (Array< int > &v) const
Returns the indices of the element's vertices.
virtual int * GetVertices ()
virtual int GetNVertices () const
virtual int GetNEdges () const
virtual const int * GetEdgeVertices (int ei) const
virtual Element * Duplicate () const
virtual ~Segment ()
Protected Attributes
int indices [2]
Detailed Description
Data type line segment element.
Definition at line 16 of file segment.hpp.
Constructor & Destructor Documentation
Segment::Segment () [inline]
Definition at line 23 of file segment.hpp.
Referenced by Duplicate().
Segment::Segment (const int * ind, int attr = 1)
Constructs triangle by specifying the indices and the attribute.
Definition at line 15 of file segment.cpp.
References Element::attribute, and indices.
Segment::Segment (int ind1, int ind2, int attr = 1)
Constructs triangle by specifying the indices and the attribute.
Definition at line 21 of file segment.cpp.
References Element::attribute, and indices.
virtual Segment::~Segment () [inline, virtual]
Definition at line 51 of file segment.hpp.
Member Function Documentation
virtual Element* Segment::Duplicate () const [inline, virtual]
Implements Element.
Definition at line 48 of file segment.hpp.
References Element::attribute, indices, and Segment().
virtual const int* Segment::GetEdgeVertices (int ei) const [inline, virtual]
Implements Element.
Definition at line 46 of file segment.hpp.
virtual int Segment::GetNEdges () const [inline, virtual]
Implements Element.
Definition at line 44 of file segment.hpp.
virtual int Segment::GetNVertices () const [inline, virtual]
Implements Element.
Definition at line 42 of file segment.hpp.
virtual int Segment::GetType () const [inline, virtual]
Return element's type.
Implements Element.
Definition at line 35 of file segment.hpp.
References Element::SEGMENT.
virtual int* Segment::GetVertices () [inline, virtual]
Implements Element.
Definition at line 40 of file segment.hpp.
References indices.
void Segment::GetVertices (Array< int > & v) const [virtual]
Returns the indices of the element's vertices.
Implements Element.
Definition at line 32 of file segment.cpp.
References indices, and Array< T >::SetSize().
void Segment::SetVertices (const int * ind) [virtual]
Set the indices the element according to the input.
Reimplemented from Element.
Definition at line 27 of file segment.cpp.
References indices.
Member Data Documentation
int Segment::indices[2] [protected]
Definition at line 19 of file segment.hpp.
Referenced by Duplicate(), GetVertices(), Segment(), and SetVertices().
The documentation for this class was generated from the following files:
segment.hpp
segment.cpp