MFEM: IntegerSet Class Reference
IntegerSet Class Reference
A set of integers.
#include <sets.hpp>
Public Member Functions
IntegerSet ()
IntegerSet (IntegerSet &s)
IntegerSet (const int n, const int *p)
int Size ()
operator Array< int > & ()
int PickElement ()
int PickRandomElement ()
int operator== (IntegerSet &s)
void Recreate (const int n, const int *p)
Private Attributes
Array< int > me
Detailed Description
A set of integers.
Definition at line 16 of file sets.hpp.
Constructor & Destructor Documentation
IntegerSet::IntegerSet () [inline]
Definition at line 22 of file sets.hpp.
IntegerSet::IntegerSet (IntegerSet & s)
Definition at line 17 of file sets.cpp.
References me, and Array< T >::Size().
IntegerSet::IntegerSet (const int n, const int * p) [inline]
Definition at line 26 of file sets.hpp.
References Recreate().
Member Function Documentation
IntegerSet::operator Array< int > & () [inline]
Definition at line 30 of file sets.hpp.
References me.
int IntegerSet::operator== (IntegerSet & s)
Definition at line 25 of file sets.cpp.
References me, and Array< T >::Size().
int IntegerSet::PickElement () [inline]
Definition at line 32 of file sets.hpp.
References me.
int IntegerSet::PickRandomElement ()
Definition at line 37 of file sets.cpp.
References me, and Array< T >::Size().
void IntegerSet::Recreate (const int n, const int * p)
Definition at line 50 of file sets.cpp.
References me, Array< T >::SetSize(), and Array< T >::Sort().
Referenced by IntegerSet().
int IntegerSet::Size () [inline]
Definition at line 28 of file sets.hpp.
References me, and Array< T >::Size().
Member Data Documentation
Array<int> IntegerSet::me [private]
Definition at line 19 of file sets.hpp.
Referenced by IntegerSet(), operator Array< int > &(), operator==(), PickElement(), PickRandomElement(), Recreate(), and Size().
The documentation for this class was generated from the following files:
sets.hpp
sets.cpp