MFEM: FiniteElementCollection Class Reference
FiniteElementCollection Class Reference
#include <fe_coll.hpp>
Public Member Functions
virtual const FiniteElement * FiniteElementForGeometry (int GeomType) const =0
virtual int DofForGeometry (int GeomType) const =0
virtual int * DofOrderForOrientation (int GeomType, int Or) const =0
virtual const char * Name () const
int HasFaceDofs (int GeomType) const
virtual ~FiniteElementCollection ()
Static Public Member Functions
static FiniteElementCollection * New (const char *name)
Detailed Description
Collection of finite elements from the same family in multiple dimensions. This class is used to match the degrees of fredom of a FiniteElementSpace between elements, and to provide the finite element restriction from an element to its boundary.
Definition at line 19 of file fe_coll.hpp.
Constructor & Destructor Documentation
virtual FiniteElementCollection::~FiniteElementCollection () [inline, virtual]
Definition at line 33 of file fe_coll.hpp.
Member Function Documentation
virtual int FiniteElementCollection::DofForGeometry (int GeomType) const [pure virtual]
Implemented in H1_FECollection, L2_FECollection, RT_FECollection, ND_FECollection, NURBSFECollection, LinearFECollection, QuadraticFECollection, QuadraticPosFECollection, CubicFECollection, CrouzeixRaviartFECollection, LinearNonConf3DFECollection, RT0_2DFECollection, RT1_2DFECollection, RT2_2DFECollection, Const2DFECollection, LinearDiscont2DFECollection, GaussLinearDiscont2DFECollection, P1OnQuadFECollection, QuadraticDiscont2DFECollection, QuadraticPosDiscont2DFECollection, GaussQuadraticDiscont2DFECollection, CubicDiscont2DFECollection, Const3DFECollection, LinearDiscont3DFECollection, QuadraticDiscont3DFECollection, RefinedLinearFECollection, ND1_3DFECollection, RT0_3DFECollection, RT1_3DFECollection, and Local_FECollection.
Referenced by FiniteElementSpace::Constructor(), FiniteElementSpace::GetBdrElementDofs(), FiniteElementSpace::GetEdgeDofs(), FiniteElementSpace::GetElementDofs(), FiniteElementSpace::GetFaceDofs(), HasFaceDofs(), and Mesh::Load().
virtual int* FiniteElementCollection::DofOrderForOrientation (int GeomType, int Or) const [pure virtual]
Implemented in H1_FECollection, L2_FECollection, RT_FECollection, ND_FECollection, NURBSFECollection, LinearFECollection, QuadraticFECollection, QuadraticPosFECollection, CubicFECollection, CrouzeixRaviartFECollection, LinearNonConf3DFECollection, RT0_2DFECollection, RT1_2DFECollection, RT2_2DFECollection, Const2DFECollection, LinearDiscont2DFECollection, GaussLinearDiscont2DFECollection, P1OnQuadFECollection, QuadraticDiscont2DFECollection, QuadraticPosDiscont2DFECollection, GaussQuadraticDiscont2DFECollection, CubicDiscont2DFECollection, Const3DFECollection, LinearDiscont3DFECollection, QuadraticDiscont3DFECollection, RefinedLinearFECollection, ND1_3DFECollection, RT0_3DFECollection, RT1_3DFECollection, and Local_FECollection.
Referenced by FiniteElementSpace::GetBdrElementDofs(), FiniteElementSpace::GetElementDofs(), and Mesh::Load().
virtual const FiniteElement* FiniteElementCollection::FiniteElementForGeometry (int GeomType) const [pure virtual]
Implemented in H1_FECollection, L2_FECollection, RT_FECollection, ND_FECollection, NURBSFECollection, LinearFECollection, QuadraticFECollection, QuadraticPosFECollection, CubicFECollection, CrouzeixRaviartFECollection, LinearNonConf3DFECollection, RT0_2DFECollection, RT1_2DFECollection, RT2_2DFECollection, Const2DFECollection, LinearDiscont2DFECollection, GaussLinearDiscont2DFECollection, P1OnQuadFECollection, QuadraticDiscont2DFECollection, QuadraticPosDiscont2DFECollection, GaussQuadraticDiscont2DFECollection, CubicDiscont2DFECollection, Const3DFECollection, LinearDiscont3DFECollection, QuadraticDiscont3DFECollection, RefinedLinearFECollection, ND1_3DFECollection, RT0_3DFECollection, RT1_3DFECollection, and Local_FECollection.
Referenced by FiniteElementSpace::GetBE(), FiniteElementSpace::GetFE(), and FiniteElementSpace::GetOrder().
int FiniteElementCollection::HasFaceDofs (int GeomType) const
Definition at line 17 of file fe_coll.cpp.
References Geometry::CUBE, DofForGeometry(), mfem_error(), Geometry::SQUARE, Geometry::TETRAHEDRON, and Geometry::TRIANGLE.
Referenced by FiniteElementSpace::GetElementDofs().
virtual const char* FiniteElementCollection::Name () const [inline, virtual]
Reimplemented in H1_FECollection, L2_FECollection, RT_FECollection, ND_FECollection, NURBSFECollection, LinearFECollection, QuadraticFECollection, QuadraticPosFECollection, CubicFECollection, CrouzeixRaviartFECollection, LinearNonConf3DFECollection, RT0_2DFECollection, RT1_2DFECollection, RT2_2DFECollection, Const2DFECollection, LinearDiscont2DFECollection, GaussLinearDiscont2DFECollection, P1OnQuadFECollection, QuadraticDiscont2DFECollection, QuadraticPosDiscont2DFECollection, GaussQuadraticDiscont2DFECollection, CubicDiscont2DFECollection, Const3DFECollection, LinearDiscont3DFECollection, QuadraticDiscont3DFECollection, RefinedLinearFECollection, ND1_3DFECollection, RT0_3DFECollection, RT1_3DFECollection, and Local_FECollection.
Definition at line 29 of file fe_coll.hpp.
Referenced by GridFunction::GridFunction(), Mesh::PrintVTK(), and FiniteElementSpace::Save().
FiniteElementCollection * FiniteElementCollection::New (const char * name) [static]
Definition at line 30 of file fe_coll.cpp.
References mfem_error().
Referenced by GridFunction::GridFunction().
The documentation for this class was generated from the following files:
fe_coll.hpp
fe_coll.cpp