MFEM: RT0TriangleFiniteElement Class Reference
RT0TriangleFiniteElement Class Reference
Public Member Functions
virtual void CalcVShape (const IntegrationPoint &ip, DenseMatrix &shape) const
virtual void CalcVShape (ElementTransformation &Trans, DenseMatrix &shape) const
virtual void CalcDivShape (const IntegrationPoint &ip, Vector &divshape) const
virtual void GetLocalInterpolation (ElementTransformation &Trans, DenseMatrix &I) const
virtual void Project (VectorCoefficient &vc, ElementTransformation &Trans, Vector &dofs) const
Detailed Description
Definition at line 592 of file fe.hpp.
Member Function Documentation
void RT0TriangleFiniteElement::CalcDivShape (const IntegrationPoint & ip, Vector & divshape) const [virtual]
This virtual function evaluates the divergence of all shape functions at the given IntegrationPoint. The result is stored in the Vector divshape (of size Dof).
Reimplemented from FiniteElement.
Definition at line 1865 of file fe.cpp.
void RT0TriangleFiniteElement::CalcVShape (const IntegrationPoint & ip, DenseMatrix & shape) const [virtual]
This virtual function evaluates the values of all components of all shape functions at the given IntegrationPoint. The result is stored in the DenseMatrix shape (Dof x Dim) so that each row contains the components of one shape function.
Reimplemented from FiniteElement.
Definition at line 1852 of file fe.cpp.
Referenced by GetLocalInterpolation().
void RT0TriangleFiniteElement::GetLocalInterpolation (ElementTransformation & Trans, DenseMatrix & I) const [virtual]
Return the local interpolation matrix I (Dof x Dof) where the fine element is the image of the base geometry under the given transformation.
Reimplemented from FiniteElement.
Definition at line 1876 of file fe.cpp.
References CalcVShape(), IntegrationRule::IntPoint(), and ElementTransformation::Jacobian().
void RT0TriangleFiniteElement::Project (VectorCoefficient & vc, ElementTransformation & Trans, Vector & dofs) const [virtual]
Given a vector coefficient and a transformation, compute its projection (approximation) in the local finite dimensional space in terms of the degrees of freedom. (VectorFiniteElements)
Reimplemented from FiniteElement.
Definition at line 1922 of file fe.cpp.
References IntegrationRule::IntPoint(), and ElementTransformation::Jacobian().
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp