MFEM: ConvectionIntegrator Class Reference
ConvectionIntegrator Class Reference
(q . grad u, v)
#include <bilininteg.hpp>
Public Member Functions
ConvectionIntegrator (VectorCoefficient &q)
virtual void AssembleElementMatrix (const FiniteElement &, ElementTransformation &, DenseMatrix &)
Given a particular Finite Element computes the element matrix elmat.
Private Attributes
DenseMatrix dshape
DenseMatrix invdfdx
Vector shape
Vector vec1
Vector vec2
Vector BdFidxT
VectorCoefficient & Q
Detailed Description
(q . grad u, v)
Definition at line 150 of file bilininteg.hpp.
Constructor & Destructor Documentation
ConvectionIntegrator::ConvectionIntegrator (VectorCoefficient & q) [inline]
Definition at line 159 of file bilininteg.hpp.
Member Function Documentation
void ConvectionIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 289 of file bilininteg.cpp.
References AddMultVWt(), BdFidxT, FiniteElement::CalcDShape(), CalcInverse(), FiniteElement::CalcShape(), dshape, VectorCoefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, invdfdx, ElementTransformation::Jacobian(), DenseMatrix::Mult, Q, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), shape, vec1, vec2, IntegrationPoint::weight, and ElementTransformation::Weight().
Member Data Documentation
Vector ConvectionIntegrator::BdFidxT [private]
Definition at line 156 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix ConvectionIntegrator::dshape [private]
Definition at line 153 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix ConvectionIntegrator::invdfdx [private]
Definition at line 154 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
VectorCoefficient& ConvectionIntegrator::Q [private]
Definition at line 157 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
Vector ConvectionIntegrator::shape [private]
Definition at line 155 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
Vector ConvectionIntegrator::vec1 [private]
Definition at line 155 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
Vector ConvectionIntegrator::vec2 [private]
Definition at line 155 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp