MFEM: ElasticityIntegrator Class Reference
ElasticityIntegrator Class Reference
#include <bilininteg.hpp>
Public Member Functions
ElasticityIntegrator (Coefficient &l, Coefficient &m)
ElasticityIntegrator (Coefficient &m, double q_l, double q_m)
virtual void AssembleElementMatrix (const FiniteElement &, ElementTransformation &, DenseMatrix &)
Given a particular Finite Element computes the element matrix elmat.
Private Attributes
double q_lambda
double q_mu
Coefficient * lambda
Coefficient * mu
DenseMatrix dshape
DenseMatrix Jinv
DenseMatrix gshape
DenseMatrix pelmat
Vector divshape
Detailed Description
Integrator for the linear elasticity form: a(u,v) = (lambda div(u), div(v)) + (2 mu e(u), e(v)), where e(v) = (1/2) (grad(v) + grad(v)^T). This is a 'Vector' integrator, i.e. defined for FE spaces using multiple copies of a scalar FE space.
Definition at line 398 of file bilininteg.hpp.
Constructor & Destructor Documentation
ElasticityIntegrator::ElasticityIntegrator (Coefficient & l, Coefficient & m) [inline]
Definition at line 410 of file bilininteg.hpp.
References lambda, and mu.
ElasticityIntegrator::ElasticityIntegrator (Coefficient & m, double q_l, double q_m) [inline]
With this constructor lambda = q_l * m and mu = q_m * m; if dim * q_l + 2 * q_m = 0 then trace(sigma) = 0.
Definition at line 414 of file bilininteg.hpp.
References lambda, mu, q_lambda, and q_mu.
Member Function Documentation
void ElasticityIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 830 of file bilininteg.cpp.
References AddMult_a_VVt(), FiniteElement::CalcDShape(), CalcInverse(), divshape, dshape, Coefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), DenseMatrix::GradToDiv(), gshape, IntegrationRule::IntPoint(), IntRules, ElementTransformation::Jacobian(), Jinv, lambda, mu, Mult(), MultAAt(), ElementTransformation::OrderGrad(), pelmat, q_lambda, q_mu, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), IntegrationPoint::weight, and ElementTransformation::Weight().
Member Data Documentation
Vector ElasticityIntegrator::divshape [private]
Definition at line 406 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix ElasticityIntegrator::dshape [private]
Definition at line 405 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix ElasticityIntegrator::gshape [private]
Definition at line 405 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix ElasticityIntegrator::Jinv [private]
Definition at line 405 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
Coefficient* ElasticityIntegrator::lambda [private]
Definition at line 402 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), and ElasticityIntegrator().
Coefficient * ElasticityIntegrator::mu [private]
Definition at line 402 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), and ElasticityIntegrator().
DenseMatrix ElasticityIntegrator::pelmat [private]
Definition at line 405 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
double ElasticityIntegrator::q_lambda [private]
Definition at line 401 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), and ElasticityIntegrator().
double ElasticityIntegrator::q_mu [private]
Definition at line 401 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), and ElasticityIntegrator().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp