MFEM: TransformedCoefficient Class Reference
TransformedCoefficient Class Reference
#include <coefficient.hpp>
Public Member Functions
TransformedCoefficient (Coefficient *q, double(*F)(double))
TransformedCoefficient (Coefficient *q1, Coefficient *q2, double(*F)(double, double))
virtual double Eval (ElementTransformation &T, const IntegrationPoint &ip)
virtual void Read (istream &in)
Private Attributes
Coefficient * Q1
Coefficient * Q2
double(* Transform1)(double)
double(* Transform2)(double, double)
Detailed Description
Definition at line 121 of file coefficient.hpp.
Constructor & Destructor Documentation
TransformedCoefficient::TransformedCoefficient (Coefficient * q, double(*)(double) F) [inline]
Definition at line 130 of file coefficient.hpp.
References Q2, and Transform2.
TransformedCoefficient::TransformedCoefficient (Coefficient * q1, Coefficient * q2, double(*)(double, double) F) [inline]
Definition at line 132 of file coefficient.hpp.
References Transform1.
Member Function Documentation
virtual double TransformedCoefficient::Eval (ElementTransformation & T, const IntegrationPoint & ip) [inline, virtual]
Implements Coefficient.
Definition at line 136 of file coefficient.hpp.
References Eval(), Q1, Q2, Transform1, and Transform2.
Referenced by Eval().
virtual void TransformedCoefficient::Read (istream & in) [inline, virtual]
Implements Coefficient.
Definition at line 140 of file coefficient.hpp.
Member Data Documentation
Coefficient* TransformedCoefficient::Q1 [private]
Definition at line 124 of file coefficient.hpp.
Referenced by Eval().
Coefficient* TransformedCoefficient::Q2 [private]
Definition at line 125 of file coefficient.hpp.
Referenced by Eval(), and TransformedCoefficient().
double(* TransformedCoefficient::Transform1)(double) [private]
Definition at line 126 of file coefficient.hpp.
Referenced by Eval(), and TransformedCoefficient().
double(* TransformedCoefficient::Transform2)(double, double) [private]
Definition at line 127 of file coefficient.hpp.
Referenced by Eval(), and TransformedCoefficient().
The documentation for this class was generated from the following file:
coefficient.hpp