MFEM: VectorBoundaryLFIntegrator Class Reference
VectorBoundaryLFIntegrator Class Reference
#include <lininteg.hpp>
Public Member Functions
VectorBoundaryLFIntegrator (VectorCoefficient &QG)
Constructs a boundary integrator with a given VectorCoefficient QG.
virtual void AssembleRHSElementVect (const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
Detailed Description
Class for boundary integration of L(v) := (g, v), where f=(f1,...,fn) and v=(v1,...,vn).
Definition at line 99 of file lininteg.hpp.
Member Function Documentation
void VectorBoundaryLFIntegrator::AssembleRHSElementVect (const FiniteElement & el, ElementTransformation & Tr, Vector & elvect) [virtual]
Given a particular boundary Finite Element and a transformation (Tr) computes the element boundary vector, elvect.
Implements LinearFormIntegrator.
Definition at line 124 of file lininteg.cpp.
References FiniteElement::CalcShape(), IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), VectorCoefficient::GetVDim(), IntegrationRule::IntPoint(), and Vector::SetSize().
The documentation for this class was generated from the following files:
lininteg.hpp
lininteg.cpp