MFEM: NURBSPatchMap Class Reference
NURBSPatchMap Class Reference
#include <nurbs.hpp>
Public Member Functions
NURBSPatchMap (NURBSExtension *ext)
int nx ()
int ny ()
int nz ()
void SetPatchVertexMap (int p, KnotVector *kv[])
void SetPatchDofMap (int p, KnotVector *kv[])
void SetBdrPatchVertexMap (int p, KnotVector *kv[], int *okv)
void SetBdrPatchDofMap (int p, KnotVector *kv[], int *okv)
int operator() (const int i) const
int operator[] (const int i) const
int operator() (const int i, const int j) const
int operator() (const int i, const int j, const int k) const
Private Member Functions
void GetPatchKnotVectors (int p, KnotVector *kv[])
void GetBdrPatchKnotVectors (int p, KnotVector *kv[], int *okv)
Static Private Member Functions
static int F (const int n, const int N)
static int Or1D (const int n, const int N, const int Or)
static int Or2D (const int n1, const int n2, const int N1, const int N2, const int Or)
Private Attributes
NURBSExtension * Ext
int I
int J
int K
int pOffset
int opatch
Array< int > verts
Array< int > edges
Array< int > faces
Array< int > oedge
Array< int > oface
Detailed Description
Definition at line 350 of file nurbs.hpp.
Constructor & Destructor Documentation
NURBSPatchMap::NURBSPatchMap (NURBSExtension * ext) [inline]
Definition at line 372 of file nurbs.hpp.
References Ext.
Member Function Documentation
static int NURBSPatchMap::F (const int n, const int N) [inline, static, private]
Definition at line 358 of file nurbs.hpp.
Referenced by operator()().
void NURBSPatchMap::GetBdrPatchKnotVectors (int p, KnotVector * kv[], int * okv) [private]
Definition at line 2698 of file nurbs.cpp.
References NURBSExtension::Dimension(), edges, Ext, faces, Mesh::GetBdrElementEdges(), Mesh::GetBdrElementFace(), Mesh::GetBdrElementVertices(), NURBSExtension::KnotVec(), oedge, opatch, NURBSExtension::patchTopo, Array< T >::SetSize(), and verts.
Referenced by SetBdrPatchDofMap(), and SetBdrPatchVertexMap().
void NURBSPatchMap::GetPatchKnotVectors (int p, KnotVector * kv[]) [private]
Definition at line 2678 of file nurbs.cpp.
References NURBSExtension::Dimension(), edges, Ext, faces, Mesh::GetElementEdges(), Mesh::GetElementFaces(), Mesh::GetElementVertices(), NURBSExtension::KnotVec(), oedge, oface, opatch, NURBSExtension::patchTopo, and verts.
Referenced by SetPatchDofMap(), and SetPatchVertexMap().
int NURBSPatchMap::nx () [inline]
Definition at line 374 of file nurbs.hpp.
References I.
Referenced by NURBSExtension::Generate2DBdrElementDofTable(), NURBSExtension::Generate3DBdrElementDofTable(), NURBSExtension::GenerateActiveVertices(), NURBSExtension::Get2DBdrElementTopo(), NURBSExtension::Get2DElementTopo(), NURBSExtension::Get3DBdrElementTopo(), and NURBSExtension::Get3DElementTopo().
int NURBSPatchMap::ny () [inline]
Definition at line 375 of file nurbs.hpp.
References J.
Referenced by NURBSExtension::Generate3DBdrElementDofTable(), NURBSExtension::GenerateActiveVertices(), NURBSExtension::Get2DElementTopo(), NURBSExtension::Get3DBdrElementTopo(), and NURBSExtension::Get3DElementTopo().
int NURBSPatchMap::nz () [inline]
Definition at line 376 of file nurbs.hpp.
References K.
Referenced by NURBSExtension::GenerateActiveVertices(), and NURBSExtension::Get3DElementTopo().
int NURBSPatchMap::operator() (const int i, const int j) const [inline]
Definition at line 513 of file nurbs.hpp.
References edges, F(), I, J, mfem_error(), oedge, opatch, Or1D(), Or2D(), pOffset, and verts.
int NURBSPatchMap::operator() (const int i, const int j, const int k) const [inline]
Definition at line 534 of file nurbs.hpp.
References edges, F(), faces, I, J, K, mfem_error(), oedge, oface, Or1D(), Or2D(), pOffset, and verts.
int NURBSPatchMap::operator() (const int i) const [inline]
Definition at line 498 of file nurbs.hpp.
References F(), I, mfem_error(), opatch, Or1D(), pOffset, and verts.
int NURBSPatchMap::operator[] (const int i) const [inline]
Definition at line 385 of file nurbs.hpp.
static int NURBSPatchMap::Or1D (const int n, const int N, const int Or) [inline, static, private]
Definition at line 361 of file nurbs.hpp.
Referenced by operator()().
int NURBSPatchMap::Or2D (const int n1, const int n2, const int N1, const int N2, const int Or) [inline, static, private]
Definition at line 477 of file nurbs.hpp.
References mfem_error().
Referenced by operator()().
void NURBSPatchMap::SetBdrPatchDofMap (int p, KnotVector * kv[], int * okv)
Definition at line 2785 of file nurbs.cpp.
References NURBSExtension::Dimension(), NURBSExtension::e_spaceOffsets, edges, Ext, NURBSExtension::f_spaceOffsets, faces, GetBdrPatchKnotVectors(), KnotVector::GetNCP(), I, J, pOffset, Array< T >::Size(), NURBSExtension::v_spaceOffsets, and verts.
Referenced by NURBSExtension::Generate2DBdrElementDofTable(), and NURBSExtension::Generate3DBdrElementDofTable().
void NURBSPatchMap::SetBdrPatchVertexMap (int p, KnotVector * kv[], int * okv)
Definition at line 2761 of file nurbs.cpp.
References NURBSExtension::Dimension(), NURBSExtension::e_meshOffsets, edges, Ext, NURBSExtension::f_meshOffsets, faces, GetBdrPatchKnotVectors(), KnotVector::GetNE(), I, J, pOffset, Array< T >::Size(), NURBSExtension::v_meshOffsets, and verts.
Referenced by NURBSExtension::Get2DBdrElementTopo(), and NURBSExtension::Get3DBdrElementTopo().
void NURBSPatchMap::SetPatchDofMap (int p, KnotVector * kv[])
Definition at line 2737 of file nurbs.cpp.
References NURBSExtension::Dimension(), NURBSExtension::e_spaceOffsets, edges, Ext, NURBSExtension::f_spaceOffsets, faces, KnotVector::GetNCP(), GetPatchKnotVectors(), I, J, K, NURBSExtension::p_spaceOffsets, pOffset, Array< T >::Size(), NURBSExtension::v_spaceOffsets, and verts.
Referenced by NURBSExtension::Generate2DElementDofTable(), NURBSExtension::Generate3DElementDofTable(), NURBSExtension::Get2DPatchNets(), NURBSExtension::Get3DPatchNets(), NURBSExtension::Set2DSolutionVector(), and NURBSExtension::Set3DSolutionVector().
void NURBSPatchMap::SetPatchVertexMap (int p, KnotVector * kv[])
Definition at line 2713 of file nurbs.cpp.
References NURBSExtension::Dimension(), NURBSExtension::e_meshOffsets, edges, Ext, NURBSExtension::f_meshOffsets, faces, KnotVector::GetNE(), GetPatchKnotVectors(), I, J, K, NURBSExtension::p_meshOffsets, pOffset, Array< T >::Size(), NURBSExtension::v_meshOffsets, and verts.
Referenced by NURBSExtension::GenerateActiveVertices(), NURBSExtension::Get2DElementTopo(), and NURBSExtension::Get3DElementTopo().
Member Data Documentation
Array<int> NURBSPatchMap::edges [private]
Definition at line 356 of file nurbs.hpp.
Referenced by GetBdrPatchKnotVectors(), GetPatchKnotVectors(), operator()(), SetBdrPatchDofMap(), SetBdrPatchVertexMap(), SetPatchDofMap(), and SetPatchVertexMap().
NURBSExtension* NURBSPatchMap::Ext [private]
Definition at line 353 of file nurbs.hpp.
Referenced by GetBdrPatchKnotVectors(), GetPatchKnotVectors(), NURBSPatchMap(), SetBdrPatchDofMap(), SetBdrPatchVertexMap(), SetPatchDofMap(), and SetPatchVertexMap().
Array<int> NURBSPatchMap::faces [private]
Definition at line 356 of file nurbs.hpp.
Referenced by GetBdrPatchKnotVectors(), GetPatchKnotVectors(), operator()(), SetBdrPatchDofMap(), SetBdrPatchVertexMap(), SetPatchDofMap(), and SetPatchVertexMap().
int NURBSPatchMap::I [private]
Definition at line 355 of file nurbs.hpp.
Referenced by nx(), operator()(), SetBdrPatchDofMap(), SetBdrPatchVertexMap(), SetPatchDofMap(), and SetPatchVertexMap().
int NURBSPatchMap::J [private]
Definition at line 355 of file nurbs.hpp.
Referenced by ny(), operator()(), SetBdrPatchDofMap(), SetBdrPatchVertexMap(), SetPatchDofMap(), and SetPatchVertexMap().
int NURBSPatchMap::K [private]
Definition at line 355 of file nurbs.hpp.
Referenced by nz(), operator()(), SetPatchDofMap(), and SetPatchVertexMap().
Array<int> NURBSPatchMap::oedge [private]
Definition at line 356 of file nurbs.hpp.
Referenced by GetBdrPatchKnotVectors(), GetPatchKnotVectors(), and operator()().
Array<int> NURBSPatchMap::oface [private]
Definition at line 356 of file nurbs.hpp.
Referenced by GetPatchKnotVectors(), and operator()().
int NURBSPatchMap::opatch [private]
Definition at line 355 of file nurbs.hpp.
Referenced by GetBdrPatchKnotVectors(), GetPatchKnotVectors(), and operator()().
int NURBSPatchMap::pOffset [private]
Definition at line 355 of file nurbs.hpp.
Referenced by operator()(), SetBdrPatchDofMap(), SetBdrPatchVertexMap(), SetPatchDofMap(), and SetPatchVertexMap().
Array<int> NURBSPatchMap::verts [private]
Definition at line 356 of file nurbs.hpp.
Referenced by GetBdrPatchKnotVectors(), GetPatchKnotVectors(), operator()(), SetBdrPatchDofMap(), SetBdrPatchVertexMap(), SetPatchDofMap(), and SetPatchVertexMap().
The documentation for this class was generated from the following files:
nurbs.hpp
nurbs.cpp