MFEM: LinearForm Class Reference
LinearForm Class Reference
Class for linear form - Vector with asociated FE space and LFIntegrators.
#include <linearform.hpp>
Public Member Functions
LinearForm (FiniteElementSpace *f)
Creates linear form associated with FE space *f.
FiniteElementSpace * GetFES ()
void AddDomainIntegrator (LinearFormIntegrator *lfi)
Adds new Domain Integrator.
void AddBoundaryIntegrator (LinearFormIntegrator *lfi)
Adds new Boundary Integrator.
void AddBdrFaceIntegrator (LinearFormIntegrator *lfi)
Adds new Boundary Face Integrator.
void Assemble ()
Assembles the linear form i.e. sums over all domain/bdr integrators.
void Update ()
void Update (FiniteElementSpace *f)
~LinearForm ()
Destroys linear form.
Private Attributes
FiniteElementSpace * fes
FE space on which LF lives.
Array< LinearFormIntegrator * > dlfi
Set of Domain Integrators to be applied.
Array< LinearFormIntegrator * > blfi
Set of Boundary Integrators to be applied.
Array< LinearFormIntegrator * > flfi
Set of Boundary Face Integrators to be applied.
Detailed Description
Class for linear form - Vector with asociated FE space and LFIntegrators.
Definition at line 16 of file linearform.hpp.
Constructor & Destructor Documentation
LinearForm::LinearForm (FiniteElementSpace * f) [inline]
Creates linear form associated with FE space *f.
Definition at line 33 of file linearform.hpp.
References fes.
LinearForm::~LinearForm ()
Destroys linear form.
Definition at line 87 of file linearform.cpp.
References blfi, dlfi, flfi, and Array< T >::Size().
Member Function Documentation
void LinearForm::AddBdrFaceIntegrator (LinearFormIntegrator * lfi)
Adds new Boundary Face Integrator.
Definition at line 27 of file linearform.cpp.
References Array< T >::Append(), and flfi.
void LinearForm::AddBoundaryIntegrator (LinearFormIntegrator * lfi)
Adds new Boundary Integrator.
Definition at line 22 of file linearform.cpp.
References Array< T >::Append(), and blfi.
Referenced by main().
void LinearForm::AddDomainIntegrator (LinearFormIntegrator * lfi)
Adds new Domain Integrator.
Definition at line 17 of file linearform.cpp.
References Array< T >::Append(), and dlfi.
Referenced by main().
void LinearForm::Assemble ()
Assembles the linear form i.e. sums over all domain/bdr integrators.
Definition at line 32 of file linearform.cpp.
References Vector::AddElementVector(), blfi, dlfi, fes, flfi, FiniteElementSpace::GetBE(), FiniteElementSpace::GetFE(), Vector::operator=(), and Array< T >::Size().
Referenced by main().
FiniteElementSpace* LinearForm::GetFES () [inline]
Definition at line 36 of file linearform.hpp.
References fes.
void LinearForm::Update () [inline]
Definition at line 50 of file linearform.hpp.
References fes, and Vector::SetSize().
void LinearForm::Update (FiniteElementSpace * f) [inline]
Definition at line 52 of file linearform.hpp.
References fes, and Vector::SetSize().
Member Data Documentation
Array<LinearFormIntegrator*> LinearForm::blfi [private]
Set of Boundary Integrators to be applied.
Definition at line 26 of file linearform.hpp.
Referenced by AddBoundaryIntegrator(), Assemble(), and ~LinearForm().
Array<LinearFormIntegrator*> LinearForm::dlfi [private]
Set of Domain Integrators to be applied.
Definition at line 23 of file linearform.hpp.
Referenced by AddDomainIntegrator(), Assemble(), and ~LinearForm().
FiniteElementSpace* LinearForm::fes [private]
FE space on which LF lives.
Definition at line 20 of file linearform.hpp.
Referenced by Assemble(), GetFES(), LinearForm(), and Update().
Array<LinearFormIntegrator*> LinearForm::flfi [private]
Set of Boundary Face Integrators to be applied.
Definition at line 29 of file linearform.hpp.
Referenced by AddBdrFaceIntegrator(), Assemble(), and ~LinearForm().
The documentation for this class was generated from the following files:
linearform.hpp
linearform.cpp