MFEM: VectorFEMassIntegrator Class Reference
VectorFEMassIntegrator Class Reference
Integrator for (Q u, v) for VectorFiniteElements.
#include <bilininteg.hpp>
Public Member Functions
VectorFEMassIntegrator ()
VectorFEMassIntegrator (Coefficient *_q)
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
virtual void AssembleElementMatrix2 (const FiniteElement &trial_fe, const FiniteElement &test_fe, ElementTransformation &Trans, DenseMatrix &elmat)
Private Attributes
Coefficient * Q
Vector shape
DenseMatrix vshape
Detailed Description
Integrator for (Q u, v) for VectorFiniteElements.
Definition at line 268 of file bilininteg.hpp.
Constructor & Destructor Documentation
VectorFEMassIntegrator::VectorFEMassIntegrator () [inline]
Definition at line 277 of file bilininteg.hpp.
References Q.
VectorFEMassIntegrator::VectorFEMassIntegrator (Coefficient * _q) [inline]
Definition at line 278 of file bilininteg.hpp.
References Q.
Member Function Documentation
void VectorFEMassIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 512 of file bilininteg.cpp.
References AddMult_a_AAt(), FiniteElement::CalcVShape(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, ElementTransformation::OrderW(), Q, ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), vshape, ElementTransformation::Weight(), and IntegrationPoint::weight.
void VectorFEMassIntegrator::AssembleElementMatrix2 (const FiniteElement & trial_fe, const FiniteElement & test_fe, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Compute the local matrix representation of a bilinear form a(u,v) defined on different trial (given by u) and test (given by v) spaces. The rows in the local matrix correspond to the test dofs and the columns -- to the trial dofs.
Reimplemented from BilinearFormIntegrator.
Definition at line 547 of file bilininteg.cpp.
References FiniteElement::CalcShape(), FiniteElement::CalcVShape(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, ElementTransformation::OrderW(), Q, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), shape, vshape, ElementTransformation::Weight(), and IntegrationPoint::weight.
Member Data Documentation
Coefficient* VectorFEMassIntegrator::Q [private]
Definition at line 271 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), AssembleElementMatrix2(), and VectorFEMassIntegrator().
Vector VectorFEMassIntegrator::shape [private]
Definition at line 273 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
DenseMatrix VectorFEMassIntegrator::vshape [private]
Definition at line 274 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), and AssembleElementMatrix2().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp