MFEM: DenseMatrixSVD Class Reference
DenseMatrixSVD Class Reference
#include <densemat.hpp>
Public Member Functions
DenseMatrixSVD (DenseMatrix &M)
DenseMatrixSVD (int h, int w)
void Eval (DenseMatrix &M)
double Singularvalue (int i)
~DenseMatrixSVD ()
Private Member Functions
void Init ()
Private Attributes
Vector sv
int m
int n
char jobu
char jobvt
int lwork
int info
double * work
Detailed Description
Definition at line 343 of file densemat.hpp.
Constructor & Destructor Documentation
DenseMatrixSVD::DenseMatrixSVD (DenseMatrix & M)
Definition at line 2497 of file densemat.cpp.
References DenseMatrix::Height(), Init(), m, n, and DenseMatrix::Width().
DenseMatrixSVD::DenseMatrixSVD (int h, int w)
Definition at line 2504 of file densemat.cpp.
References Init(), m, and n.
DenseMatrixSVD::~DenseMatrixSVD ()
Definition at line 2553 of file densemat.cpp.
References work.
Member Function Documentation
void DenseMatrixSVD::Eval (DenseMatrix & M)
Definition at line 2532 of file densemat.cpp.
References DenseMatrix::Data(), Vector::GetData(), DenseMatrix::Height(), info, jobu, jobvt, lwork, m, mfem_error(), n, sv, DenseMatrix::Width(), and work.
void DenseMatrixSVD::Init () [private]
Definition at line 2511 of file densemat.cpp.
References Vector::GetData(), info, jobu, jobvt, lwork, m, mfem_error(), n, Vector::SetSize(), sv, and work.
Referenced by DenseMatrixSVD().
double DenseMatrixSVD::Singularvalue (int i) [inline]
Definition at line 358 of file densemat.hpp.
References sv.
Member Data Documentation
int DenseMatrixSVD::info [private]
Definition at line 349 of file densemat.hpp.
Referenced by Eval(), and Init().
char DenseMatrixSVD::jobu [private]
Definition at line 348 of file densemat.hpp.
Referenced by Eval(), and Init().
char DenseMatrixSVD::jobvt [private]
Definition at line 348 of file densemat.hpp.
Referenced by Eval(), and Init().
int DenseMatrixSVD::lwork [private]
Definition at line 349 of file densemat.hpp.
Referenced by Eval(), and Init().
int DenseMatrixSVD::m [private]
Definition at line 347 of file densemat.hpp.
Referenced by DenseMatrixSVD(), Eval(), and Init().
int DenseMatrixSVD::n [private]
Definition at line 347 of file densemat.hpp.
Referenced by DenseMatrixSVD(), Eval(), and Init().
Vector DenseMatrixSVD::sv [private]
Definition at line 345 of file densemat.hpp.
Referenced by Eval(), Init(), and Singularvalue().
double* DenseMatrixSVD::work [private]
Definition at line 350 of file densemat.hpp.
Referenced by Eval(), Init(), and ~DenseMatrixSVD().
The documentation for this class was generated from the following files:
densemat.hpp
densemat.cpp