MFEM: IsoparametricTransformation Class Reference
IsoparametricTransformation Class Reference
#include <eltrans.hpp>
Public Member Functions
void SetFE (const FiniteElement *FE)
DenseMatrix & GetPointMat ()
virtual void Transform (const IntegrationPoint &, Vector &)
virtual void Transform (const IntegrationRule &, DenseMatrix &)
virtual const DenseMatrix & Jacobian ()
virtual double Weight ()
virtual int OrderJ ()
virtual int OrderW ()
virtual int OrderGrad (const FiniteElement *fe)
order of adj(J)^t.grad(fi)
virtual ~IsoparametricTransformation ()
Private Attributes
DenseMatrix dshape
DenseMatrix dFdx
double Wght
Vector shape
const FiniteElement * FElem
DenseMatrix PointMat
Detailed Description
Definition at line 43 of file eltrans.hpp.
Constructor & Destructor Documentation
virtual IsoparametricTransformation::~IsoparametricTransformation () [inline, virtual]
Definition at line 65 of file eltrans.hpp.
Member Function Documentation
DenseMatrix& IsoparametricTransformation::GetPointMat () [inline]
Definition at line 55 of file eltrans.hpp.
References PointMat.
Referenced by Geometry::Geometry(), Mesh::GetBdrElementTransformation(), Mesh::GetElementTransformation(), Mesh::GetFaceTransformation(), Mesh::GetFineElemTrans(), Mesh::GetLocalQuadToHexTransformation(), Mesh::GetLocalSegToQuadTransformation(), Mesh::GetLocalSegToTriTransformation(), Mesh::GetLocalTriToTetTransformation(), and IntegrationPointTransformation::Transform().
const DenseMatrix & IsoparametricTransformation::Jacobian () [virtual]
Return the jacobian of the transformation at the IntPoint. The first column contains the x derivatives of the transformation, the second -- the y derivatives, etc.
Implements ElementTransformation.
Definition at line 16 of file eltrans.cpp.
References dFdx, dshape, FElem, FiniteElement::GetDim(), FiniteElement::GetDof(), DenseMatrix::Height(), ElementTransformation::IntPoint, ElementTransformation::JacobianIsEvaluated, Mult(), PointMat, DenseMatrix::SetSize(), and DenseMatrix::Width().
Referenced by Geometry::Geometry(), and Weight().
int IsoparametricTransformation::OrderGrad (const FiniteElement * fe) [virtual]
order of adj(J)^t.grad(fi)
Implements ElementTransformation.
Definition at line 70 of file eltrans.cpp.
References FElem, FiniteElement::GetDim(), FiniteElement::GetOrder(), mfem_error(), FunctionSpace::Pk, FunctionSpace::Qk, and FiniteElement::Space().
int IsoparametricTransformation::OrderJ () [virtual]
Implements ElementTransformation.
Definition at line 42 of file eltrans.cpp.
References FElem, FiniteElement::GetOrder(), mfem_error(), FunctionSpace::Pk, FunctionSpace::Qk, and FiniteElement::Space().
int IsoparametricTransformation::OrderW () [virtual]
Implements ElementTransformation.
Definition at line 56 of file eltrans.cpp.
References FElem, FiniteElement::GetDim(), FiniteElement::GetOrder(), mfem_error(), FunctionSpace::Pk, FunctionSpace::Qk, and FiniteElement::Space().
void IsoparametricTransformation::SetFE (const FiniteElement * FE) [inline]
Definition at line 54 of file eltrans.hpp.
References FElem.
Referenced by Geometry::Geometry(), Mesh::GetBdrElementTransformation(), Mesh::GetElementTransformation(), Mesh::GetFaceTransformation(), Mesh::GetFineElemTrans(), Mesh::GetLocalQuadToHexTransformation(), Mesh::GetLocalSegToQuadTransformation(), Mesh::GetLocalSegToTriTransformation(), and Mesh::GetLocalTriToTetTransformation().
void IsoparametricTransformation::Transform (const IntegrationRule & ir, DenseMatrix & tr) [virtual]
Implements ElementTransformation.
Definition at line 99 of file eltrans.cpp.
References FElem, FiniteElement::GetDof(), IntegrationRule::GetNPoints(), DenseMatrix::Height(), IntegrationRule::IntPoint(), PointMat, DenseMatrix::SetSize(), Vector::SetSize(), and shape.
void IsoparametricTransformation::Transform (const IntegrationPoint & ip, Vector & trans) [virtual]
Implements ElementTransformation.
Definition at line 89 of file eltrans.cpp.
References FElem, FiniteElement::GetDof(), DenseMatrix::Height(), DenseMatrix::Mult, PointMat, Vector::SetSize(), and shape.
Referenced by IntegrationPointTransformation::Transform().
double IsoparametricTransformation::Weight () [virtual]
Implements ElementTransformation.
Definition at line 31 of file eltrans.cpp.
References dFdx, FElem, FiniteElement::GetDim(), Jacobian(), DenseMatrix::Weight(), ElementTransformation::WeightIsEvaluated, and Wght.
Member Data Documentation
DenseMatrix IsoparametricTransformation::dFdx [private]
Definition at line 46 of file eltrans.hpp.
Referenced by Jacobian(), and Weight().
DenseMatrix IsoparametricTransformation::dshape [private]
Definition at line 46 of file eltrans.hpp.
Referenced by Jacobian().
const FiniteElement* IsoparametricTransformation::FElem [private]
Definition at line 50 of file eltrans.hpp.
Referenced by Jacobian(), OrderGrad(), OrderJ(), OrderW(), SetFE(), Transform(), and Weight().
DenseMatrix IsoparametricTransformation::PointMat [private]
Definition at line 51 of file eltrans.hpp.
Referenced by GetPointMat(), Jacobian(), and Transform().
Vector IsoparametricTransformation::shape [private]
Definition at line 48 of file eltrans.hpp.
Referenced by Transform().
double IsoparametricTransformation::Wght [private]
Definition at line 47 of file eltrans.hpp.
Referenced by Weight().
The documentation for this class was generated from the following files:
eltrans.hpp
eltrans.cpp