MFEM: GaussQuad2DFiniteElement Class Reference
GaussQuad2DFiniteElement Class Reference
Class for quadratic FE on triangle with nodes at the "Gaussian" points.
#include <fe.hpp>
Public Member Functions
GaussQuad2DFiniteElement ()
virtual void CalcShape (const IntegrationPoint &ip, Vector &shape) const
virtual void CalcDShape (const IntegrationPoint &ip, DenseMatrix &dshape) const
Private Attributes
DenseMatrix A
DenseMatrix D
Vector pol
Static Private Attributes
static const double p [2]
Detailed Description
Class for quadratic FE on triangle with nodes at the "Gaussian" points.
Definition at line 359 of file fe.hpp.
Constructor & Destructor Documentation
GaussQuad2DFiniteElement::GaussQuad2DFiniteElement ()
Definition at line 557 of file fe.cpp.
References A, IntegrationRule::IntPoint(), DenseMatrix::Invert(), FiniteElement::Nodes, p, IntegrationPoint::x, and IntegrationPoint::y.
Member Function Documentation
void GaussQuad2DFiniteElement::CalcDShape (const IntegrationPoint & ip, DenseMatrix & dshape) const [virtual]
pure virtual function which evaluates the values of all partial derivatives of all shape functions at a given point ip and stores them in the matrix dshape (Dof x Dim) so that each row contains the derivatives of one shape function
Implements FiniteElement.
Definition at line 601 of file fe.cpp.
References A, D, Mult(), IntegrationPoint::x, and IntegrationPoint::y.
void GaussQuad2DFiniteElement::CalcShape (const IntegrationPoint & ip, Vector & shape) const [virtual]
pure virtual function which evaluates the values of all shape functions at a given point ip and stores them in the vector shape of dimension Dof
Implements FiniteElement.
Definition at line 587 of file fe.cpp.
References A, DenseMatrix::Mult, pol, IntegrationPoint::x, and IntegrationPoint::y.
Member Data Documentation
DenseMatrix GaussQuad2DFiniteElement::A [private]
Definition at line 363 of file fe.hpp.
Referenced by CalcDShape(), CalcShape(), and GaussQuad2DFiniteElement().
DenseMatrix GaussQuad2DFiniteElement::D [mutable, private]
Definition at line 364 of file fe.hpp.
Referenced by CalcDShape().
const double GaussQuad2DFiniteElement::p [static, private]
Initial value:
{ 0.0915762135097707434595714634022015, 0.445948490915964886318329253883051 }
Definition at line 362 of file fe.hpp.
Referenced by GaussQuad2DFiniteElement().
Vector GaussQuad2DFiniteElement::pol [mutable, private]
Definition at line 365 of file fe.hpp.
Referenced by CalcShape().
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp