MFEM: VectorMassIntegrator Class Reference
VectorMassIntegrator Class Reference
#include <bilininteg.hpp>
Public Member Functions
VectorMassIntegrator ()
Construct an integrator with coefficient 1.0.
VectorMassIntegrator (Coefficient &q, int qo=0)
VectorMassIntegrator (Coefficient &q, const IntegrationRule *ir)
VectorMassIntegrator (VectorCoefficient &q, int qo=0)
Construct an integrator with diagonal coefficient q.
VectorMassIntegrator (MatrixCoefficient &q, int qo=0)
Construct an integrator with matrix coefficient q.
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
Private Attributes
Vector shape
Vector vec
DenseMatrix partelmat
DenseMatrix mcoeff
Coefficient * Q
VectorCoefficient * VQ
MatrixCoefficient * MQ
const IntegrationRule * IntRule
int Q_order
Detailed Description
Class for integrating the bilinear form a(u,v) := (Q u, v), where u=(u1,...,un) and v=(v1,...,vn); ui and vi are defined by scalar FE through standard transformation.
Definition at line 168 of file bilininteg.hpp.
Constructor & Destructor Documentation
VectorMassIntegrator::VectorMassIntegrator () [inline]
Construct an integrator with coefficient 1.0.
Definition at line 183 of file bilininteg.hpp.
References IntRule, MQ, Q, Q_order, and VQ.
VectorMassIntegrator::VectorMassIntegrator (Coefficient & q, int qo = 0) [inline]
Construct an integrator with scalar coefficient q. If possible, save memory by using a scalar integrator since the resulting matrix is block diagonal with the same diagonal block repeated. ;-)
Definition at line 189 of file bilininteg.hpp.
References IntRule, MQ, Q_order, and VQ.
VectorMassIntegrator::VectorMassIntegrator (Coefficient & q, const IntegrationRule * ir) [inline]
Definition at line 191 of file bilininteg.hpp.
References IntRule, MQ, Q_order, and VQ.
VectorMassIntegrator::VectorMassIntegrator (VectorCoefficient & q, int qo = 0) [inline]
Construct an integrator with diagonal coefficient q.
Definition at line 194 of file bilininteg.hpp.
References IntRule, MQ, Q, and Q_order.
VectorMassIntegrator::VectorMassIntegrator (MatrixCoefficient & q, int qo = 0) [inline]
Construct an integrator with matrix coefficient q.
Definition at line 197 of file bilininteg.hpp.
References IntRule, Q, Q_order, and VQ.
Member Function Documentation
void VectorMassIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 328 of file bilininteg.cpp.
References DenseMatrix::AddMatrix(), FiniteElement::CalcShape(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, MultVVt(), norm(), ElementTransformation::OrderW(), RefinedIntRules, FunctionSpace::rQk, ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), FiniteElement::Space(), ElementTransformation::Weight(), and IntegrationPoint::weight.
Member Data Documentation
const IntegrationRule* VectorMassIntegrator::IntRule [private]
Definition at line 178 of file bilininteg.hpp.
Referenced by VectorMassIntegrator().
DenseMatrix VectorMassIntegrator::mcoeff [private]
Definition at line 173 of file bilininteg.hpp.
MatrixCoefficient* VectorMassIntegrator::MQ [private]
Definition at line 176 of file bilininteg.hpp.
Referenced by VectorMassIntegrator().
DenseMatrix VectorMassIntegrator::partelmat [private]
Definition at line 172 of file bilininteg.hpp.
Coefficient* VectorMassIntegrator::Q [private]
Definition at line 174 of file bilininteg.hpp.
Referenced by VectorMassIntegrator().
int VectorMassIntegrator::Q_order [private]
Definition at line 179 of file bilininteg.hpp.
Referenced by VectorMassIntegrator().
Vector VectorMassIntegrator::shape [private]
Definition at line 171 of file bilininteg.hpp.
Vector VectorMassIntegrator::vec [private]
Definition at line 171 of file bilininteg.hpp.
VectorCoefficient* VectorMassIntegrator::VQ [private]
Definition at line 175 of file bilininteg.hpp.
Referenced by VectorMassIntegrator().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp