MFEM: VectorBoundaryFluxLFIntegrator Class Reference
VectorBoundaryFluxLFIntegrator Class Reference
#include <lininteg.hpp>
Public Member Functions
VectorBoundaryFluxLFIntegrator (Coefficient &f, double s=1.0, const IntegrationRule *ir=NULL)
virtual void AssembleRHSElementVect (const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
Private Attributes
double Sign
Coefficient * F
Vector shape
Vector nor
const IntegrationRule * IntRule
Detailed Description
for vector test function v=(v1,...,vn) where all vi are in the same scalar FE space and f is a scalar function.
Definition at line 140 of file lininteg.hpp.
Constructor & Destructor Documentation
VectorBoundaryFluxLFIntegrator::VectorBoundaryFluxLFIntegrator (Coefficient & f, double s = 1.0, const IntegrationRule * ir = NULL) [inline]
Definition at line 149 of file lininteg.hpp.
Member Function Documentation
void VectorBoundaryFluxLFIntegrator::AssembleRHSElementVect (const FiniteElement & el, ElementTransformation & Tr, Vector & elvect) [virtual]
Given a particular Finite Element and a transformation (Tr) computes the element vector, elvect.
Implements LinearFormIntegrator.
Definition at line 183 of file lininteg.cpp.
References FiniteElement::CalcShape(), F, IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRule, IntRules, ElementTransformation::Jacobian(), nor, ElementTransformation::SetIntPoint(), Vector::SetSize(), shape, Sign, and IntegrationPoint::weight.
Member Data Documentation
Coefficient* VectorBoundaryFluxLFIntegrator::F [private]
Definition at line 144 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
const IntegrationRule* VectorBoundaryFluxLFIntegrator::IntRule [private]
Definition at line 146 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Vector VectorBoundaryFluxLFIntegrator::nor [private]
Definition at line 145 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Vector VectorBoundaryFluxLFIntegrator::shape [private]
Definition at line 145 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
double VectorBoundaryFluxLFIntegrator::Sign [private]
Definition at line 143 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
The documentation for this class was generated from the following files:
lininteg.hpp
lininteg.cpp