MFEM: VectorArrayCoefficient Class Reference
VectorArrayCoefficient Class Reference
Vector coefficient defined by an array of scalar coefficients.
#include <coefficient.hpp>
Public Member Functions
VectorArrayCoefficient (int dim)
Construct vector of dim coefficients.
Coefficient & GetCoeff (int i)
Returns i'th coefficient.
Coefficient ** GetCoeffs ()
void Set (int i, Coefficient *c)
Sets coefficient in the vector.
double Eval (int i, ElementTransformation &T, IntegrationPoint &ip)
Evaluates i'th component of the vector.
virtual void Eval (Vector &V, ElementTransformation &T, const IntegrationPoint &ip)
void Read (int i, istream &in)
Reads vector coefficient.
virtual ~VectorArrayCoefficient ()
Destroys vector coefficient.
Private Attributes
Array< Coefficient * > Coeff
Detailed Description
Vector coefficient defined by an array of scalar coefficients.
Definition at line 237 of file coefficient.hpp.
Constructor & Destructor Documentation
VectorArrayCoefficient::VectorArrayCoefficient (int dim) [explicit]
Construct vector of dim coefficients.
Definition at line 80 of file coefficient.cpp.
References Coeff.
VectorArrayCoefficient::~VectorArrayCoefficient () [virtual]
Destroys vector coefficient.
Definition at line 87 of file coefficient.cpp.
References Coeff, and VectorCoefficient::vdim.
Member Function Documentation
double VectorArrayCoefficient::Eval (int i, ElementTransformation & T, IntegrationPoint & ip) [inline]
Evaluates i'th component of the vector.
Definition at line 255 of file coefficient.hpp.
References Coeff, and Eval().
Referenced by Eval().
void VectorArrayCoefficient::Eval (Vector & V, ElementTransformation & T, const IntegrationPoint & ip) [virtual]
Implements VectorCoefficient.
Definition at line 93 of file coefficient.cpp.
References Coeff, Eval(), Vector::SetSize(), and VectorCoefficient::vdim.
Coefficient& VectorArrayCoefficient::GetCoeff (int i) [inline]
Returns i'th coefficient.
Definition at line 247 of file coefficient.hpp.
References Coeff.
Coefficient** VectorArrayCoefficient::GetCoeffs () [inline]
Definition at line 249 of file coefficient.hpp.
References Coeff.
void VectorArrayCoefficient::Read (int i, istream & in) [inline]
Reads vector coefficient.
Definition at line 262 of file coefficient.hpp.
References Coeff, and Read().
Referenced by Read().
void VectorArrayCoefficient::Set (int i, Coefficient * c) [inline]
Sets coefficient in the vector.
Definition at line 252 of file coefficient.hpp.
References Coeff.
Referenced by main().
Member Data Documentation
Array<Coefficient*> VectorArrayCoefficient::Coeff [private]
Definition at line 240 of file coefficient.hpp.
Referenced by Eval(), GetCoeff(), GetCoeffs(), Read(), Set(), VectorArrayCoefficient(), and ~VectorArrayCoefficient().
The documentation for this class was generated from the following files:
coefficient.hpp
coefficient.cpp