MFEM: Coefficient Class Reference
Coefficient Class Reference
Base class Coefficient.
#include <coefficient.hpp>
Public Member Functions
virtual double Eval (ElementTransformation &T, const IntegrationPoint &ip)=0
virtual void Read (istream &in)=0
virtual ~Coefficient ()
Detailed Description
Base class Coefficient.
Definition at line 16 of file coefficient.hpp.
Constructor & Destructor Documentation
virtual Coefficient::~Coefficient () [inline, virtual]
Definition at line 24 of file coefficient.hpp.
Member Function Documentation
virtual double Coefficient::Eval (ElementTransformation & T, const IntegrationPoint & ip) [pure virtual]
Implemented in ConstantCoefficient, PWConstCoefficient, FunctionCoefficient, GridFunctionCoefficient, TransformedCoefficient, DeltaCoefficient, and RestrictedCoefficient.
Referenced by ElasticityIntegrator::AssembleElementMatrix(), DerivativeIntegrator::AssembleElementMatrix2(), VectorFECurlIntegrator::AssembleElementMatrix2(), VectorFEDivergenceIntegrator::AssembleElementMatrix2(), VectorFEBoundaryFluxLFIntegrator::AssembleRHSElementVect(), BoundaryLFIntegrator::AssembleRHSElementVect(), DomainLFIntegrator::AssembleRHSElementVect(), GridFunction::ComputeH1Error(), GridFunction::ComputeL2Error(), ComputeLpNorm(), GridFunction::ComputeMaxError(), GridFunction::ComputeW11Error(), RestrictedCoefficient::Eval(), BiQuadPos2DFiniteElement::Project(), NodalFiniteElement::Project(), GridFunction::ProjectBdrCoefficient(), and GridFunction::ProjectCoefficient().
virtual void Coefficient::Read (istream & in) [pure virtual]
Implemented in ConstantCoefficient, PWConstCoefficient, FunctionCoefficient, GridFunctionCoefficient, TransformedCoefficient, DeltaCoefficient, and RestrictedCoefficient.
The documentation for this class was generated from the following file:
coefficient.hpp