MFEM: Quadrilateral Class Reference
Quadrilateral Class Reference
Data type quadrilateral element.
#include <quadrilateral.hpp>
Public Member Functions
Quadrilateral ()
Quadrilateral (const int *ind, int attr=1)
Constructs quadrilateral by specifying the indices and the attribute.
Quadrilateral (int ind1, int ind2, int ind3, int ind4, int attr=1)
Constructs quadrilateral by specifying the indices and the attribute.
int GetType () const
Return element's type.
virtual void SetVertices (const int *ind)
Set the vertices according to the given input.
virtual void GetVertices (Array< int > &v) const
Returns the indices of the element's vertices.
virtual int * GetVertices ()
virtual int GetNVertices () const
virtual int GetNEdges () const
virtual const int * GetEdgeVertices (int ei) const
virtual Element * Duplicate (Mesh *m) const
virtual ~Quadrilateral ()
Protected Attributes
int indices [4]
Static Protected Attributes
static const int edges [4][2]
Detailed Description
Data type quadrilateral element.
Definition at line 16 of file quadrilateral.hpp.
Constructor & Destructor Documentation
Quadrilateral::Quadrilateral () [inline]
Definition at line 24 of file quadrilateral.hpp.
Referenced by Duplicate().
Quadrilateral::Quadrilateral (const int * ind, int attr = 1)
Constructs quadrilateral by specifying the indices and the attribute.
Definition at line 18 of file quadrilateral.cpp.
References Element::attribute, and indices.
Quadrilateral::Quadrilateral (int ind1, int ind2, int ind3, int ind4, int attr = 1)
Constructs quadrilateral by specifying the indices and the attribute.
Definition at line 26 of file quadrilateral.cpp.
References Element::attribute, and indices.
virtual Quadrilateral::~Quadrilateral () [inline, virtual]
Definition at line 53 of file quadrilateral.hpp.
Member Function Documentation
virtual Element* Quadrilateral::Duplicate (Mesh * m) const [inline, virtual]
Implements Element.
Definition at line 50 of file quadrilateral.hpp.
References Element::attribute, indices, and Quadrilateral().
virtual const int* Quadrilateral::GetEdgeVertices (int ei) const [inline, virtual]
Implements Element.
Definition at line 47 of file quadrilateral.hpp.
References edges.
virtual int Quadrilateral::GetNEdges () const [inline, virtual]
Implements Element.
Definition at line 45 of file quadrilateral.hpp.
virtual int Quadrilateral::GetNVertices () const [inline, virtual]
Implements Element.
Definition at line 43 of file quadrilateral.hpp.
int Quadrilateral::GetType () const [inline, virtual]
Return element's type.
Implements Element.
Definition at line 33 of file quadrilateral.hpp.
References Element::QUADRILATERAL.
virtual int* Quadrilateral::GetVertices () [inline, virtual]
Implements Element.
Definition at line 41 of file quadrilateral.hpp.
References indices.
void Quadrilateral::GetVertices (Array< int > & v) const [virtual]
Returns the indices of the element's vertices.
Implements Element.
Definition at line 40 of file quadrilateral.cpp.
References indices, and Array< T >::SetSize().
void Quadrilateral::SetVertices (const int * ind) [virtual]
Set the vertices according to the given input.
Reimplemented from Element.
Definition at line 35 of file quadrilateral.cpp.
References indices.
Member Data Documentation
const int Quadrilateral::edges [static, protected]
Initial value:
{{0, 1}, {1, 2}, {2, 3}, {3, 0}}
Definition at line 20 of file quadrilateral.hpp.
Referenced by GetEdgeVertices().
int Quadrilateral::indices[4] [protected]
Definition at line 19 of file quadrilateral.hpp.
Referenced by Duplicate(), GetVertices(), Quadrilateral(), and SetVertices().
The documentation for this class was generated from the following files:
quadrilateral.hpp
quadrilateral.cpp