MFEM: VectorFEDomainLFIntegrator Class Reference
VectorFEDomainLFIntegrator Class Reference
for VectorFiniteElements (Nedelec, Raviart-Thomas)
#include <lininteg.hpp>
Public Member Functions
VectorFEDomainLFIntegrator (VectorCoefficient &F)
virtual void AssembleRHSElementVect (const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
Private Attributes
VectorCoefficient & QF
DenseMatrix vshape
Vector vec
Detailed Description
for VectorFiniteElements (Nedelec, Raviart-Thomas)
Definition at line 121 of file lininteg.hpp.
Constructor & Destructor Documentation
VectorFEDomainLFIntegrator::VectorFEDomainLFIntegrator (VectorCoefficient & F) [inline]
Definition at line 129 of file lininteg.hpp.
Member Function Documentation
void VectorFEDomainLFIntegrator::AssembleRHSElementVect (const FiniteElement & el, ElementTransformation & Tr, Vector & elvect) [virtual]
Given a particular Finite Element and a transformation (Tr) computes the element vector, elvect.
Implements LinearFormIntegrator.
Definition at line 148 of file lininteg.cpp.
References DenseMatrix::AddMult(), FiniteElement::CalcVShape(), VectorCoefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, QF, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), vec, vshape, ElementTransformation::Weight(), and IntegrationPoint::weight.
Member Data Documentation
VectorCoefficient& VectorFEDomainLFIntegrator::QF [private]
Definition at line 124 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Vector VectorFEDomainLFIntegrator::vec [private]
Definition at line 126 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
DenseMatrix VectorFEDomainLFIntegrator::vshape [private]
Definition at line 125 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
The documentation for this class was generated from the following files:
lininteg.hpp
lininteg.cpp