MFEM: MatrixArrayCoefficient Class Reference
MatrixArrayCoefficient Class Reference
#include <coefficient.hpp>
Public Member Functions
MatrixArrayCoefficient (int dim)
Coefficient & GetCoeff (int i, int j)
void Set (int i, int j, Coefficient *c)
double Eval (int i, int j, ElementTransformation &T, IntegrationPoint &ip)
virtual void Eval (DenseMatrix &K, ElementTransformation &T, const IntegrationPoint &ip)
virtual ~MatrixArrayCoefficient ()
Private Attributes
Array< Coefficient * > Coeff
Detailed Description
Definition at line 332 of file coefficient.hpp.
Constructor & Destructor Documentation
MatrixArrayCoefficient::MatrixArrayCoefficient (int dim) [explicit]
Definition at line 137 of file coefficient.cpp.
References Coeff, Array< T >::SetSize(), and MatrixCoefficient::vdim.
MatrixArrayCoefficient::~MatrixArrayCoefficient () [virtual]
Definition at line 143 of file coefficient.cpp.
References Coeff, and MatrixCoefficient::vdim.
Member Function Documentation
double MatrixArrayCoefficient::Eval (int i, int j, ElementTransformation & T, IntegrationPoint & ip) [inline]
Definition at line 345 of file coefficient.hpp.
References Coeff, Eval(), and MatrixCoefficient::vdim.
Referenced by Eval().
void MatrixArrayCoefficient::Eval (DenseMatrix & K, ElementTransformation & T, const IntegrationPoint & ip) [virtual]
Implements MatrixCoefficient.
Definition at line 149 of file coefficient.cpp.
References Coeff, Eval(), and MatrixCoefficient::vdim.
Coefficient& MatrixArrayCoefficient::GetCoeff (int i, int j) [inline]
Definition at line 341 of file coefficient.hpp.
References Coeff, and MatrixCoefficient::vdim.
void MatrixArrayCoefficient::Set (int i, int j, Coefficient * c) [inline]
Definition at line 343 of file coefficient.hpp.
References Coeff, and MatrixCoefficient::vdim.
Member Data Documentation
Array<Coefficient *> MatrixArrayCoefficient::Coeff [private]
Definition at line 335 of file coefficient.hpp.
Referenced by Eval(), GetCoeff(), MatrixArrayCoefficient(), Set(), and ~MatrixArrayCoefficient().
The documentation for this class was generated from the following files:
coefficient.hpp
coefficient.cpp