MFEM: Array2D< T > Class Template Reference
Array2D< T > Class Template Reference
#include <array.hpp>
Public Member Functions
Array2D ()
Array2D (int m, int n)
void SetSize (int m, int n)
int NumRows () const
int NumCols () const
const T & operator() (int i, int j) const
T & operator() (int i, int j)
const T * operator[] (int i) const
T * operator[] (int i)
const T * operator() (int i) const
T * operator() (int i)
const T * GetRow (int i) const
T * GetRow (int i)
void Copy (Array2D &copy) const
Private Attributes
Array< T > array1d
int N
Friends
void Swap (Array2D< T > &, Array2D< T > &)
Detailed Description
template<class T>
class Array2D< T >
Definition at line 180 of file array.hpp.
Constructor & Destructor Documentation
template<class T> Array2D< T >::Array2D () [inline]
Definition at line 189 of file array.hpp.
template<class T> Array2D< T >::Array2D (int m, int n) [inline]
Definition at line 190 of file array.hpp.
Member Function Documentation
template<class T> void Array2D< T >::Copy (Array2D< T > & copy) const [inline]
Definition at line 209 of file array.hpp.
template<class T> T* Array2D< T >::GetRow (int i) [inline]
Definition at line 207 of file array.hpp.
template<class T> const T* Array2D< T >::GetRow (int i) const [inline]
Definition at line 206 of file array.hpp.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
template<class T> int Array2D< T >::NumCols () const [inline]
Definition at line 195 of file array.hpp.
Referenced by SparseMatrix::GetBlocks().
template<class T> int Array2D< T >::NumRows () const [inline]
Definition at line 194 of file array.hpp.
Referenced by SparseMatrix::GetBlocks().
template<class T> const T* Array2D< T >::operator() (int i) const [inline]
Definition at line 203 of file array.hpp.
template<class T> T* Array2D< T >::operator() (int i) [inline]
Definition at line 204 of file array.hpp.
template<class T > T & Array2D< T >::operator() (int i, int j) [inline]
Definition at line 417 of file array.hpp.
References mfem_error().
template<class T > const T & Array2D< T >::operator() (int i, int j) const [inline]
Definition at line 402 of file array.hpp.
References mfem_error().
template<class T > const T * Array2D< T >::operator[] (int i) const [inline]
Definition at line 432 of file array.hpp.
References mfem_error().
template<class T > T * Array2D< T >::operator[] (int i) [inline]
Definition at line 446 of file array.hpp.
References mfem_error().
template<class T> void Array2D< T >::SetSize (int m, int n) [inline]
Definition at line 192 of file array.hpp.
Referenced by NURBSExtension::Generate2DBdrElementDofTable(), NURBSExtension::Generate2DElementDofTable(), NURBSExtension::Generate3DBdrElementDofTable(), NURBSExtension::Generate3DElementDofTable(), and MixedBilinearForm::GetBlocks().
Friends And Related Function Documentation
template<class T> void Swap (Array2D< T > & a, Array2D< T > & b) [friend]
Member Data Documentation
template<class T> Array<T> Array2D< T >::array1d [private]
Definition at line 185 of file array.hpp.
Referenced by Array2D< int >::Copy(), and Swap().
template<class T> int Array2D< T >::N [private]
Definition at line 186 of file array.hpp.
Referenced by Array2D< int >::Copy(), and Swap().
The documentation for this class was generated from the following file:
array.hpp