MFEM: BoundaryLFIntegrator Class Reference
BoundaryLFIntegrator Class Reference
Class for boundary integration L(v) := (g, v)
#include <lininteg.hpp>
Public Member Functions
BoundaryLFIntegrator (Coefficient &QG, int a=1, int b=1)
Constructs a boundary integrator with a given Coefficient QG.
virtual void AssembleRHSElementVect (const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
Private Attributes
Vector shape
Coefficient & Q
int oa
int ob
Detailed Description
Class for boundary integration L(v) := (g, v)
Definition at line 59 of file lininteg.hpp.
Constructor & Destructor Documentation
BoundaryLFIntegrator::BoundaryLFIntegrator (Coefficient & QG, int a = 1, int b = 1) [inline]
Constructs a boundary integrator with a given Coefficient QG.
Definition at line 66 of file lininteg.hpp.
Member Function Documentation
void BoundaryLFIntegrator::AssembleRHSElementVect (const FiniteElement & el, ElementTransformation & Tr, Vector & elvect) [virtual]
Given a particular boundary Finite Element and a transformation (Tr) computes the element boundary vector, elvect.
Implements LinearFormIntegrator.
Definition at line 58 of file lininteg.cpp.
References add(), FiniteElement::CalcShape(), Coefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, oa, ob, Q, ElementTransformation::SetIntPoint(), Vector::SetSize(), shape, IntegrationPoint::weight, and ElementTransformation::Weight().
Member Data Documentation
int BoundaryLFIntegrator::oa [private]
Definition at line 63 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
int BoundaryLFIntegrator::ob [private]
Definition at line 63 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Coefficient& BoundaryLFIntegrator::Q [private]
Definition at line 62 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
Vector BoundaryLFIntegrator::shape [private]
Definition at line 61 of file lininteg.hpp.
Referenced by AssembleRHSElementVect().
The documentation for this class was generated from the following files:
lininteg.hpp
lininteg.cpp