MFEM: ParGridFunction Class Reference
ParGridFunction Class Reference
Class for parallel grid function.
#include <pgridfunc.hpp>
Public Member Functions
ParGridFunction ()
ParGridFunction (ParFiniteElementSpace *pf)
ParGridFunction (ParFiniteElementSpace *pf, GridFunction *gf)
ParGridFunction (ParFiniteElementSpace *pf, HypreParVector *tv)
ParGridFunction (ParMesh *pmesh, GridFunction *gf)
ParGridFunction & operator= (double value)
Redefine '=' for GridFunction = constant.
ParGridFunction & operator= (const Vector &v)
Redefine '=' for vector = vector.
ParFiniteElementSpace * ParFESpace ()
void Update (ParFiniteElementSpace *f)
void Update (ParFiniteElementSpace *f, Vector &v, int v_offset)
void Distribute (HypreParVector *tv)
ParGridFunction & operator= (HypreParVector &tv)
Short semantic for Distribute.
void ParallelAverage (HypreParVector &tv)
Returns the vector averaged on the true dofs.
HypreParVector * ParallelAverage ()
Returns a new vector averaged on the true dofs.
double ComputeL1Error (Coefficient *exsol[], const IntegrationRule *irs[]=NULL) const
double ComputeL1Error (VectorCoefficient &exsol, const IntegrationRule *irs[]=NULL) const
double ComputeL2Error (Coefficient *exsol[], const IntegrationRule *irs[]=NULL) const
double ComputeL2Error (VectorCoefficient &exsol, const IntegrationRule *irs[]=NULL, Array< int > *elems=NULL) const
double ComputeMaxError (Coefficient *exsol[], const IntegrationRule *irs[]=NULL) const
double ComputeMaxError (VectorCoefficient &exsol, const IntegrationRule *irs[]=NULL) const
virtual void Save (ostream &out)
void SaveAsOne (ostream &out=cout)
Merge the local grid functions.
virtual ~ParGridFunction ()
Protected Attributes
ParFiniteElementSpace * pfes
Detailed Description
Class for parallel grid function.
Definition at line 16 of file pgridfunc.hpp.
Constructor & Destructor Documentation
ParGridFunction::ParGridFunction () [inline]
Definition at line 22 of file pgridfunc.hpp.
References pfes.
ParGridFunction::ParGridFunction (ParFiniteElementSpace * pf) [inline]
Definition at line 24 of file pgridfunc.hpp.
ParGridFunction::ParGridFunction (ParFiniteElementSpace * pf, GridFunction * gf)
Construct a ParGridFunction corresponding to *pf and the data from *gf which is a local GridFunction on each processor.
ParGridFunction::ParGridFunction (ParFiniteElementSpace * pf, HypreParVector * tv)
Creates grid function on (all) dofs from a given vector on the true dofs, i.e. P tv.
ParGridFunction::ParGridFunction (ParMesh * pmesh, GridFunction * gf)
Construct a ParGridFunction from the given serial GridFunction. The data from 'gf' is NOT copied.
virtual ParGridFunction::~ParGridFunction () [inline, virtual]
Definition at line 91 of file pgridfunc.hpp.
Member Function Documentation
double ParGridFunction::ComputeL1Error (Coefficient * exsol[], const IntegrationRule * irs[] = NULL) const
double ParGridFunction::ComputeL1Error (VectorCoefficient & exsol, const IntegrationRule * irs[] = NULL) const
Reimplemented from GridFunction.
double ParGridFunction::ComputeL2Error (Coefficient * exsol[], const IntegrationRule * irs[] = NULL) const
Reimplemented from GridFunction.
Referenced by main().
double ParGridFunction::ComputeL2Error (VectorCoefficient & exsol, const IntegrationRule * irs[] = NULL, Array< int > * elems = NULL) const
Reimplemented from GridFunction.
double ParGridFunction::ComputeMaxError (VectorCoefficient & exsol, const IntegrationRule * irs[] = NULL) const
Reimplemented from GridFunction.
double ParGridFunction::ComputeMaxError (Coefficient * exsol[], const IntegrationRule * irs[] = NULL) const
Reimplemented from GridFunction.
void ParGridFunction::Distribute (HypreParVector * tv)
Set the grid function on (all) dofs from a given vector on the true dofs, i.e. P tv.
Referenced by operator=().
ParGridFunction& ParGridFunction::operator= (const Vector & v) [inline]
Redefine '=' for vector = vector.
Reimplemented from GridFunction.
Definition at line 41 of file pgridfunc.hpp.
References operator=().
ParGridFunction& ParGridFunction::operator= (double value) [inline]
Redefine '=' for GridFunction = constant.
Reimplemented from GridFunction.
Definition at line 38 of file pgridfunc.hpp.
Referenced by operator=().
ParGridFunction& ParGridFunction::operator= (HypreParVector & tv) [inline]
Short semantic for Distribute.
Definition at line 55 of file pgridfunc.hpp.
References Distribute().
void ParGridFunction::ParallelAverage (HypreParVector & tv)
Returns the vector averaged on the true dofs.
Referenced by main().
HypreParVector* ParGridFunction::ParallelAverage ()
Returns a new vector averaged on the true dofs.
ParFiniteElementSpace* ParGridFunction::ParFESpace () [inline]
Definition at line 44 of file pgridfunc.hpp.
References pfes.
virtual void ParGridFunction::Save (ostream & out) [virtual]
Save the local portion of the ParGridFunction. It differs from the serial GridFunction::Save in that it takes into account the signs of the local dofs.
Reimplemented from GridFunction.
Referenced by main().
void ParGridFunction::SaveAsOne (ostream & out = cout)
Merge the local grid functions.
void ParGridFunction::Update (ParFiniteElementSpace * f)
void ParGridFunction::Update (ParFiniteElementSpace * f, Vector & v, int v_offset)
Member Data Documentation
ParFiniteElementSpace* ParGridFunction::pfes [protected]
Definition at line 19 of file pgridfunc.hpp.
Referenced by ParFESpace(), and ParGridFunction().
The documentation for this class was generated from the following file:
pgridfunc.hpp