MFEM: NURBSExtension Class Reference
NURBSExtension Class Reference
#include <nurbs.hpp>
Public Member Functions
NURBSExtension (istream &input)
Read-in a NURBSExtension.
NURBSExtension (NURBSExtension *parent, int Order)
NURBSExtension (Mesh *mesh_array[], int num_pieces)
Construct a NURBSExtension by merging a partitioned NURBS mesh.
void MergeGridFunctions (GridFunction *gf_array[], int num_pieces, GridFunction &merged)
virtual ~NURBSExtension ()
Destroy a NURBSExtension.
void Print (ostream &out) const
void PrintCharacteristics (ostream &out)
int Dimension ()
int GetNP ()
int GetNBP ()
int GetOrder ()
int GetNKV ()
int GetGNV ()
int GetNV ()
int GetGNE ()
int GetNE ()
int GetGNBE ()
int GetNBE ()
int GetNTotalDof ()
int GetNDof ()
const KnotVector * GetKnotVector (int i) const
void GetElementTopo (Array< Element * > &elements)
void GetBdrElementTopo (Array< Element * > &boundary)
bool HavePatches ()
Table * GetElementDofTable ()
Table * GetBdrElementDofTable ()
void GetVertexLocalToGlobal (Array< int > &lvert_vert)
void GetElementLocalToGlobal (Array< int > &lelem_elem)
void LoadFE (int i, const FiniteElement *FE)
void LoadBE (int i, const FiniteElement *BE)
const Vector & GetWeights () const
Vector & GetWeights ()
void ConvertToPatches (const Vector &Nodes)
void SetKnotsFromPatches ()
void SetCoordsFromPatches (Vector &Nodes)
void DegreeElevate (int t)
void UniformRefinement ()
void KnotInsert (Array< KnotVector * > &kv)
Protected Member Functions
int KnotInd (int edge)
KnotVector * KnotVec (int edge)
KnotVector * KnotVec (int edge, int oedge, int *okv)
void CheckPatches ()
void CheckBdrPatches ()
void GetPatchKnotVectors (int p, Array< KnotVector * > &kv)
void GetBdrPatchKnotVectors (int p, Array< KnotVector * > &kv)
void GenerateOffsets ()
void CountElements ()
void CountBdrElements ()
void Get2DElementTopo (Array< Element * > &elements)
void Get3DElementTopo (Array< Element * > &elements)
void Get2DBdrElementTopo (Array< Element * > &boundary)
void Get3DBdrElementTopo (Array< Element * > &boundary)
void GenerateElementDofTable ()
void Generate2DElementDofTable ()
void Generate3DElementDofTable ()
void GenerateBdrElementDofTable ()
void Generate2DBdrElementDofTable ()
void Generate3DBdrElementDofTable ()
void GetPatchNets (const Vector &Nodes)
void Get2DPatchNets (const Vector &Nodes)
void Get3DPatchNets (const Vector &Nodes)
void SetSolutionVector (Vector &Nodes)
void Set2DSolutionVector (Vector &Nodes)
void Set3DSolutionVector (Vector &Nodes)
void GenerateActiveVertices ()
void GenerateActiveBdrElems ()
void MergeWeights (Mesh *mesh_array[], int num_pieces)
NURBSExtension ()
Protected Attributes
int Order
int NumOfKnotVectors
int NumOfVertices
int NumOfElements
int NumOfBdrElements
int NumOfDofs
int NumOfActiveVertices
int NumOfActiveElems
int NumOfActiveBdrElems
int NumOfActiveDofs
Array< int > activeVert
Array< bool > activeElem
Array< bool > activeBdrElem
Array< int > activeDof
Mesh * patchTopo
int own_topo
Array< int > edge_to_knot
Array< KnotVector * > knotVectors
Vector weights
Array< int > v_meshOffsets
Array< int > e_meshOffsets
Array< int > f_meshOffsets
Array< int > p_meshOffsets
Array< int > v_spaceOffsets
Array< int > e_spaceOffsets
Array< int > f_spaceOffsets
Array< int > p_spaceOffsets
Table * el_dof
Table * bel_dof
Array< int > el_to_patch
Array< int > bel_to_patch
Array2D< int > el_to_IJK
Array2D< int > bel_to_IJK
Array< NURBSPatch * > patches
Friends
class NURBSPatchMap
Detailed Description
Definition at line 136 of file nurbs.hpp.
Constructor & Destructor Documentation
NURBSExtension::NURBSExtension () [inline, protected]
Definition at line 247 of file nurbs.hpp.
NURBSExtension::NURBSExtension (istream & input)
Read-in a NURBSExtension.
Definition at line 1038 of file nurbs.cpp.
References activeElem, CheckPatches(), CountBdrElements(), CountElements(), Dimension(), edge_to_knot, Tetrahedron::edges, GenerateActiveBdrElems(), GenerateActiveVertices(), GenerateBdrElementDofTable(), GenerateElementDofTable(), GenerateOffsets(), Mesh::GetElementEdges(), GetGNE(), GetNDof(), Mesh::GetNEdges(), GetNP(), GetOrder(), KnotInd(), knotVectors, Vector::Load(), Mesh::LoadPatchTopo(), mfem_error(), NumOfActiveElems, NumOfElements, NumOfKnotVectors, Order, own_topo, patches, patchTopo, Vector::SetSize(), Array< T >::SetSize(), Array< T >::Size(), skip_comment_lines(), and weights.
NURBSExtension::NURBSExtension (NURBSExtension * parent, int Order)
Create a NURBSExtension with elevated order by repeating the endpoints of the knot vectors and using uniform weights of 1.
Definition at line 1164 of file nurbs.cpp.
References activeBdrElem, activeElem, activeVert, Array< T >::Copy(), KnotVector::DegreeElevate(), edge_to_knot, GenerateBdrElementDofTable(), GenerateElementDofTable(), GenerateOffsets(), GetKnotVector(), GetNDof(), GetNKV(), GetOrder(), knotVectors, NumOfActiveBdrElems, NumOfActiveElems, NumOfActiveVertices, NumOfBdrElements, NumOfElements, NumOfKnotVectors, Order, own_topo, patchTopo, Vector::SetSize(), Array< T >::SetSize(), and weights.
NURBSExtension::NURBSExtension (Mesh * mesh_array[], int num_pieces)
Construct a NURBSExtension by merging a partitioned NURBS mesh.
Definition at line 1201 of file nurbs.cpp.
References activeElem, Array< T >::Copy(), CountBdrElements(), CountElements(), edge_to_knot, GenerateActiveBdrElems(), GenerateActiveVertices(), GenerateBdrElementDofTable(), GenerateElementDofTable(), GenerateOffsets(), GetKnotVector(), GetNDof(), GetNKV(), GetOrder(), knotVectors, MergeWeights(), mfem_error(), NumOfActiveElems, NumOfElements, NumOfKnotVectors, Mesh::NURBSext, Order, own_topo, patchTopo, Vector::SetSize(), Array< T >::SetSize(), and weights.
NURBSExtension::~NURBSExtension () [virtual]
Destroy a NURBSExtension.
Definition at line 1241 of file nurbs.cpp.
References bel_dof, el_dof, knotVectors, own_topo, patches, patchTopo, and Array< T >::Size().
Member Function Documentation
void NURBSExtension::CheckBdrPatches () [protected]
Definition at line 1479 of file nurbs.cpp.
References Dimension(), edge_to_knot, Tetrahedron::edges, Mesh::GetBdrElementEdges(), GetNBP(), mfem_error(), patchTopo, and Array< T >::Size().
void NURBSExtension::CheckPatches () [protected]
Definition at line 1435 of file nurbs.cpp.
References Dimension(), edge_to_knot, Tetrahedron::edges, Mesh::GetElementEdges(), GetNP(), mfem_error(), patchTopo, and Array< T >::Size().
Referenced by NURBSExtension().
void NURBSExtension::ConvertToPatches (const Vector & Nodes)
Definition at line 2161 of file nurbs.cpp.
References bel_dof, el_dof, GetPatchNets(), patches, and Array< T >::Size().
Referenced by Mesh::DegreeElevate(), Mesh::KnotInsert(), and Mesh::NURBSUniformRefinement().
void NURBSExtension::CountBdrElements () [protected]
Definition at line 1650 of file nurbs.cpp.
References Dimension(), GetBdrPatchKnotVectors(), GetNBP(), GetNE(), and NumOfBdrElements.
Referenced by NURBSExtension(), and SetKnotsFromPatches().
void NURBSExtension::CountElements () [protected]
Definition at line 1632 of file nurbs.cpp.
References Dimension(), GetNE(), GetNP(), GetPatchKnotVectors(), and NumOfElements.
Referenced by NURBSExtension(), and SetKnotsFromPatches().
void NURBSExtension::DegreeElevate (int t)
Definition at line 2217 of file nurbs.cpp.
References patches, and Array< T >::Size().
Referenced by Mesh::DegreeElevate().
int NURBSExtension::Dimension () [inline]
Definition at line 269 of file nurbs.hpp.
References Mesh::Dimension(), and patchTopo.
Referenced by CheckBdrPatches(), CheckPatches(), CountBdrElements(), CountElements(), GenerateActiveBdrElems(), GenerateActiveVertices(), GenerateBdrElementDofTable(), GenerateElementDofTable(), GenerateOffsets(), GetBdrElementTopo(), NURBSPatchMap::GetBdrPatchKnotVectors(), GetBdrPatchKnotVectors(), GetElementTopo(), NURBSPatchMap::GetPatchKnotVectors(), GetPatchKnotVectors(), GetPatchNets(), KnotInsert(), Mesh::Load(), NURBSExtension(), PrintCharacteristics(), NURBSPatchMap::SetBdrPatchDofMap(), NURBSPatchMap::SetBdrPatchVertexMap(), NURBSPatchMap::SetPatchDofMap(), NURBSPatchMap::SetPatchVertexMap(), SetSolutionVector(), and Mesh::UpdateNURBS().
void NURBSExtension::Generate2DBdrElementDofTable () [protected]
Definition at line 2009 of file nurbs.cpp.
References activeBdrElem, bel_dof, bel_to_IJK, bel_to_patch, GetNBP(), KnotVector::GetNKS(), Table::GetRow(), NumOfActiveBdrElems, NURBSPatchMap::nx(), Order, NURBSPatchMap::SetBdrPatchDofMap(), Array2D< T >::SetSize(), and Array< T >::SetSize().
Referenced by GenerateBdrElementDofTable().
void NURBSExtension::Generate2DElementDofTable () [protected]
Definition at line 1876 of file nurbs.cpp.
References activeDof, activeElem, el_dof, el_to_IJK, el_to_patch, KnotVector::GetNKS(), GetNP(), Table::GetRow(), NumOfActiveElems, Order, NURBSPatchMap::SetPatchDofMap(), Array2D< T >::SetSize(), and Array< T >::SetSize().
Referenced by GenerateElementDofTable().
void NURBSExtension::Generate3DBdrElementDofTable () [protected]
Definition at line 2050 of file nurbs.cpp.
References activeBdrElem, bel_dof, bel_to_IJK, bel_to_patch, GetNBP(), KnotVector::GetNKS(), Table::GetRow(), NumOfActiveBdrElems, NURBSPatchMap::nx(), NURBSPatchMap::ny(), Order, NURBSPatchMap::SetBdrPatchDofMap(), Array2D< T >::SetSize(), and Array< T >::SetSize().
Referenced by GenerateBdrElementDofTable().
void NURBSExtension::Generate3DElementDofTable () [protected]
Definition at line 1927 of file nurbs.cpp.
References activeDof, activeElem, el_dof, el_to_IJK, el_to_patch, KnotVector::GetNKS(), GetNP(), Table::GetRow(), NumOfActiveElems, Order, NURBSPatchMap::SetPatchDofMap(), Array2D< T >::SetSize(), and Array< T >::SetSize().
Referenced by GenerateElementDofTable().
void NURBSExtension::GenerateActiveBdrElems () [protected]
Definition at line 1365 of file nurbs.cpp.
References activeBdrElem, Dimension(), GetGNBE(), GetGNE(), GetNE(), NumOfActiveBdrElems, and Array< T >::SetSize().
Referenced by NURBSExtension(), and SetKnotsFromPatches().
void NURBSExtension::GenerateActiveVertices () [protected]
Definition at line 1302 of file nurbs.cpp.
References activeElem, activeVert, Dimension(), GetGNV(), GetNP(), NumOfActiveVertices, NURBSPatchMap::nx(), NURBSPatchMap::ny(), NURBSPatchMap::nz(), NURBSPatchMap::SetPatchVertexMap(), and Array< T >::SetSize().
Referenced by NURBSExtension(), and SetKnotsFromPatches().
void NURBSExtension::GenerateBdrElementDofTable () [protected]
Definition at line 1990 of file nurbs.cpp.
References activeDof, bel_dof, Dimension(), Generate2DBdrElementDofTable(), Generate3DBdrElementDofTable(), Table::GetJ(), and Table::Size_of_connections().
Referenced by NURBSExtension(), and SetKnotsFromPatches().
void NURBSExtension::GenerateElementDofTable () [protected]
Definition at line 1846 of file nurbs.cpp.
References activeDof, Dimension(), el_dof, Generate2DElementDofTable(), Generate3DElementDofTable(), Table::GetJ(), GetNTotalDof(), NumOfActiveDofs, Array< T >::SetSize(), and Table::Size_of_connections().
Referenced by NURBSExtension(), and SetKnotsFromPatches().
void NURBSExtension::GenerateOffsets () [protected]
Definition at line 1545 of file nurbs.cpp.
References Dimension(), e_meshOffsets, e_spaceOffsets, Tetrahedron::edges, f_meshOffsets, f_spaceOffsets, Mesh::GetElementEdges(), Mesh::GetFaceEdges(), KnotVector::GetNCP(), KnotVector::GetNE(), Mesh::GetNE(), Mesh::GetNEdges(), Mesh::GetNFaces(), Mesh::GetNV(), KnotVec(), NumOfDofs, NumOfVertices, p_meshOffsets, p_spaceOffsets, patchTopo, Array< T >::SetSize(), v_meshOffsets, and v_spaceOffsets.
Referenced by NURBSExtension(), and SetKnotsFromPatches().
void NURBSExtension::Get2DBdrElementTopo (Array< Element * > & boundary) [protected]
Definition at line 1777 of file nurbs.cpp.
References activeBdrElem, activeVert, Mesh::GetBdrAttribute(), GetNBP(), NURBSPatchMap::nx(), patchTopo, and NURBSPatchMap::SetBdrPatchVertexMap().
Referenced by GetBdrElementTopo().
void NURBSExtension::Get2DElementTopo (Array< Element * > & elements) [protected]
Definition at line 1682 of file nurbs.cpp.
References activeElem, activeVert, Mesh::GetAttribute(), GetNP(), NURBSPatchMap::nx(), NURBSPatchMap::ny(), patchTopo, and NURBSPatchMap::SetPatchVertexMap().
Referenced by GetElementTopo().
void NURBSExtension::Get2DPatchNets (const Vector & Nodes) [protected]
Definition at line 2272 of file nurbs.cpp.
References GetNP(), patches, NURBSPatchMap::SetPatchDofMap(), Array< T >::SetSize(), and weights.
Referenced by GetPatchNets().
void NURBSExtension::Get3DBdrElementTopo (Array< Element * > & boundary) [protected]
Definition at line 1808 of file nurbs.cpp.
References activeBdrElem, activeVert, Mesh::GetBdrAttribute(), GetNBP(), NURBSPatchMap::nx(), NURBSPatchMap::ny(), patchTopo, and NURBSPatchMap::SetBdrPatchVertexMap().
Referenced by GetBdrElementTopo().
void NURBSExtension::Get3DElementTopo (Array< Element * > & elements) [protected]
Definition at line 1718 of file nurbs.cpp.
References activeElem, activeVert, Mesh::GetAttribute(), GetNP(), NURBSPatchMap::nx(), NURBSPatchMap::ny(), NURBSPatchMap::nz(), patchTopo, and NURBSPatchMap::SetPatchVertexMap().
Referenced by GetElementTopo().
void NURBSExtension::Get3DPatchNets (const Vector & Nodes) [protected]
Definition at line 2299 of file nurbs.cpp.
References GetNP(), patches, NURBSPatchMap::SetPatchDofMap(), Array< T >::SetSize(), and weights.
Referenced by GetPatchNets().
Table* NURBSExtension::GetBdrElementDofTable () [inline]
Definition at line 295 of file nurbs.hpp.
References bel_dof.
Referenced by FiniteElementSpace::UpdateNURBS().
void NURBSExtension::GetBdrElementTopo (Array< Element * > & boundary)
Definition at line 1763 of file nurbs.cpp.
References Dimension(), Get2DBdrElementTopo(), Get3DBdrElementTopo(), GetNBE(), and Array< T >::SetSize().
Referenced by Mesh::Load(), and Mesh::UpdateNURBS().
void NURBSExtension::GetBdrPatchKnotVectors (int p, Array< KnotVector * > & kv) [protected]
Definition at line 1526 of file nurbs.cpp.
References Dimension(), Tetrahedron::edges, Mesh::GetBdrElementEdges(), KnotVec(), patchTopo, and Array< T >::SetSize().
Referenced by CountBdrElements(), and LoadBE().
Table* NURBSExtension::GetElementDofTable () [inline]
Definition at line 294 of file nurbs.hpp.
References el_dof.
Referenced by FiniteElementSpace::UpdateNURBS().
void NURBSExtension::GetElementLocalToGlobal (Array< int > & lelem_elem)
Definition at line 2113 of file nurbs.cpp.
References activeElem, GetGNE(), GetNE(), and Array< T >::SetSize().
Referenced by MergeGridFunctions(), MergeWeights(), and Mesh::Mesh().
void NURBSExtension::GetElementTopo (Array< Element * > & elements)
Definition at line 1668 of file nurbs.cpp.
References Dimension(), Get2DElementTopo(), Get3DElementTopo(), GetNE(), and Array< T >::SetSize().
Referenced by Mesh::Load(), Mesh::Mesh(), and Mesh::UpdateNURBS().
int NURBSExtension::GetGNBE () [inline]
Definition at line 279 of file nurbs.hpp.
References NumOfBdrElements.
Referenced by GenerateActiveBdrElems(), and PrintCharacteristics().
int NURBSExtension::GetGNE () [inline]
Definition at line 277 of file nurbs.hpp.
References NumOfElements.
Referenced by GenerateActiveBdrElems(), GetElementLocalToGlobal(), NURBSExtension(), and PrintCharacteristics().
int NURBSExtension::GetGNV () [inline]
Definition at line 275 of file nurbs.hpp.
References NumOfVertices.
Referenced by GenerateActiveVertices(), GetVertexLocalToGlobal(), and PrintCharacteristics().
const KnotVector* NURBSExtension::GetKnotVector (int i) const [inline]
Definition at line 286 of file nurbs.hpp.
References knotVectors.
Referenced by NURBSExtension().
int NURBSExtension::GetNBE () [inline]
Definition at line 280 of file nurbs.hpp.
References NumOfActiveBdrElems.
Referenced by GetBdrElementTopo(), Mesh::Load(), PrintCharacteristics(), and Mesh::UpdateNURBS().
int NURBSExtension::GetNBP () [inline]
Definition at line 271 of file nurbs.hpp.
References Mesh::GetNBE(), and patchTopo.
Referenced by CheckBdrPatches(), CountBdrElements(), Generate2DBdrElementDofTable(), Generate3DBdrElementDofTable(), Get2DBdrElementTopo(), Get3DBdrElementTopo(), and PrintCharacteristics().
int NURBSExtension::GetNDof () [inline]
Definition at line 283 of file nurbs.hpp.
References NumOfActiveDofs.
Referenced by NURBSExtension(), PrintCharacteristics(), Set2DSolutionVector(), Set3DSolutionVector(), and FiniteElementSpace::UpdateNURBS().
int NURBSExtension::GetNE () [inline]
Definition at line 278 of file nurbs.hpp.
References NumOfActiveElems.
Referenced by CountBdrElements(), CountElements(), GenerateActiveBdrElems(), GetElementLocalToGlobal(), GetElementTopo(), Mesh::Load(), MergeGridFunctions(), MergeWeights(), Mesh::Mesh(), PrintCharacteristics(), and Mesh::UpdateNURBS().
int NURBSExtension::GetNKV () [inline]
Definition at line 273 of file nurbs.hpp.
References NumOfKnotVectors.
Referenced by Mesh::KnotInsert(), NURBSExtension(), and PrintCharacteristics().
int NURBSExtension::GetNP () [inline]
Definition at line 270 of file nurbs.hpp.
References Mesh::GetNE(), and patchTopo.
Referenced by CheckPatches(), CountElements(), Generate2DElementDofTable(), Generate3DElementDofTable(), GenerateActiveVertices(), Get2DElementTopo(), Get2DPatchNets(), Get3DElementTopo(), Get3DPatchNets(), NURBSExtension(), PrintCharacteristics(), Set2DSolutionVector(), and Set3DSolutionVector().
int NURBSExtension::GetNTotalDof () [inline]
Definition at line 282 of file nurbs.hpp.
References NumOfDofs.
Referenced by GenerateElementDofTable(), and PrintCharacteristics().
int NURBSExtension::GetNV () [inline]
Definition at line 276 of file nurbs.hpp.
References NumOfActiveVertices.
Referenced by GetVertexLocalToGlobal(), Mesh::Load(), Mesh::Mesh(), PrintCharacteristics(), and Mesh::UpdateNURBS().
int NURBSExtension::GetOrder () [inline]
Definition at line 272 of file nurbs.hpp.
References Order.
Referenced by FiniteElementSpace::FiniteElementSpace(), Mesh::Load(), main(), NURBSExtension(), PrintCharacteristics(), and SetKnotsFromPatches().
void NURBSExtension::GetPatchKnotVectors (int p, Array< KnotVector * > & kv) [protected]
Definition at line 1505 of file nurbs.cpp.
References Dimension(), Tetrahedron::edges, Mesh::GetElementEdges(), KnotVec(), patchTopo, and Array< T >::SetSize().
Referenced by CountElements(), LoadFE(), and SetKnotsFromPatches().
void NURBSExtension::GetPatchNets (const Vector & Nodes) [protected]
Definition at line 2260 of file nurbs.cpp.
References Dimension(), Get2DPatchNets(), and Get3DPatchNets().
Referenced by ConvertToPatches().
void NURBSExtension::GetVertexLocalToGlobal (Array< int > & lvert_vert)
Definition at line 2105 of file nurbs.cpp.
References activeVert, GetGNV(), GetNV(), and Array< T >::SetSize().
Referenced by Mesh::Mesh().
Vector& NURBSExtension::GetWeights () [inline]
Definition at line 305 of file nurbs.hpp.
References weights.
const Vector& NURBSExtension::GetWeights () const [inline]
Definition at line 304 of file nurbs.hpp.
References weights.
bool NURBSExtension::HavePatches () [inline]
Definition at line 292 of file nurbs.hpp.
References patches, and Array< T >::Size().
Referenced by Mesh::Load().
int NURBSExtension::KnotInd (int edge) [inline, protected]
Definition at line 450 of file nurbs.hpp.
References edge_to_knot.
Referenced by KnotInsert(), KnotVec(), and NURBSExtension().
void NURBSExtension::KnotInsert (Array< KnotVector * > & kv)
Definition at line 2233 of file nurbs.cpp.
References Dimension(), Tetrahedron::edges, Mesh::GetElementEdges(), KnotInd(), patches, patchTopo, and Array< T >::Size().
Referenced by Mesh::KnotInsert().
KnotVector * NURBSExtension::KnotVec (int edge) [inline, protected]
Definition at line 456 of file nurbs.hpp.
References KnotInd(), and knotVectors.
Referenced by GenerateOffsets(), NURBSPatchMap::GetBdrPatchKnotVectors(), GetBdrPatchKnotVectors(), NURBSPatchMap::GetPatchKnotVectors(), and GetPatchKnotVectors().
KnotVector * NURBSExtension::KnotVec (int edge, int oedge, int * okv) [inline, protected]
Definition at line 461 of file nurbs.hpp.
References edge_to_knot, and knotVectors.
void NURBSExtension::LoadBE (int i, const FiniteElement * BE)
Definition at line 2141 of file nurbs.cpp.
References bel_dof, bel_to_IJK, bel_to_patch, GetBdrPatchKnotVectors(), NURBSFiniteElement::GetElement(), NURBSFiniteElement::GetPatch(), Table::GetRow(), Array2D< T >::GetRow(), Vector::GetSubVector(), NURBSFiniteElement::KnotVectors(), NURBSFiniteElement::SetElement(), NURBSFiniteElement::SetIJK(), NURBSFiniteElement::SetPatch(), NURBSFiniteElement::Weights(), and weights.
Referenced by FiniteElementSpace::GetBE().
void NURBSExtension::LoadFE (int i, const FiniteElement * FE)
Definition at line 2121 of file nurbs.cpp.
References el_dof, el_to_IJK, el_to_patch, NURBSFiniteElement::GetElement(), NURBSFiniteElement::GetPatch(), GetPatchKnotVectors(), Table::GetRow(), Array2D< T >::GetRow(), Vector::GetSubVector(), NURBSFiniteElement::KnotVectors(), NURBSFiniteElement::SetElement(), NURBSFiniteElement::SetIJK(), NURBSFiniteElement::SetPatch(), NURBSFiniteElement::Weights(), and weights.
Referenced by FiniteElementSpace::GetFE().
void NURBSExtension::MergeGridFunctions (GridFunction * gf_array[], int num_pieces, GridFunction & merged)
Definition at line 1410 of file nurbs.cpp.
References GridFunction::FESpace(), GetElementLocalToGlobal(), FiniteElementSpace::GetElementVDofs(), FiniteElementSpace::GetMesh(), GetNE(), Vector::GetSubVector(), Mesh::NURBSext, and Vector::SetSubVector().
Referenced by GridFunction::GridFunction().
void NURBSExtension::MergeWeights (Mesh * mesh_array[], int num_pieces) [protected]
Definition at line 1387 of file nurbs.cpp.
References el_dof, GetElementLocalToGlobal(), GetNE(), Table::GetRow(), Mesh::NURBSext, Table::RowSize(), and weights.
Referenced by NURBSExtension().
void NURBSExtension::Print (ostream & out) const
Definition at line 1256 of file nurbs.cpp.
References activeElem, edge_to_knot, knotVectors, NumOfActiveElems, NumOfElements, NumOfKnotVectors, patchTopo, Vector::Print(), Array< T >::Print(), Mesh::PrintTopo(), and weights.
Referenced by Mesh::Print().
void NURBSExtension::PrintCharacteristics (ostream & out)
Definition at line 1277 of file nurbs.cpp.
References Dimension(), GetGNBE(), GetGNE(), GetGNV(), GetNBE(), GetNBP(), GetNDof(), GetNE(), GetNKV(), GetNP(), GetNTotalDof(), GetNV(), GetOrder(), knotVectors, NumOfKnotVectors, and Array< T >::Print().
void NURBSExtension::Set2DSolutionVector (Vector & Nodes) [protected]
Definition at line 2341 of file nurbs.cpp.
References GetNDof(), GetNP(), patches, NURBSPatchMap::SetPatchDofMap(), Vector::SetSize(), and weights.
Referenced by SetSolutionVector().
void NURBSExtension::Set3DSolutionVector (Vector & Nodes) [protected]
Definition at line 2368 of file nurbs.cpp.
References GetNDof(), GetNP(), patches, NURBSPatchMap::SetPatchDofMap(), Vector::SetSize(), and weights.
Referenced by SetSolutionVector().
void NURBSExtension::SetCoordsFromPatches (Vector & Nodes)
Definition at line 2170 of file nurbs.cpp.
References patches, Array< T >::SetSize(), SetSolutionVector(), and Array< T >::Size().
Referenced by Mesh::Load(), and Mesh::UpdateNURBS().
void NURBSExtension::SetKnotsFromPatches ()
Definition at line 2178 of file nurbs.cpp.
References activeElem, CountBdrElements(), CountElements(), GenerateActiveBdrElems(), GenerateActiveVertices(), GenerateBdrElementDofTable(), GenerateElementDofTable(), GenerateOffsets(), GetOrder(), GetPatchKnotVectors(), knotVectors, mfem_error(), NumOfActiveElems, NumOfElements, NumOfKnotVectors, Order, patches, Array< T >::SetSize(), and Array< T >::Size().
Referenced by Mesh::UpdateNURBS().
void NURBSExtension::SetSolutionVector (Vector & Nodes) [protected]
Definition at line 2329 of file nurbs.cpp.
References Dimension(), Set2DSolutionVector(), and Set3DSolutionVector().
Referenced by SetCoordsFromPatches().
void NURBSExtension::UniformRefinement ()
Definition at line 2225 of file nurbs.cpp.
References patches, and Array< T >::Size().
Referenced by Mesh::NURBSUniformRefinement().
Friends And Related Function Documentation
friend class NURBSPatchMap [friend]
Definition at line 141 of file nurbs.hpp.
Member Data Documentation
Array<bool> NURBSExtension::activeBdrElem [protected]
Definition at line 154 of file nurbs.hpp.
Referenced by Generate2DBdrElementDofTable(), Generate3DBdrElementDofTable(), GenerateActiveBdrElems(), Get2DBdrElementTopo(), Get3DBdrElementTopo(), and NURBSExtension().
Array<int> NURBSExtension::activeDof [protected]
Definition at line 155 of file nurbs.hpp.
Referenced by Generate2DElementDofTable(), Generate3DElementDofTable(), GenerateBdrElementDofTable(), and GenerateElementDofTable().
Array<bool> NURBSExtension::activeElem [protected]
Definition at line 153 of file nurbs.hpp.
Referenced by Generate2DElementDofTable(), Generate3DElementDofTable(), GenerateActiveVertices(), Get2DElementTopo(), Get3DElementTopo(), GetElementLocalToGlobal(), NURBSExtension(), Print(), and SetKnotsFromPatches().
Array<int> NURBSExtension::activeVert [protected]
Definition at line 152 of file nurbs.hpp.
Referenced by GenerateActiveVertices(), Get2DBdrElementTopo(), Get2DElementTopo(), Get3DBdrElementTopo(), Get3DElementTopo(), GetVertexLocalToGlobal(), and NURBSExtension().
Table * NURBSExtension::bel_dof [protected]
Definition at line 175 of file nurbs.hpp.
Referenced by ConvertToPatches(), Generate2DBdrElementDofTable(), Generate3DBdrElementDofTable(), GenerateBdrElementDofTable(), GetBdrElementDofTable(), LoadBE(), and ~NURBSExtension().
Array2D<int> NURBSExtension::bel_to_IJK [protected]
Definition at line 180 of file nurbs.hpp.
Referenced by Generate2DBdrElementDofTable(), Generate3DBdrElementDofTable(), and LoadBE().
Array<int> NURBSExtension::bel_to_patch [protected]
Definition at line 178 of file nurbs.hpp.
Referenced by Generate2DBdrElementDofTable(), Generate3DBdrElementDofTable(), and LoadBE().
Array<int> NURBSExtension::e_meshOffsets [protected]
Definition at line 165 of file nurbs.hpp.
Referenced by GenerateOffsets(), NURBSPatchMap::SetBdrPatchVertexMap(), and NURBSPatchMap::SetPatchVertexMap().
Array<int> NURBSExtension::e_spaceOffsets [protected]
Definition at line 171 of file nurbs.hpp.
Referenced by GenerateOffsets(), NURBSPatchMap::SetBdrPatchDofMap(), and NURBSPatchMap::SetPatchDofMap().
Array<int> NURBSExtension::edge_to_knot [protected]
Definition at line 159 of file nurbs.hpp.
Referenced by CheckBdrPatches(), CheckPatches(), KnotInd(), KnotVec(), NURBSExtension(), and Print().
Table* NURBSExtension::el_dof [protected]
Definition at line 175 of file nurbs.hpp.
Referenced by ConvertToPatches(), Generate2DElementDofTable(), Generate3DElementDofTable(), GenerateElementDofTable(), GetElementDofTable(), LoadFE(), MergeWeights(), and ~NURBSExtension().
Array2D<int> NURBSExtension::el_to_IJK [protected]
Definition at line 179 of file nurbs.hpp.
Referenced by Generate2DElementDofTable(), Generate3DElementDofTable(), and LoadFE().
Array<int> NURBSExtension::el_to_patch [protected]
Definition at line 177 of file nurbs.hpp.
Referenced by Generate2DElementDofTable(), Generate3DElementDofTable(), and LoadFE().
Array<int> NURBSExtension::f_meshOffsets [protected]
Definition at line 166 of file nurbs.hpp.
Referenced by GenerateOffsets(), NURBSPatchMap::SetBdrPatchVertexMap(), and NURBSPatchMap::SetPatchVertexMap().
Array<int> NURBSExtension::f_spaceOffsets [protected]
Definition at line 172 of file nurbs.hpp.
Referenced by GenerateOffsets(), NURBSPatchMap::SetBdrPatchDofMap(), and NURBSPatchMap::SetPatchDofMap().
Array<KnotVector *> NURBSExtension::knotVectors [protected]
Definition at line 160 of file nurbs.hpp.
Referenced by GetKnotVector(), KnotVec(), NURBSExtension(), Print(), PrintCharacteristics(), SetKnotsFromPatches(), and ~NURBSExtension().
int NURBSExtension::NumOfActiveBdrElems [protected]
Definition at line 149 of file nurbs.hpp.
Referenced by Generate2DBdrElementDofTable(), Generate3DBdrElementDofTable(), GenerateActiveBdrElems(), GetNBE(), and NURBSExtension().
int NURBSExtension::NumOfActiveDofs [protected]
Definition at line 150 of file nurbs.hpp.
Referenced by GenerateElementDofTable(), and GetNDof().
int NURBSExtension::NumOfActiveElems [protected]
Definition at line 149 of file nurbs.hpp.
Referenced by Generate2DElementDofTable(), Generate3DElementDofTable(), GetNE(), NURBSExtension(), Print(), and SetKnotsFromPatches().
int NURBSExtension::NumOfActiveVertices [protected]
Definition at line 149 of file nurbs.hpp.
Referenced by GenerateActiveVertices(), GetNV(), and NURBSExtension().
int NURBSExtension::NumOfBdrElements [protected]
Definition at line 147 of file nurbs.hpp.
Referenced by CountBdrElements(), GetGNBE(), and NURBSExtension().
int NURBSExtension::NumOfDofs [protected]
Definition at line 147 of file nurbs.hpp.
Referenced by GenerateOffsets(), and GetNTotalDof().
int NURBSExtension::NumOfElements [protected]
Definition at line 147 of file nurbs.hpp.
Referenced by CountElements(), GetGNE(), NURBSExtension(), Print(), and SetKnotsFromPatches().
int NURBSExtension::NumOfKnotVectors [protected]
Definition at line 145 of file nurbs.hpp.
Referenced by GetNKV(), NURBSExtension(), Print(), PrintCharacteristics(), and SetKnotsFromPatches().
int NURBSExtension::NumOfVertices [protected]
Definition at line 147 of file nurbs.hpp.
Referenced by GenerateOffsets(), and GetGNV().
int NURBSExtension::Order [protected]
Definition at line 144 of file nurbs.hpp.
Referenced by Generate2DBdrElementDofTable(), Generate2DElementDofTable(), Generate3DBdrElementDofTable(), Generate3DElementDofTable(), GetOrder(), NURBSExtension(), and SetKnotsFromPatches().
int NURBSExtension::own_topo [protected]
Definition at line 158 of file nurbs.hpp.
Referenced by NURBSExtension(), and ~NURBSExtension().
Array<int> NURBSExtension::p_meshOffsets [protected]
Definition at line 167 of file nurbs.hpp.
Referenced by GenerateOffsets(), and NURBSPatchMap::SetPatchVertexMap().
Array<int> NURBSExtension::p_spaceOffsets [protected]
Definition at line 173 of file nurbs.hpp.
Referenced by GenerateOffsets(), and NURBSPatchMap::SetPatchDofMap().
Array<NURBSPatch *> NURBSExtension::patches [protected]
Definition at line 182 of file nurbs.hpp.
Referenced by ConvertToPatches(), DegreeElevate(), Get2DPatchNets(), Get3DPatchNets(), HavePatches(), KnotInsert(), NURBSExtension(), Set2DSolutionVector(), Set3DSolutionVector(), SetCoordsFromPatches(), SetKnotsFromPatches(), UniformRefinement(), and ~NURBSExtension().
Mesh* NURBSExtension::patchTopo [protected]
Definition at line 157 of file nurbs.hpp.
Referenced by CheckBdrPatches(), CheckPatches(), Dimension(), GenerateOffsets(), Get2DBdrElementTopo(), Get2DElementTopo(), Get3DBdrElementTopo(), Get3DElementTopo(), NURBSPatchMap::GetBdrPatchKnotVectors(), GetBdrPatchKnotVectors(), GetNBP(), GetNP(), NURBSPatchMap::GetPatchKnotVectors(), GetPatchKnotVectors(), KnotInsert(), NURBSExtension(), Print(), and ~NURBSExtension().
Array<int> NURBSExtension::v_meshOffsets [protected]
Definition at line 164 of file nurbs.hpp.
Referenced by GenerateOffsets(), NURBSPatchMap::SetBdrPatchVertexMap(), and NURBSPatchMap::SetPatchVertexMap().
Array<int> NURBSExtension::v_spaceOffsets [protected]
Definition at line 170 of file nurbs.hpp.
Referenced by GenerateOffsets(), NURBSPatchMap::SetBdrPatchDofMap(), and NURBSPatchMap::SetPatchDofMap().
Vector NURBSExtension::weights [protected]
Definition at line 161 of file nurbs.hpp.
Referenced by Get2DPatchNets(), Get3DPatchNets(), GetWeights(), LoadBE(), LoadFE(), MergeWeights(), NURBSExtension(), Print(), Set2DSolutionVector(), and Set3DSolutionVector().
The documentation for this class was generated from the following files:
nurbs.hpp
nurbs.cpp