MFEM: RefinedElement Class Reference
RefinedElement Class Reference
#include <element.hpp>
Public Types
enum { COARSE = 0, FINE = 1 }
Public Member Functions
RefinedElement ()
RefinedElement (Element *ce)
void SetCoarseElem (Element *ce)
Element * IAm ()
const Element * IAm () const
virtual void SetVertices (const int *ind)
Set the indices the element according to the input.
virtual void GetVertices (Array< int > &v) const
Returns element's vertices.
virtual int * GetVertices ()
virtual int GetNVertices () const
virtual int GetNEdges () const
virtual const int * GetEdgeVertices (int ei) const
virtual void MarkEdge (DenseMatrix &pmat)
Mark the longest edge by assuming/changing the order of the vertices.
virtual void MarkEdge (const DSTable &v_to_v, const int *length)
Mark the longest edge by assuming/changing the order of the vertices.
virtual int NeedRefinement (DSTable &v_to_v, int *middle) const
Return 1 if the element needs refinement in order to get conforming mesh.
Public Attributes
Element * CoarseElem
Element * FirstChild
Static Public Attributes
static int State = RefinedElement::FINE
Detailed Description
Definition at line 74 of file element.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator:
COARSE
FINE
Definition at line 78 of file element.hpp.
Constructor & Destructor Documentation
RefinedElement::RefinedElement () [inline]
Definition at line 85 of file element.hpp.
RefinedElement::RefinedElement (Element * ce) [inline]
Definition at line 87 of file element.hpp.
References Element::attribute, CoarseElem, and Element::GetAttribute().
Member Function Documentation
virtual const int* RefinedElement::GetEdgeVertices (int ei) const [inline, virtual]
Implements Element.
Definition at line 120 of file element.hpp.
References GetEdgeVertices(), and IAm().
Referenced by GetEdgeVertices().
virtual int RefinedElement::GetNEdges () const [inline, virtual]
Implements Element.
Definition at line 118 of file element.hpp.
References GetNEdges(), and IAm().
Referenced by GetNEdges().
virtual int RefinedElement::GetNVertices () const [inline, virtual]
Implements Element.
Definition at line 116 of file element.hpp.
References Element::GetNVertices(), and IAm().
virtual void RefinedElement::GetVertices (Array< int > & v) const [inline, virtual]
Returns element's vertices.
Implements Element.
Definition at line 112 of file element.hpp.
References Element::GetVertices(), and IAm().
virtual int* RefinedElement::GetVertices () [inline, virtual]
Implements Element.
Definition at line 114 of file element.hpp.
References Element::GetVertices(), and IAm().
Element* RefinedElement::IAm () [inline]
Definition at line 99 of file element.hpp.
References COARSE, CoarseElem, FirstChild, and State.
Referenced by GetEdgeVertices(), GetNEdges(), GetNVertices(), GetVertices(), MarkEdge(), NeedRefinement(), and SetVertices().
const Element* RefinedElement::IAm () const [inline]
Definition at line 104 of file element.hpp.
References COARSE, CoarseElem, FirstChild, and State.
virtual void RefinedElement::MarkEdge (const DSTable & v_to_v, const int * length) [inline, virtual]
Mark the longest edge by assuming/changing the order of the vertices.
Reimplemented from Element.
Definition at line 125 of file element.hpp.
References IAm(), and Element::MarkEdge().
virtual void RefinedElement::MarkEdge (DenseMatrix & pmat) [inline, virtual]
Mark the longest edge by assuming/changing the order of the vertices.
Reimplemented from Element.
Definition at line 123 of file element.hpp.
References IAm(), and Element::MarkEdge().
virtual int RefinedElement::NeedRefinement (DSTable & v_to_v, int * middle) const [inline, virtual]
Return 1 if the element needs refinement in order to get conforming mesh.
Reimplemented from Element.
Definition at line 128 of file element.hpp.
References IAm(), and Element::NeedRefinement().
void RefinedElement::SetCoarseElem (Element * ce) [inline]
Definition at line 92 of file element.hpp.
References Element::attribute, Element::base_geom, CoarseElem, Element::GetAttribute(), and Element::GetGeometryType().
Referenced by Mesh::Bisection(), Mesh::LocalRefinement(), and Mesh::QuadUniformRefinement().
virtual void RefinedElement::SetVertices (const int * ind) [inline, virtual]
Set the indices the element according to the input.
Reimplemented from Element.
Definition at line 110 of file element.hpp.
References IAm(), and Element::SetVertices().
Member Data Documentation
Element* RefinedElement::CoarseElem
Definition at line 83 of file element.hpp.
Referenced by Mesh::GetFineElem(), Mesh::GetFineElemTrans(), IAm(), RefinedElement(), SetCoarseElem(), and Mesh::SetState().
Element * RefinedElement::FirstChild
Definition at line 83 of file element.hpp.
Referenced by Mesh::Bisection(), Mesh::GetFineElem(), Mesh::GetFineElemPath(), Mesh::GetFineElemTrans(), Mesh::GetNumFineElems(), Mesh::HexUniformRefinement(), IAm(), Mesh::LocalRefinement(), Mesh::QuadUniformRefinement(), Mesh::SetState(), and Mesh::UniformRefinement().
int RefinedElement::State = RefinedElement::FINE [static]
Definition at line 81 of file element.hpp.
Referenced by Mesh::HexUniformRefinement(), IAm(), Mesh::LocalRefinement(), Mesh::QuadUniformRefinement(), and Mesh::SetState().
The documentation for this class was generated from the following files:
element.hpp
point.cpp