MFEM: VectorDivergenceIntegrator Class Reference
VectorDivergenceIntegrator Class Reference
#include <bilininteg.hpp>
Public Member Functions
VectorDivergenceIntegrator ()
VectorDivergenceIntegrator (Coefficient *_q)
VectorDivergenceIntegrator (Coefficient &q)
virtual void AssembleElementMatrix2 (const FiniteElement &trial_fe, const FiniteElement &test_fe, ElementTransformation &Trans, DenseMatrix &elmat)
Private Attributes
Coefficient * Q
Vector shape
Vector divshape
DenseMatrix dshape
DenseMatrix gshape
DenseMatrix Jadj
Detailed Description
Integrator for (Q div u, p) where u=(v1,...,vn) and all vi are in the same scalar FE space; p is also in a (different) scalar FE space.
Definition at line 331 of file bilininteg.hpp.
Constructor & Destructor Documentation
VectorDivergenceIntegrator::VectorDivergenceIntegrator () [inline]
Definition at line 343 of file bilininteg.hpp.
References Q.
VectorDivergenceIntegrator::VectorDivergenceIntegrator (Coefficient * _q) [inline]
Definition at line 344 of file bilininteg.hpp.
References Q.
VectorDivergenceIntegrator::VectorDivergenceIntegrator (Coefficient & q) [inline]
Definition at line 345 of file bilininteg.hpp.
References Q.
Member Function Documentation
void VectorDivergenceIntegrator::AssembleElementMatrix2 (const FiniteElement & trial_fe, const FiniteElement & test_fe, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Compute the local matrix representation of a bilinear form a(u,v) defined on different trial (given by u) and test (given by v) spaces. The rows in the local matrix correspond to the test dofs and the columns -- to the trial dofs.
Reimplemented from BilinearFormIntegrator.
Definition at line 684 of file bilininteg.cpp.
References AddMultVWt(), CalcAdjugate(), FiniteElement::CalcDShape(), FiniteElement::CalcShape(), divshape, dshape, IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), FiniteElement::GetOrder(), DenseMatrix::GradToDiv(), gshape, IntegrationRule::IntPoint(), IntRules, ElementTransformation::Jacobian(), Jadj, Mult(), ElementTransformation::OrderGrad(), Q, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), shape, and IntegrationPoint::weight.
Member Data Documentation
Vector VectorDivergenceIntegrator::divshape [private]
Definition at line 337 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
DenseMatrix VectorDivergenceIntegrator::dshape [private]
Definition at line 338 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
DenseMatrix VectorDivergenceIntegrator::gshape [private]
Definition at line 339 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
DenseMatrix VectorDivergenceIntegrator::Jadj [private]
Definition at line 340 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
Coefficient* VectorDivergenceIntegrator::Q [private]
Definition at line 334 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2(), and VectorDivergenceIntegrator().
Vector VectorDivergenceIntegrator::shape [private]
Definition at line 336 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp