MFEM: VectorDiffusionIntegrator Class Reference
VectorDiffusionIntegrator Class Reference
#include <bilininteg.hpp>
Public Member Functions
VectorDiffusionIntegrator ()
VectorDiffusionIntegrator (Coefficient &q)
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
Private Attributes
Coefficient * Q
DenseMatrix Jinv
DenseMatrix dshape
DenseMatrix gshape
DenseMatrix pelmat
Detailed Description
Integrator for (Q grad u, grad v) = sum_i (Q grad u_i, grad v_i) for FE spaces defined by 'dim' copies of a scalar FE space.
Definition at line 332 of file bilininteg.hpp.
Constructor & Destructor Documentation
VectorDiffusionIntegrator::VectorDiffusionIntegrator () [inline]
Definition at line 343 of file bilininteg.hpp.
References Q.
VectorDiffusionIntegrator::VectorDiffusionIntegrator (Coefficient & q) [inline]
Definition at line 344 of file bilininteg.hpp.
References Q.
Member Function Documentation
void VectorDiffusionIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 681 of file bilininteg.cpp.
References FiniteElement::CalcDShape(), CalcInverse(), dshape, IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), gshape, IntegrationRule::IntPoint(), IntRules, ElementTransformation::Jacobian(), Jinv, Mult(), MultAAt(), norm(), ElementTransformation::OrderGrad(), pelmat, Q, RefinedIntRules, FunctionSpace::rQk, ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), FiniteElement::Space(), ElementTransformation::Weight(), and IntegrationPoint::weight.
Member Data Documentation
DenseMatrix VectorDiffusionIntegrator::dshape [private]
Definition at line 338 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix VectorDiffusionIntegrator::gshape [private]
Definition at line 339 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix VectorDiffusionIntegrator::Jinv [private]
Definition at line 337 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
DenseMatrix VectorDiffusionIntegrator::pelmat [private]
Definition at line 340 of file bilininteg.hpp.
Referenced by AssembleElementMatrix().
Coefficient* VectorDiffusionIntegrator::Q [private]
Definition at line 335 of file bilininteg.hpp.
Referenced by AssembleElementMatrix(), and VectorDiffusionIntegrator().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp