MFEM: Point Class Reference
Point Class Reference
Data type point element.
#include <point.hpp>
Public Member Functions
Point ()
Point (const int *ind, int attr=-1)
Constructs triangle by specifying the indices and the attribute.
virtual int GetType () const
Return element's type.
virtual void GetVertices (Array< int > &v) const
Returns the indices of the element's vertices.
virtual int * GetVertices ()
virtual int GetNVertices () const
virtual int GetNEdges () const
virtual const int * GetEdgeVertices (int ei) const
virtual Element * Duplicate (Mesh *m) const
virtual ~Point ()
Protected Attributes
int indices [1]
Detailed Description
Data type point element.
Definition at line 16 of file point.hpp.
Constructor & Destructor Documentation
Point::Point () [inline]
Definition at line 23 of file point.hpp.
Referenced by Duplicate().
Point::Point (const int * ind, int attr = -1)
Constructs triangle by specifying the indices and the attribute.
Definition at line 15 of file point.cpp.
References Element::attribute, and indices.
virtual Point::~Point () [inline, virtual]
Definition at line 45 of file point.hpp.
Member Function Documentation
virtual Element* Point::Duplicate (Mesh * m) const [inline, virtual]
Implements Element.
Definition at line 42 of file point.hpp.
References Element::attribute, indices, and Point().
virtual const int* Point::GetEdgeVertices (int ei) const [inline, virtual]
Implements Element.
Definition at line 40 of file point.hpp.
virtual int Point::GetNEdges () const [inline, virtual]
Implements Element.
Definition at line 38 of file point.hpp.
virtual int Point::GetNVertices () const [inline, virtual]
Implements Element.
Definition at line 36 of file point.hpp.
virtual int Point::GetType () const [inline, virtual]
Return element's type.
Implements Element.
Definition at line 29 of file point.hpp.
References Element::POINT.
virtual int* Point::GetVertices () [inline, virtual]
Implements Element.
Definition at line 34 of file point.hpp.
References indices.
void Point::GetVertices (Array< int > & v) const [virtual]
Returns the indices of the element's vertices.
Implements Element.
Definition at line 20 of file point.cpp.
References indices, and Array< T >::SetSize().
Member Data Documentation
int Point::indices[1] [protected]
Definition at line 19 of file point.hpp.
Referenced by Duplicate(), GetVertices(), and Point().
The documentation for this class was generated from the following files:
point.hpp
point.cpp