MFEM: VectorFECurlIntegrator Class Reference
VectorFECurlIntegrator Class Reference
Integrator for (curl u, v) for Nedelec and RT elements.
#include <bilininteg.hpp>
Public Member Functions
VectorFECurlIntegrator ()
VectorFECurlIntegrator (Coefficient &q)
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
virtual void AssembleElementMatrix2 (const FiniteElement &trial_fe, const FiniteElement &test_fe, ElementTransformation &Trans, DenseMatrix &elmat)
Private Attributes
Coefficient * Q
DenseMatrix curlshapeTrial
DenseMatrix vshapeTest
DenseMatrix curlshapeTrial_dFT
Detailed Description
Integrator for (curl u, v) for Nedelec and RT elements.
Definition at line 236 of file bilininteg.hpp.
Constructor & Destructor Documentation
VectorFECurlIntegrator::VectorFECurlIntegrator () [inline]
Definition at line 246 of file bilininteg.hpp.
References Q.
VectorFECurlIntegrator::VectorFECurlIntegrator (Coefficient & q) [inline]
Definition at line 247 of file bilininteg.hpp.
References Q.
Member Function Documentation
virtual void VectorFECurlIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [inline, virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 248 of file bilininteg.hpp.
void VectorFECurlIntegrator::AssembleElementMatrix2 (const FiniteElement & trial_fe, const FiniteElement & test_fe, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Compute the local matrix representation of a bilinear form a(u,v) defined on different trial (given by u) and test (given by v) spaces. The rows in the local matrix correspond to the test dofs and the columns -- to the trial dofs.
Reimplemented from BilinearFormIntegrator.
Definition at line 443 of file bilininteg.cpp.
References AddMultABt(), FiniteElement::CalcCurlShape(), FiniteElement::CalcVShape(), curlshapeTrial, curlshapeTrial_dFT, Coefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDim(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, ElementTransformation::Jacobian(), MultABt(), Q, ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), vshapeTest, and IntegrationPoint::weight.
Member Data Documentation
DenseMatrix VectorFECurlIntegrator::curlshapeTrial [private]
Definition at line 241 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
DenseMatrix VectorFECurlIntegrator::curlshapeTrial_dFT [private]
Definition at line 243 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
Coefficient* VectorFECurlIntegrator::Q [private]
Definition at line 239 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2(), and VectorFECurlIntegrator().
DenseMatrix VectorFECurlIntegrator::vshapeTest [private]
Definition at line 242 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp