MFEM: BilinearFormIntegrator Class Reference
BilinearFormIntegrator Class Reference
Abstract base class BilinearFormIntegrator.
#include <bilininteg.hpp>
Public Member Functions
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
virtual void AssembleElementMatrix2 (const FiniteElement &trial_fe, const FiniteElement &test_fe, ElementTransformation &Trans, DenseMatrix &elmat)
virtual void AssembleFaceMatrix (const FiniteElement &el1, const FiniteElement &el2, FaceElementTransformations &Trans, DenseMatrix &elmat)
virtual void ComputeElementFlux (const FiniteElement &el, ElementTransformation &Trans, Vector &u, const FiniteElement &fluxelem, Vector &flux, int wcoef=1)
virtual double ComputeFluxEnergy (const FiniteElement &fluxelem, ElementTransformation &Trans, Vector &flux)
virtual ~BilinearFormIntegrator ()
Detailed Description
Abstract base class BilinearFormIntegrator.
Definition at line 16 of file bilininteg.hpp.
Constructor & Destructor Documentation
virtual BilinearFormIntegrator::~BilinearFormIntegrator () [inline, virtual]
Definition at line 43 of file bilininteg.hpp.
Member Function Documentation
void BilinearFormIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented in ElasticityIntegrator, VectorDiffusionIntegrator, DivDivIntegrator, VectorFEMassIntegrator, CurlCurlIntegrator, DerivativeIntegrator, VectorFECurlIntegrator, VectorFEDivergenceIntegrator, VectorMassIntegrator, ConvectionIntegrator, MassIntegrator, DiffusionIntegrator, LumpedIntegrator, and TransposeIntegrator.
Definition at line 17 of file bilininteg.cpp.
References mfem_error().
void BilinearFormIntegrator::AssembleElementMatrix2 (const FiniteElement & trial_fe, const FiniteElement & test_fe, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Compute the local matrix representation of a bilinear form a(u,v) defined on different trial (given by u) and test (given by v) spaces. The rows in the local matrix correspond to the test dofs and the columns -- to the trial dofs.
Reimplemented in DivergenceInterpolator, CurlInterpolator, IdentityInterpolator, GradientInterpolator, VectorDivergenceIntegrator, VectorFEMassIntegrator, DerivativeIntegrator, VectorFECurlIntegrator, VectorFEDivergenceIntegrator, MassIntegrator, and TransposeIntegrator.
Definition at line 25 of file bilininteg.cpp.
References mfem_error().
void BilinearFormIntegrator::AssembleFaceMatrix (const FiniteElement & el1, const FiniteElement & el2, FaceElementTransformations & Trans, DenseMatrix & elmat) [virtual]
Definition at line 33 of file bilininteg.cpp.
References mfem_error().
virtual void BilinearFormIntegrator::ComputeElementFlux (const FiniteElement & el, ElementTransformation & Trans, Vector & u, const FiniteElement & fluxelem, Vector & flux, int wcoef = 1) [inline, virtual]
Reimplemented in DiffusionIntegrator.
Definition at line 35 of file bilininteg.hpp.
Referenced by ComputeFlux(), and ZZErrorEstimator().
virtual double BilinearFormIntegrator::ComputeFluxEnergy (const FiniteElement & fluxelem, ElementTransformation & Trans, Vector & flux) [inline, virtual]
Reimplemented in DiffusionIntegrator.
Definition at line 40 of file bilininteg.hpp.
Referenced by ZZErrorEstimator().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp