MFEM: GeometryRefiner Class Reference
GeometryRefiner Class Reference
#include <geom.hpp>
Public Member Functions
GeometryRefiner ()
void SetType (const int t)
RefinedGeometry * Refine (int Geom, int Times, int ETimes=1)
const IntegrationRule * RefineInterior (int Geom, int Times)
~GeometryRefiner ()
Private Attributes
int type
RefinedGeometry * RGeom [Geometry::NumGeom]
IntegrationRule * IntPts [Geometry::NumGeom]
Detailed Description
Definition at line 68 of file geom.hpp.
Constructor & Destructor Documentation
GeometryRefiner::GeometryRefiner ()
Definition at line 264 of file geom.cpp.
References IntPts, Geometry::NumGeom, RGeom, and type.
GeometryRefiner::~GeometryRefiner ()
Definition at line 274 of file geom.cpp.
References IntPts, Geometry::NumGeom, and RGeom.
Member Function Documentation
RefinedGeometry * GeometryRefiner::Refine (int Geom, int Times, int ETimes = 1)
Definition at line 283 of file geom.cpp.
References Poly_1D::ClosedPoints(), Geometry::CUBE, RefinedGeometry::ETimes, IntegrationRule::IntPoint(), mfem_error(), poly1d, RefinedGeometry::RefEdges, RefinedGeometry::RefGeoms, RefinedGeometry::RefPts, RGeom, Geometry::SEGMENT, Geometry::SQUARE, Geometry::TETRAHEDRON, RefinedGeometry::Times, Geometry::TRIANGLE, type, IntegrationPoint::x, IntegrationPoint::y, and IntegrationPoint::z.
Referenced by Mesh::PrintVTK(), GridFunction::SaveSTL(), and GridFunction::SaveVTK().
const IntegrationRule * GeometryRefiner::RefineInterior (int Geom, int Times)
Definition at line 628 of file geom.cpp.
References IntegrationRule::IntPoint(), IntPts, mfem_error(), Geometry::SEGMENT, Geometry::SQUARE, Geometry::TRIANGLE, IntegrationPoint::x, IntegrationPoint::y, and IntegrationPoint::z.
void GeometryRefiner::SetType (const int t) [inline]
Definition at line 77 of file geom.hpp.
References type.
Member Data Documentation
IntegrationRule* GeometryRefiner::IntPts[Geometry::NumGeom] [private]
Definition at line 73 of file geom.hpp.
Referenced by GeometryRefiner(), RefineInterior(), and ~GeometryRefiner().
RefinedGeometry* GeometryRefiner::RGeom[Geometry::NumGeom] [private]
Definition at line 72 of file geom.hpp.
Referenced by GeometryRefiner(), Refine(), and ~GeometryRefiner().
int GeometryRefiner::type [private]
Definition at line 71 of file geom.hpp.
Referenced by GeometryRefiner(), Refine(), and SetType().
The documentation for this class was generated from the following files:
geom.hpp
geom.cpp