MFEM: NURBSFiniteElement Class Reference
NURBSFiniteElement Class Reference
#include <fe.hpp>
Public Member Functions
NURBSFiniteElement (int D, int G, int Do, int O, int F)
void Reset () const
void SetIJK (int *IJK) const
int GetPatch () const
void SetPatch (int p) const
int GetElement () const
void SetElement (int e) const
Array< KnotVector * > & KnotVectors () const
Vector & Weights () const
Protected Attributes
Array< KnotVector * > kv
int * ijk
int patch
int elem
Vector weights
Detailed Description
Definition at line 1705 of file fe.hpp.
Constructor & Destructor Documentation
NURBSFiniteElement::NURBSFiniteElement (int D, int G, int Do, int O, int F) [inline]
Definition at line 1713 of file fe.hpp.
References FiniteElement::Dim, FiniteElement::Dof, elem, ijk, kv, patch, Vector::SetSize(), Array< T >::SetSize(), and weights.
Member Function Documentation
int NURBSFiniteElement::GetElement () const [inline]
Definition at line 1727 of file fe.hpp.
References elem.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
int NURBSFiniteElement::GetPatch () const [inline]
Definition at line 1725 of file fe.hpp.
References patch.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
Array<KnotVector*>& NURBSFiniteElement::KnotVectors () const [inline]
Definition at line 1729 of file fe.hpp.
References kv.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
void NURBSFiniteElement::Reset () const [inline]
Definition at line 1723 of file fe.hpp.
References elem, and patch.
Referenced by NURBSFECollection::Reset().
void NURBSFiniteElement::SetElement (int e) const [inline]
Definition at line 1728 of file fe.hpp.
References elem.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
void NURBSFiniteElement::SetIJK (int * IJK) const [inline]
Definition at line 1724 of file fe.hpp.
References ijk.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
void NURBSFiniteElement::SetPatch (int p) const [inline]
Definition at line 1726 of file fe.hpp.
References patch.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
Vector& NURBSFiniteElement::Weights () const [inline]
Definition at line 1730 of file fe.hpp.
References weights.
Referenced by NURBSExtension::LoadBE(), and NURBSExtension::LoadFE().
Member Data Documentation
int NURBSFiniteElement::elem [mutable, protected]
Definition at line 1709 of file fe.hpp.
Referenced by GetElement(), NURBSFiniteElement(), Reset(), and SetElement().
int* NURBSFiniteElement::ijk [mutable, protected]
Definition at line 1709 of file fe.hpp.
Referenced by NURBS1DFiniteElement::CalcDShape(), NURBS2DFiniteElement::CalcDShape(), NURBS3DFiniteElement::CalcDShape(), NURBS1DFiniteElement::CalcShape(), NURBS2DFiniteElement::CalcShape(), NURBS3DFiniteElement::CalcShape(), NURBSFiniteElement(), and SetIJK().
Array<KnotVector*> NURBSFiniteElement::kv [mutable, protected]
Definition at line 1708 of file fe.hpp.
Referenced by NURBS1DFiniteElement::CalcDShape(), NURBS2DFiniteElement::CalcDShape(), NURBS3DFiniteElement::CalcDShape(), NURBS1DFiniteElement::CalcShape(), NURBS2DFiniteElement::CalcShape(), NURBS3DFiniteElement::CalcShape(), KnotVectors(), and NURBSFiniteElement().
int NURBSFiniteElement::patch [mutable, protected]
Definition at line 1709 of file fe.hpp.
Referenced by GetPatch(), NURBSFiniteElement(), Reset(), and SetPatch().
Vector NURBSFiniteElement::weights [mutable, protected]
Definition at line 1710 of file fe.hpp.
Referenced by NURBS1DFiniteElement::CalcDShape(), NURBS2DFiniteElement::CalcDShape(), NURBS3DFiniteElement::CalcDShape(), NURBS1DFiniteElement::CalcShape(), NURBS2DFiniteElement::CalcShape(), NURBS3DFiniteElement::CalcShape(), NURBSFiniteElement(), and Weights().
The documentation for this class was generated from the following file:
fe.hpp