MFEM: VectorFEDivergenceIntegrator Class Reference
VectorFEDivergenceIntegrator Class Reference
#include <bilininteg.hpp>
Public Member Functions
VectorFEDivergenceIntegrator ()
VectorFEDivergenceIntegrator (Coefficient &q)
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
Given a particular Finite Element computes the element matrix elmat.
virtual void AssembleElementMatrix2 (const FiniteElement &trial_fe, const FiniteElement &test_fe, ElementTransformation &Trans, DenseMatrix &elmat)
Private Attributes
Coefficient * Q
Vector divshape
Vector shape
Detailed Description
Class for integrating (div u, p) where u is a vector field given by VectorFiniteElement through Piola transformation (for RT elements); p is scalar function given by FiniteElement through standard transformation. Here, u is the trial function and p is the test function. Note: the element matrix returned by AssembleElementMatrix2 does NOT depend on the ElementTransformation Trans.
Definition at line 215 of file bilininteg.hpp.
Constructor & Destructor Documentation
VectorFEDivergenceIntegrator::VectorFEDivergenceIntegrator () [inline]
Definition at line 223 of file bilininteg.hpp.
References Q.
VectorFEDivergenceIntegrator::VectorFEDivergenceIntegrator (Coefficient & q) [inline]
Definition at line 224 of file bilininteg.hpp.
References Q.
Member Function Documentation
virtual void VectorFEDivergenceIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [inline, virtual]
Given a particular Finite Element computes the element matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 225 of file bilininteg.hpp.
void VectorFEDivergenceIntegrator::AssembleElementMatrix2 (const FiniteElement & trial_fe, const FiniteElement & test_fe, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Compute the local matrix representation of a bilinear form a(u,v) defined on different trial (given by u) and test (given by v) spaces. The rows in the local matrix correspond to the test dofs and the columns -- to the trial dofs.
Reimplemented from BilinearFormIntegrator.
Definition at line 408 of file bilininteg.cpp.
References AddMultVWt(), FiniteElement::CalcDivShape(), FiniteElement::CalcShape(), divshape, Coefficient::Eval(), IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, Q, ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), Vector::SetSize(), shape, and IntegrationPoint::weight.
Member Data Documentation
Vector VectorFEDivergenceIntegrator::divshape [private]
Definition at line 220 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
Coefficient* VectorFEDivergenceIntegrator::Q [private]
Definition at line 218 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2(), and VectorFEDivergenceIntegrator().
Vector VectorFEDivergenceIntegrator::shape [private]
Definition at line 220 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp