MFEM: DenseTensor Class Reference
DenseTensor Class Reference
Rank 3 tensor (array of matrices)
#include <densemat.hpp>
Public Member Functions
DenseTensor ()
DenseTensor (int i, int j, int k)
int SizeI () const
int SizeJ () const
int SizeK () const
void SetSize (int i, int j, int k)
DenseMatrix & operator() (int k)
double * GetData (int k)
double * Data ()
~DenseTensor ()
Private Attributes
DenseMatrix Mk
double * tdata
int nk
Detailed Description
Rank 3 tensor (array of matrices)
Definition at line 364 of file densemat.hpp.
Constructor & Destructor Documentation
DenseTensor::DenseTensor () [inline]
Definition at line 372 of file densemat.hpp.
References nk, and tdata.
DenseTensor::DenseTensor (int i, int j, int k) [inline]
Definition at line 374 of file densemat.hpp.
References nk, and tdata.
DenseTensor::~DenseTensor () [inline]
Definition at line 396 of file densemat.hpp.
References DenseMatrix::ClearExternalData(), Mk, and tdata.
Member Function Documentation
double* DenseTensor::Data () [inline]
Definition at line 394 of file densemat.hpp.
References tdata.
double* DenseTensor::GetData (int k) [inline]
Definition at line 392 of file densemat.hpp.
References DenseMatrix::Height(), Mk, tdata, and DenseMatrix::Width().
Referenced by BilinearForm::ComputeElementMatrices(), BilinearForm::ComputeElementMatrix(), and operator()().
DenseMatrix& DenseTensor::operator() (int k) [inline]
Definition at line 390 of file densemat.hpp.
References DenseMatrix::data, GetData(), and Mk.
void DenseTensor::SetSize (int i, int j, int k) [inline]
Definition at line 382 of file densemat.hpp.
References Mk, nk, tdata, and DenseMatrix::UseExternalData().
int DenseTensor::SizeI () const [inline]
Definition at line 378 of file densemat.hpp.
References DenseMatrix::Height(), and Mk.
Referenced by BilinearForm::ComputeElementMatrix().
int DenseTensor::SizeJ () const [inline]
Definition at line 379 of file densemat.hpp.
References Mk, and DenseMatrix::Width().
Referenced by BilinearForm::ComputeElementMatrix().
int DenseTensor::SizeK () const [inline]
Definition at line 380 of file densemat.hpp.
References nk.
Member Data Documentation
DenseMatrix DenseTensor::Mk [private]
Definition at line 367 of file densemat.hpp.
Referenced by GetData(), operator()(), SetSize(), SizeI(), SizeJ(), and ~DenseTensor().
int DenseTensor::nk [private]
Definition at line 369 of file densemat.hpp.
Referenced by DenseTensor(), SetSize(), and SizeK().
double* DenseTensor::tdata [private]
Definition at line 368 of file densemat.hpp.
Referenced by Data(), DenseTensor(), GetData(), SetSize(), and ~DenseTensor().
The documentation for this class was generated from the following file:
densemat.hpp