MFEM: L2_SegmentElement Class Reference
L2_SegmentElement Class Reference
#include <fe.hpp>
Public Member Functions
L2_SegmentElement (const int p)
virtual void CalcShape (const IntegrationPoint &ip, Vector &shape) const
virtual void CalcDShape (const IntegrationPoint &ip, DenseMatrix &dshape) const
virtual void ProjectDelta (int vertex, Vector &dofs) const
Private Attributes
Poly_1D::Basis & basis1d
Vector shape_x
Vector dshape_x
Detailed Description
Definition at line 1313 of file fe.hpp.
Constructor & Destructor Documentation
L2_SegmentElement::L2_SegmentElement (const int p)
Definition at line 6514 of file fe.cpp.
References dshape_x, IntegrationRule::IntPoint(), FiniteElement::Nodes, Poly_1D::OpenPoints(), Vector::SetDataAndSize(), Vector::SetSize(), shape_x, and IntegrationPoint::x.
Member Function Documentation
void L2_SegmentElement::CalcDShape (const IntegrationPoint & ip, DenseMatrix & dshape) const [virtual]
pure virtual function which evaluates the values of all partial derivatives of all shape functions at a given point ip and stores them in the matrix dshape (Dof x Dim) so that each row contains the derivatives of one shape function
Implements FiniteElement.
Definition at line 6535 of file fe.cpp.
References basis1d, DenseMatrix::Data(), FiniteElement::Dof, dshape_x, Poly_1D::Basis::Eval(), Vector::SetData(), shape_x, and IntegrationPoint::x.
void L2_SegmentElement::CalcShape (const IntegrationPoint & ip, Vector & shape) const [virtual]
pure virtual function which evaluates the values of all shape functions at a given point ip and stores them in the vector shape of dimension Dof
Implements FiniteElement.
Definition at line 6529 of file fe.cpp.
References basis1d, Poly_1D::Basis::Eval(), and IntegrationPoint::x.
void L2_SegmentElement::ProjectDelta (int vertex, Vector & dofs) const [virtual]
Compute a representation (up to multiplicative constant) for the delta function at the vertex with the given index.
Reimplemented from FiniteElement.
Definition at line 6546 of file fe.cpp.
References Poly_1D::CalcDelta(), Poly_1D::OpenPoints(), and FiniteElement::Order.
Member Data Documentation
Poly_1D::Basis& L2_SegmentElement::basis1d [private]
Definition at line 1316 of file fe.hpp.
Referenced by CalcDShape(), and CalcShape().
Vector L2_SegmentElement::dshape_x [mutable, private]
Definition at line 1318 of file fe.hpp.
Referenced by CalcDShape(), and L2_SegmentElement().
Vector L2_SegmentElement::shape_x [mutable, private]
Definition at line 1318 of file fe.hpp.
Referenced by CalcDShape(), and L2_SegmentElement().
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp