MFEM: MatrixFunctionCoefficient Class Reference
MatrixFunctionCoefficient Class Reference
#include <coefficient.hpp>
Public Member Functions
MatrixFunctionCoefficient (int dim, void(*F)(const Vector &, DenseMatrix &))
virtual void Eval (DenseMatrix &K, ElementTransformation &T, const IntegrationPoint &ip)
virtual ~MatrixFunctionCoefficient ()
Private Attributes
void(* Function)(const Vector &, DenseMatrix &)
Detailed Description
Definition at line 316 of file coefficient.hpp.
Constructor & Destructor Documentation
MatrixFunctionCoefficient::MatrixFunctionCoefficient (int dim, void(*)(const Vector &, DenseMatrix &) F) [inline]
Definition at line 322 of file coefficient.hpp.
References Function.
virtual MatrixFunctionCoefficient::~MatrixFunctionCoefficient () [inline, virtual]
Definition at line 329 of file coefficient.hpp.
Member Function Documentation
void MatrixFunctionCoefficient::Eval (DenseMatrix & K, ElementTransformation & T, const IntegrationPoint & ip) [virtual]
Implements MatrixCoefficient.
Definition at line 125 of file coefficient.cpp.
References DenseMatrix::SetSize(), ElementTransformation::Transform(), and MatrixCoefficient::vdim.
Member Data Documentation
void(* MatrixFunctionCoefficient::Function)(const Vector &, DenseMatrix &) [private]
Definition at line 319 of file coefficient.hpp.
Referenced by MatrixFunctionCoefficient().
The documentation for this class was generated from the following files:
coefficient.hpp
coefficient.cpp