MFEM: MassIntegrator Class Reference
MassIntegrator Class Reference
#include <bilininteg.hpp>
Public Member Functions
MassIntegrator (const IntegrationRule *ir=NULL)
MassIntegrator (Coefficient &q, const IntegrationRule *ir=NULL)
Construct a mass integrator with coefficient q.
virtual void AssembleElementMatrix (const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
virtual void AssembleElementMatrix2 (const FiniteElement &trial_fe, const FiniteElement &test_fe, ElementTransformation &Trans, DenseMatrix &elmat)
Private Attributes
Vector shape
Vector te_shape
Coefficient * Q
const IntegrationRule * IntRule
Detailed Description
Class for local mass matrix assemblying a(u,v) := (Q u, v)
Definition at line 118 of file bilininteg.hpp.
Constructor & Destructor Documentation
MassIntegrator::MassIntegrator (const IntegrationRule * ir = NULL) [inline]
Definition at line 126 of file bilininteg.hpp.
References IntRule, and Q.
MassIntegrator::MassIntegrator (Coefficient & q, const IntegrationRule * ir = NULL) [inline]
Construct a mass integrator with coefficient q.
Definition at line 129 of file bilininteg.hpp.
References IntRule.
Member Function Documentation
void MassIntegrator::AssembleElementMatrix (const FiniteElement & el, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Given a particular Finite Element computes the element mass matrix elmat.
Reimplemented from BilinearFormIntegrator.
Definition at line 214 of file bilininteg.cpp.
References AddMult_a_VVt(), FiniteElement::CalcShape(), IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRules, ElementTransformation::OrderW(), RefinedIntRules, FunctionSpace::rQk, ElementTransformation::SetIntPoint(), DenseMatrix::SetSize(), FiniteElement::Space(), IntegrationPoint::weight, and ElementTransformation::Weight().
void MassIntegrator::AssembleElementMatrix2 (const FiniteElement & trial_fe, const FiniteElement & test_fe, ElementTransformation & Trans, DenseMatrix & elmat) [virtual]
Compute the local matrix representation of a bilinear form a(u,v) defined on different trial (given by u) and test (given by v) spaces. The rows in the local matrix correspond to the test dofs and the columns -- to the trial dofs.
Reimplemented from BilinearFormIntegrator.
Definition at line 250 of file bilininteg.cpp.
References AddMultVWt(), FiniteElement::CalcShape(), IntegrationRules::Get(), FiniteElement::GetDof(), FiniteElement::GetGeomType(), IntegrationRule::GetNPoints(), FiniteElement::GetOrder(), IntegrationRule::IntPoint(), IntRule, IntRules, ElementTransformation::OrderW(), Q, ElementTransformation::SetIntPoint(), Vector::SetSize(), DenseMatrix::SetSize(), shape, te_shape, IntegrationPoint::weight, and ElementTransformation::Weight().
Referenced by GridFunction::GetElementAverages().
Member Data Documentation
const IntegrationRule* MassIntegrator::IntRule [private]
Definition at line 123 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2(), and MassIntegrator().
Coefficient* MassIntegrator::Q [private]
Definition at line 122 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2(), and MassIntegrator().
Vector MassIntegrator::shape [private]
Definition at line 121 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
Vector MassIntegrator::te_shape [private]
Definition at line 121 of file bilininteg.hpp.
Referenced by AssembleElementMatrix2().
The documentation for this class was generated from the following files:
bilininteg.hpp
bilininteg.cpp