MFEM: BiQuadPos2DFiniteElement Class Reference
BiQuadPos2DFiniteElement Class Reference
#include <fe.hpp>
Public Member Functions
BiQuadPos2DFiniteElement ()
virtual void CalcShape (const IntegrationPoint &ip, Vector &shape) const
virtual void CalcDShape (const IntegrationPoint &ip, DenseMatrix &dshape) const
virtual void Project (Coefficient &coeff, ElementTransformation &Trans, Vector &dofs) const
virtual void Project (VectorCoefficient &vc, ElementTransformation &Trans, Vector &dofs) const
virtual void ProjectDelta (int vertex, Vector &dofs) const
Detailed Description
Definition at line 484 of file fe.hpp.
Constructor & Destructor Documentation
BiQuadPos2DFiniteElement::BiQuadPos2DFiniteElement ()
Definition at line 1082 of file fe.cpp.
References IntegrationRule::IntPoint(), FiniteElement::Nodes, IntegrationPoint::x, and IntegrationPoint::y.
Member Function Documentation
void BiQuadPos2DFiniteElement::CalcDShape (const IntegrationPoint & ip, DenseMatrix & dshape) const [virtual]
pure virtual function which evaluates the values of all partial derivatives of all shape functions at a given point ip and stores them in the matrix dshape (Dof x Dim) so that each row contains the derivatives of one shape function
Implements FiniteElement.
Definition at line 1129 of file fe.cpp.
References IntegrationPoint::x, and IntegrationPoint::y.
void BiQuadPos2DFiniteElement::CalcShape (const IntegrationPoint & ip, Vector & shape) const [virtual]
pure virtual function which evaluates the values of all shape functions at a given point ip and stores them in the vector shape of dimension Dof
Implements FiniteElement.
Definition at line 1105 of file fe.cpp.
References IntegrationPoint::x, and IntegrationPoint::y.
void BiQuadPos2DFiniteElement::Project (VectorCoefficient & vc, ElementTransformation & Trans, Vector & dofs) const [virtual]
Given a vector coefficient and a transformation, compute its projection (approximation) in the local finite dimensional space in terms of the degrees of freedom. (VectorFiniteElements)
Reimplemented from FiniteElement.
Definition at line 1197 of file fe.cpp.
References VectorCoefficient::Eval(), VectorCoefficient::GetVDim(), IntegrationRule::IntPoint(), FiniteElement::Nodes, and ElementTransformation::SetIntPoint().
void BiQuadPos2DFiniteElement::Project (Coefficient & coeff, ElementTransformation & Trans, Vector & dofs) const [virtual]
Given a coefficient and a transformation, compute its projection (approximation) in the local finite dimensional space in terms of the degrees of freedom.
Reimplemented from FiniteElement.
Definition at line 1178 of file fe.cpp.
References Coefficient::Eval(), IntegrationRule::IntPoint(), FiniteElement::Nodes, and ElementTransformation::SetIntPoint().
virtual void BiQuadPos2DFiniteElement::ProjectDelta (int vertex, Vector & dofs) const [inline, virtual]
Compute a representation (up to multiplicative constant) for the delta function at the vertex with the given index.
Reimplemented from FiniteElement.
Definition at line 496 of file fe.hpp.
The documentation for this class was generated from the following files:
fe.hpp
fe.cpp