MFEM: coefficient.hpp File Reference
coefficient.hpp File Reference
Classes
class Coefficient
Base class Coefficient.
class ConstantCoefficient
Subclass constant coefficient.
class PWConstCoefficient
class for piecewise constant coefficient
class FunctionCoefficient
class for C-function coefficient
class GridFunctionCoefficient
class TransformedCoefficient
class DeltaCoefficient
Delta function coefficient.
class VectorCoefficient
class VectorConstantCoefficient
class VectorFunctionCoefficient
class VectorArrayCoefficient
Vector coefficient defined by an array of scalar coefficients.
class VectorGridFunctionCoefficient
Vector coefficient defined by a vector GridFunction.
class MatrixCoefficient
class MatrixFunctionCoefficient
class MatrixArrayCoefficient
Functions
double ComputeLpNorm (double p, Coefficient &coeff, Mesh &mesh, const IntegrationRule *irs[])
Function Documentation
double ComputeLpNorm (double p, Coefficient & coeff, Mesh & mesh, const IntegrationRule * irs[])
Definition at line 140 of file coefficient.cpp.
References Coefficient::Eval(), Mesh::GetElementTransformation(), Mesh::GetElementType(), Mesh::GetNE(), IntegrationRule::GetNPoints(), IntegrationRule::IntPoint(), norm(), ElementTransformation::SetIntPoint(), ElementTransformation::Weight(), and IntegrationPoint::weight.