MFEM: densemat.hpp File Reference
densemat.hpp File Reference
Classes
class DenseMatrix
Data type dense matrix.
class DenseMatrixInverse
class DenseMatrixEigensystem
class DenseMatrixSVD
class DenseTensor
Rank 3 tensor (array of matrices)
Functions
void Add (const DenseMatrix &A, const DenseMatrix &B, double alpha, DenseMatrix &C)
C = A + alpha*B.
void Mult (const DenseMatrix &b, const DenseMatrix &c, DenseMatrix &a)
Matrix matrix multiplication. A = B * C.
void CalcAdjugate (const DenseMatrix &a, DenseMatrix &adja)
Calculate the adjugate of a matrix (for 2x2 or 3x3 matrices)
void CalcAdjugateTranspose (const DenseMatrix &a, DenseMatrix &adjat)
Calculate the transposed adjugate of a matrix (for 2x2 or 3x3 matrices)
void CalcInverse (const DenseMatrix &a, DenseMatrix &inva)
Calculate the inverse of a matrix (for 2x2 or 3x3 matrices)
void CalcInverseTranspose (const DenseMatrix &a, DenseMatrix &inva)
Calculate the inverse transpose of a matrix (for 2x2 or 3x3 matrices)
void MultAAt (DenseMatrix &a, DenseMatrix &aat)
Calculate the matrix A.At.
void MultADAt (const DenseMatrix &A, const Vector &D, DenseMatrix &ADAt)
ADAt = A D A^t, where D is diagonal.
void MultABt (const DenseMatrix &A, const DenseMatrix &B, DenseMatrix &ABt)
Multiply a matrix A with the transpose of a matrix B: A*Bt.
void AddMultABt (DenseMatrix &A, DenseMatrix &B, DenseMatrix &ABt)
ABt += A * B^t.
void MultAtB (const DenseMatrix &A, const DenseMatrix &B, DenseMatrix &AtB)
Multiply the transpose of a matrix A with a matrix B: At*B.
void AddMult_a_AAt (double a, DenseMatrix &A, DenseMatrix &AAt)
AAt += a * A * A^t.
void Mult_a_AAt (double a, DenseMatrix &A, DenseMatrix &AAt)
AAt = a * A * A^t.
void MultVVt (const Vector &v, DenseMatrix &vvt)
Make a matrix from a vector V.Vt.
void MultVWt (Vector &v, Vector &w, DenseMatrix &VWt)
void AddMultVWt (Vector &v, Vector &w, DenseMatrix &VWt)
VWt += v w^t.
void AddMult_a_VVt (const double a, const Vector &v, DenseMatrix &VVt)
VVt += a * v v^t.
Function Documentation
void Add (const DenseMatrix & A, const DenseMatrix & B, double alpha, DenseMatrix & C)
C = A + alpha*B.
Definition at line 1054 of file densemat.cpp.
References DenseMatrix::Height(), and Operator::Size().
Referenced by aGMRES(), and GMRES().
void AddMult_a_AAt (double a, DenseMatrix & A, DenseMatrix & AAt)
AAt += a * A * A^t.
Definition at line 1325 of file densemat.cpp.
References DenseMatrix::Height(), and DenseMatrix::Width().
Referenced by VectorFEMassIntegrator::AssembleElementMatrix(), CurlCurlIntegrator::AssembleElementMatrix(), and DiffusionIntegrator::AssembleElementMatrix().
void AddMult_a_VVt (const double a, const Vector & v, DenseMatrix & VVt)
VVt += a * v v^t.
Definition at line 1402 of file densemat.cpp.
References DenseMatrix::Height(), mfem_error(), Vector::Size(), and DenseMatrix::Width().
Referenced by ElasticityIntegrator::AssembleElementMatrix(), DivDivIntegrator::AssembleElementMatrix(), and MassIntegrator::AssembleElementMatrix().
void AddMultABt (DenseMatrix & A, DenseMatrix & B, DenseMatrix & ABt)
ABt += A * B^t.
Definition at line 1288 of file densemat.cpp.
References DenseMatrix::Height(), mfem_error(), and DenseMatrix::Width().
Referenced by DiffusionIntegrator::AssembleElementMatrix().
void AddMultVWt (Vector & v, Vector & w, DenseMatrix & VWt)
VWt += v w^t.
Definition at line 1385 of file densemat.cpp.
References DenseMatrix::Height(), mfem_error(), Vector::Size(), and DenseMatrix::Width().
Referenced by ConvectionIntegrator::AssembleElementMatrix(), VectorDivergenceIntegrator::AssembleElementMatrix2(), DerivativeIntegrator::AssembleElementMatrix2(), VectorFEDivergenceIntegrator::AssembleElementMatrix2(), and MassIntegrator::AssembleElementMatrix2().
void CalcAdjugate (const DenseMatrix & a, DenseMatrix & adja)
Calculate the adjugate of a matrix (for 2x2 or 3x3 matrices)
Definition at line 1099 of file densemat.cpp.
References DenseMatrix::Height(), mfem_error(), and Operator::Size().
Referenced by VectorDivergenceIntegrator::AssembleElementMatrix2().
void CalcAdjugateTranspose (const DenseMatrix & a, DenseMatrix & adjat)
Calculate the transposed adjugate of a matrix (for 2x2 or 3x3 matrices)
Definition at line 1129 of file densemat.cpp.
References DenseMatrix::Height(), mfem_error(), and Operator::Size().
Referenced by RT0TetFiniteElement::GetLocalInterpolation(), RT0QuadFiniteElement::GetLocalInterpolation(), RT0TriangleFiniteElement::GetLocalInterpolation(), RT0TetFiniteElement::Project(), RT0QuadFiniteElement::Project(), and RT0TriangleFiniteElement::Project().
void CalcInverse (const DenseMatrix & a, DenseMatrix & inva)
Calculate the inverse of a matrix (for 2x2 or 3x3 matrices)
Definition at line 1159 of file densemat.cpp.
References DenseMatrix::Det(), DenseMatrix::FNorm(), DenseMatrix::Height(), mfem_error(), and Operator::Size().
Referenced by ElasticityIntegrator::AssembleElementMatrix(), VectorDiffusionIntegrator::AssembleElementMatrix(), ConvectionIntegrator::AssembleElementMatrix(), DiffusionIntegrator::AssembleElementMatrix(), DerivativeIntegrator::AssembleElementMatrix2(), VectorFiniteElement::CalcVShape_ND(), DiffusionIntegrator::ComputeElementFlux(), GridFunction::ComputeH1Error(), GridFunction::ComputeW11Error(), Geometry::Geometry(), GridFunction::GetDerivative(), GridFunction::GetDivergence(), GridFunction::GetGradients(), GridFunction::GetVectorGradient(), and Mesh::PrintCharacteristics().
void CalcInverseTranspose (const DenseMatrix & a, DenseMatrix & inva)
Calculate the inverse transpose of a matrix (for 2x2 or 3x3 matrices)
Definition at line 1204 of file densemat.cpp.
References DenseMatrix::Det(), DenseMatrix::Height(), mfem_error(), and Operator::Size().
void Mult (const DenseMatrix & b, const DenseMatrix & c, DenseMatrix & a)
Matrix matrix multiplication. A = B * C.
Definition at line 1063 of file densemat.cpp.
References DenseMatrix::data, DenseMatrix::height, mfem_error(), and Operator::size.
void Mult_a_AAt (double a, DenseMatrix & A, DenseMatrix & AAt)
AAt = a * A * A^t.
Definition at line 1346 of file densemat.cpp.
References DenseMatrix::Height(), and DenseMatrix::Width().
void MultAAt (DenseMatrix & a, DenseMatrix & aat)
Calculate the matrix A.At.
Definition at line 1240 of file densemat.cpp.
References DenseMatrix::Height(), and Operator::Size().
Referenced by ElasticityIntegrator::AssembleElementMatrix(), and VectorDiffusionIntegrator::AssembleElementMatrix().
void MultABt (const DenseMatrix & A, const DenseMatrix & B, DenseMatrix & ABt)
Multiply a matrix A with the transpose of a matrix B: A*Bt.
Definition at line 1266 of file densemat.cpp.
References DenseMatrix::Height(), mfem_error(), and DenseMatrix::Width().
Referenced by CurlCurlIntegrator::AssembleElementMatrix(), DiffusionIntegrator::AssembleElementMatrix(), and VectorFiniteElement::CalcVShape_RT().
void MultADAt (const DenseMatrix & A, const Vector & D, DenseMatrix & ADAt)
ADAt = A D A^t, where D is diagonal.
Definition at line 1252 of file densemat.cpp.
References DenseMatrix::Height(), and DenseMatrix::Width().
void MultAtB (const DenseMatrix & A, const DenseMatrix & B, DenseMatrix & AtB)
Multiply the transpose of a matrix A with a matrix B: At*B.
Definition at line 1309 of file densemat.cpp.
References DenseMatrix::Height(), and Operator::Size().
void MultVVt (const Vector & v, DenseMatrix & vvt)
Make a matrix from a vector V.Vt.
Definition at line 1358 of file densemat.cpp.
References Vector::Size().
Referenced by VectorMassIntegrator::AssembleElementMatrix().
void MultVWt (Vector & v, Vector & w, DenseMatrix & VWt)
Definition at line 1367 of file densemat.cpp.
References DenseMatrix::Height(), mfem_error(), Operator::Size(), and Vector::Size().