MFEM: error.hpp File Reference
error.hpp File Reference
#include <iostream>
Functions
void mfem_error (const char *msg=NULL)
Function Documentation
void mfem_error (const char * msg = NULL)
Definition at line 14 of file error.cpp.
Referenced by add(), Vector::Add(), SparseMatrix::Add(), DenseMatrix::AddMatrix(), SparseMatrix::AddMult(), DenseMatrix::AddMult(), AddMult_a_VVt(), AddMultABt(), SparseMatrix::AddMultTranspose(), AddMultVWt(), Mesh::AddQuadFaceElement(), SparseMatrix::AddRow(), Mesh::AddSegmentFaceElement(), SparseMatrix::AddSubMatrix(), Mesh::AddTriangleFaceElement(), DenseMatrix::AdjustDofDirection(), BilinearFormIntegrator::AssembleElementMatrix(), BilinearFormIntegrator::AssembleElementMatrix2(), BilinearFormIntegrator::AssembleFaceMatrix(), LinearFormIntegrator::AssembleRHSElementVect(), Mesh::Bisection(), CalcAdjugate(), CalcAdjugateTranspose(), FiniteElement::CalcCurlShape(), FiniteElement::CalcDivShape(), VectorFiniteElement::CalcDShape(), FiniteElement::CalcHessian(), CalcInverse(), CalcInverseTranspose(), VectorFiniteElement::CalcShape(), FiniteElement::CalcVShape(), Mesh::CheckDisplacements(), Tetrahedron::CreateRefinementFlag(), FiniteElementSpace::D2C_GlobalRestrictionMatrix(), FiniteElementSpace::D2Const_GlobalRestrictionMatrix(), DenseMatrix::Det(), DetOfLinComb(), RT0_3DFECollection::DofForGeometry(), ND1_3DFECollection::DofForGeometry(), RefinedLinearFECollection::DofForGeometry(), QuadraticDiscont3DFECollection::DofForGeometry(), LinearDiscont3DFECollection::DofForGeometry(), Const3DFECollection::DofForGeometry(), LinearNonConf3DFECollection::DofForGeometry(), CubicDiscont2DFECollection::DofForGeometry(), GaussQuadraticDiscont2DFECollection::DofForGeometry(), QuadraticPosDiscont2DFECollection::DofForGeometry(), QuadraticDiscont2DFECollection::DofForGeometry(), P1OnQuadFECollection::DofForGeometry(), GaussLinearDiscont2DFECollection::DofForGeometry(), LinearDiscont2DFECollection::DofForGeometry(), Const2DFECollection::DofForGeometry(), RT2_2DFECollection::DofForGeometry(), RT1_2DFECollection::DofForGeometry(), RT0_2DFECollection::DofForGeometry(), CrouzeixRaviartFECollection::DofForGeometry(), CubicFECollection::DofForGeometry(), QuadraticPosFECollection::DofForGeometry(), QuadraticFECollection::DofForGeometry(), LinearFECollection::DofForGeometry(), dsyev_Eigensystem(), dsyevr_Eigensystem(), OctasectedElement::Duplicate(), QuadrisectedElement::Duplicate(), BisectedElement::Duplicate(), DenseMatrix::Eigensystem(), Mesh::ElementToEdgeTable(), Mesh::ElementToElementTable(), Mesh::ElementToFaceTable(), SparseMatrix::EliminateCol(), SparseMatrix::EliminateCols(), SparseMatrix::EliminateRow(), SparseMatrix::EliminateRowCol(), DenseMatrixSVD::Eval(), DenseMatrixEigensystem::Eval(), DeltaCoefficient::Eval(), DenseMatrixInverse::Factor(), Table::Finalize(), FindPartitioningComponents(), FindRoots(), RT0_3DFECollection::FiniteElementForGeometry(), ND1_3DFECollection::FiniteElementForGeometry(), RefinedLinearFECollection::FiniteElementForGeometry(), QuadraticDiscont3DFECollection::FiniteElementForGeometry(), LinearDiscont3DFECollection::FiniteElementForGeometry(), Const3DFECollection::FiniteElementForGeometry(), LinearNonConf3DFECollection::FiniteElementForGeometry(), CubicDiscont2DFECollection::FiniteElementForGeometry(), GaussQuadraticDiscont2DFECollection::FiniteElementForGeometry(), QuadraticPosDiscont2DFECollection::FiniteElementForGeometry(), QuadraticDiscont2DFECollection::FiniteElementForGeometry(), P1OnQuadFECollection::FiniteElementForGeometry(), GaussLinearDiscont2DFECollection::FiniteElementForGeometry(), LinearDiscont2DFECollection::FiniteElementForGeometry(), Const2DFECollection::FiniteElementForGeometry(), RT2_2DFECollection::FiniteElementForGeometry(), RT1_2DFECollection::FiniteElementForGeometry(), RT0_2DFECollection::FiniteElementForGeometry(), CrouzeixRaviartFECollection::FiniteElementForGeometry(), CubicFECollection::FiniteElementForGeometry(), QuadraticPosFECollection::FiniteElementForGeometry(), QuadraticFECollection::FiniteElementForGeometry(), LinearFECollection::FiniteElementForGeometry(), SparseMatrix::Gauss_Seidel_back(), SparseMatrix::Gauss_Seidel_forw(), Mesh::GeneratePartitioning(), IntegrationRules::Get(), Mesh::GetBdrElementEdges(), Mesh::GetBdrElementFace(), Mesh::GetElementEdges(), Mesh::GetElementFaces(), Mesh::GetElementToEdgeTable(), Mesh::GetFaceBaseGeometry(), FiniteElement::GetFaceDofs(), Mesh::GetFineElemTrans(), GridFunction::GetGradient(), SparseMatrix::GetJacobiScaling(), RT0TetFiniteElement::GetLocalInterpolation(), Nedelec1TetFiniteElement::GetLocalInterpolation(), Nedelec1HexFiniteElement::GetLocalInterpolation(), RT0QuadFiniteElement::GetLocalInterpolation(), RT0TriangleFiniteElement::GetLocalInterpolation(), FiniteElement::GetLocalInterpolation(), Geometry::GetPerfPointMat(), Mesh::GetQuadOrientation(), Mesh::GetRefinementType(), SparseMatrix::GetSubMatrix(), Mesh::GetTransformationFEforElementType(), Mesh::GetTriOrientation(), Geometry::GetVertices(), DenseMatrix::GradToCurl(), DenseMatrix::GradToDiv(), GridFunction::GridFunction(), FiniteElementCollection::HasFaceDofs(), DSTable::Index(), DenseMatrixSVD::Init(), DenseMatrix::Invert(), SparseMatrix::IsSymmetric(), SparseMatrix::Jacobi(), SparseMatrix::Jacobi2(), LagrangeHexFiniteElement::LagrangeHexFiniteElement(), Array< T >::Last(), Mesh::Load(), Mesh::LocalRefinement(), ListOfIntegerSets::Lookup(), DenseMatrixInverse::Mult(), Mult(), DenseMatrix::Mult(), MultABt(), Operator::MultTranspose(), DenseMatrix::MultTranspose(), MultVWt(), FiniteElementCollection::New(), SparseMatrix::NumNonZeroElems(), Vector::operator()(), STable3D::operator()(), SparseMatrix::operator()(), DenseMatrix::operator()(), Vector::operator*(), DenseMatrix::operator*(), SparseMatrix::operator+=(), Array< T >::operator[](), IsoparametricTransformation::OrderGrad(), IsoparametricTransformation::OrderJ(), IsoparametricTransformation::OrderW(), Tetrahedron::ParseRefinementFlag(), SparseMatrix::PartMult(), SparseMatrix::Print(), SparseMatrix::PrintCSR(), SparseMatrix::PrintCSR2(), Mesh::PrintVTK(), Mesh::PrintXG(), FiniteElement::Project(), FiniteElement::ProjectDelta(), Table::Push(), STable3D::Push(), STable3D::Push4(), DSTable::Push_(), GridFunctionCoefficient::Read(), GeometryRefiner::Refine(), GeometryRefiner::RefineInterior(), SparseMatrix::SearchRow(), Vector::Set(), SparseMatrix::Set(), IntegrationRules::Set(), Mesh::SetState(), SparseMatrix::SetSubMatrix(), SparseMatrix::SetSubMatrixTranspose(), Vector::SetVector(), DenseMatrix::SingularValues(), subtract(), SparseMatrix::Symmetrize(), DenseMatrix::Symmetrize(), IntegrationRules::TetrahedronIntegrationRules(), DenseMatrix::Trace(), IntegrationRules::TriangleIntegrationRules(), Mesh::UniformRefinement(), and DenseMatrix::Weight().