MFEM: ex3.cpp File Reference
ex3.cpp File Reference
#include <fstream>
#include "mfem.hpp"
Functions
void E_exact (const Vector &, Vector &)
void f_exact (const Vector &, Vector &)
int main (int argc, char *argv[])
Variables
const double kappa = M_PI
Function Documentation
void E_exact (const Vector & x, Vector & E)
Definition at line 167 of file ex3.cpp.
References kappa.
Referenced by main().
void f_exact (const Vector & x, Vector & f)
Definition at line 174 of file ex3.cpp.
References kappa.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 34 of file ex3.cpp.
References BilinearForm::AddDomainIntegrator(), LinearForm::AddDomainIntegrator(), BilinearForm::Assemble(), LinearForm::Assemble(), Mesh::bdr_attributes, GridFunction::ComputeL2Error(), Mesh::Dimension(), E_exact(), BilinearForm::EliminateEssentialBC(), f_exact(), BilinearForm::Finalize(), Mesh::GetNE(), Array< T >::Max(), PCG(), Mesh::Print(), GridFunction::ProjectCoefficient(), GridFunction::ProjectVectorFieldOn(), GridFunction::Save(), osockstream::send(), BilinearForm::SpMat(), and Mesh::UniformRefinement().
Variable Documentation
const double kappa = M_PI
Definition at line 165 of file ex3.cpp.
Referenced by E_exact(), f_exact(), and Mesh::PrintCharacteristics().