MFEM: ex3p.cpp File Reference
ex3p.cpp File Reference
#include <fstream>
#include "mfem.hpp"
Functions
void E_exact (const Vector &, Vector &)
void f_exact (const Vector &, Vector &)
int main (int argc, char *argv[])
Variables
const double kappa = M_PI
Function Documentation
void E_exact (const Vector & x, Vector & E)
void f_exact (const Vector & x, Vector & f)
int main (int argc, char * argv[])
Definition at line 34 of file ex3p.cpp.
References BilinearForm::AddDomainIntegrator(), LinearForm::AddDomainIntegrator(), BilinearForm::Assemble(), LinearForm::Assemble(), Mesh::bdr_attributes, ParGridFunction::ComputeL2Error(), Mesh::Dimension(), E_exact(), BilinearForm::EliminateEssentialBCFromDofs(), f_exact(), BilinearForm::Finalize(), ParFiniteElementSpace::GetEssentialVDofs(), Mesh::GetNE(), ParFiniteElementSpace::GlobalTrueVSize(), Array< T >::Max(), HyprePCG::Mult(), ParLinearForm::ParallelAssemble(), ParBilinearForm::ParallelAssemble(), ParGridFunction::ParallelAverage(), ParMesh::Print(), GridFunction::ProjectCoefficient(), ParMesh::ReorientTetMesh(), ParGridFunction::Save(), osockstream::send(), HyprePCG::SetMaxIter(), HyprePCG::SetPreconditioner(), HyprePCG::SetPrintLevel(), HyprePCG::SetTol(), and Mesh::UniformRefinement().
Variable Documentation
const double kappa = M_PI
Definition at line 225 of file ex3p.cpp.