MFEM: gridfunc.cpp File Reference
gridfunc.cpp File Reference
#include "fem.hpp"
#include <cstring>
#include <math.h>
Functions
void ComputeFlux (BilinearFormIntegrator &blfi, GridFunction &u, GridFunction &flux, int wcoef, int sd)
void ZZErrorEstimator (BilinearFormIntegrator &blfi, GridFunction &u, GridFunction &flux, Vector &ErrorEstimates, int wsd)
Function Documentation
void ComputeFlux (BilinearFormIntegrator & blfi, GridFunction & u, GridFunction & flux, int wcoef, int sd)
Definition at line 1686 of file gridfunc.cpp.
References Vector::AddElementVector(), BilinearFormIntegrator::ComputeElementFlux(), GridFunction::FESpace(), FiniteElementSpace::GetElementTransformation(), FiniteElementSpace::GetElementVDofs(), FiniteElementSpace::GetFE(), FiniteElementSpace::GetNE(), Array< T >::SetSize(), Vector::Size(), and Array< T >::Size().
Referenced by ZZErrorEstimator().
void ZZErrorEstimator (BilinearFormIntegrator & blfi, GridFunction & u, GridFunction & flux, Vector & ErrorEstimates, int wsd)
Definition at line 1732 of file gridfunc.cpp.
References BilinearFormIntegrator::ComputeElementFlux(), ComputeFlux(), BilinearFormIntegrator::ComputeFluxEnergy(), GridFunction::FESpace(), FiniteElementSpace::GetAttribute(), FiniteElementSpace::GetElementTransformation(), FiniteElementSpace::GetElementVDofs(), FiniteElementSpace::GetFE(), FiniteElementSpace::GetNE(), Vector::SetSize(), Vector::Size(), and Array< T >::Size().