MFEM: mesh.cpp File Reference
mesh.cpp File Reference
#include <iostream>
#include <fstream>
#include <math.h>
#include <string.h>
#include <time.h>
#include "mesh_headers.hpp"
#include "../fem/fem.hpp"
#include "../general/sort_pairs.hpp"
Classes
struct edge_length
Functions
Element * NewElement (int geom)
void XYZ_VectorFunction (const Vector &p, Vector &v)
void FindPartitioningComponents (Table &elem_elem, const Array< int > &partitioning, Array< int > &component, Array< int > &num_comp)
void DetOfLinComb (const DenseMatrix &A, const DenseMatrix &B, Vector &c)
void swap (double &a, double &b)
int FindRoots (const Vector &z, Vector &x)
void FindTMax (Vector &c, Vector &x, double &tmax, const double factor, const int Dim)
Function Documentation
void DetOfLinComb (const DenseMatrix & A, const DenseMatrix & B, Vector & c)
Definition at line 3397 of file mesh.cpp.
References DenseMatrix::Data(), mfem_error(), Vector::SetSize(), and Operator::Size().
Referenced by Mesh::CheckDisplacements().
void FindPartitioningComponents (Table & elem_elem, const Array< int > & partitioning, Array< int > & component, Array< int > & num_comp)
Definition at line 3287 of file mesh.cpp.
References Table::GetI(), Table::GetJ(), mfem_error(), Array< T >::SetSize(), and Table::Size().
Referenced by Mesh::CheckPartitioning().
int FindRoots (const Vector & z, Vector & x)
Definition at line 3486 of file mesh.cpp.
References mfem_error(), Vector::Size(), and swap().
Referenced by FindTMax().
void FindTMax (Vector & c, Vector & x, double & tmax, const double factor, const int Dim)
Definition at line 3615 of file mesh.cpp.
References FindRoots().
Referenced by Mesh::CheckDisplacements().
Element* NewElement (int geom)
Definition at line 1074 of file mesh.cpp.
References Geometry::CUBE, Geometry::SEGMENT, Geometry::SQUARE, Geometry::TETRAHEDRON, and Geometry::TRIANGLE.
Referenced by Mesh::Load().
void swap (double & a, double & b) [inline]
Definition at line 3473 of file mesh.cpp.
void XYZ_VectorFunction (const Vector & p, Vector & v)
Definition at line 2222 of file mesh.cpp.
Referenced by Mesh::SetNodalFESpace(), and Mesh::SetNodalGridFunction().