MFEM: sparsemat.hpp File Reference
sparsemat.hpp File Reference
#include "../general/mem_alloc.hpp"
#include "../general/table.hpp"
#include "densemat.hpp"
Classes
class RowNode
class SparseMatrix
Data type sparse matrix.
Functions
void SparseMatrixFunction (SparseMatrix &S, double(*f)(double))
Applies f() to each element of the matrix (after it is finalized).
SparseMatrix * Transpose (SparseMatrix &A)
Transpose of a sparse matrix. A must be finalized.
SparseMatrix * Mult (SparseMatrix &A, SparseMatrix &B, SparseMatrix *OAB=NULL)
SparseMatrix * RAP (SparseMatrix &A, SparseMatrix &R, SparseMatrix *ORAP=NULL)
SparseMatrix * Mult_AtDA (SparseMatrix &A, Vector &D, SparseMatrix *OAtDA=NULL)
Function Documentation
SparseMatrix* Mult (SparseMatrix & A, SparseMatrix & B, SparseMatrix * OAB = NULL)
Matrix product A.B. If OAB is not NULL, we assume it has the structure of A.B and store the result in OAB. If OAB is NULL, we create a new SparseMatrix to store the result and return a pointer to it. All matrices must be finalized.
Definition at line 1176 of file sparsemat.cpp.
References SparseMatrix::GetData(), SparseMatrix::GetI(), SparseMatrix::GetJ(), mfem_error(), Operator::Size(), and SparseMatrix::Width().
SparseMatrix* Mult_AtDA (SparseMatrix & A, Vector & D, SparseMatrix * OAtDA = NULL)
Matrix multiplication A^t D A. All matrices must be finalized.
Definition at line 1296 of file sparsemat.cpp.
References Mult(), and Transpose().
SparseMatrix* RAP (SparseMatrix & A, SparseMatrix & R, SparseMatrix * ORAP = NULL)
RAP matrix product. ORAP is like OAB above. All matrices must be finalized.
Definition at line 1285 of file sparsemat.cpp.
References Mult(), and Transpose().
void SparseMatrixFunction (SparseMatrix & S, double(*)(double) f)
Applies f() to each element of the matrix (after it is finalized).
Definition at line 1125 of file sparsemat.cpp.
References SparseMatrix::GetData(), and SparseMatrix::NumNonZeroElems().
SparseMatrix* Transpose (SparseMatrix & A)
Transpose of a sparse matrix. A must be finalized.
Definition at line 1134 of file sparsemat.cpp.
References SparseMatrix::GetData(), SparseMatrix::GetI(), SparseMatrix::GetJ(), SparseMatrix::NumNonZeroElems(), Operator::Size(), and SparseMatrix::Width().