MFEM: table.hpp File Reference
table.hpp File Reference
#include "mem_alloc.hpp"
Classes
class Table
class STable
class DSTable
class DSTable::Node
class DSTable::RowIterator
Functions
void Transpose (const Table &A, Table &At, int _ncols_A=-1)
Transpose a Table.
void Transpose (const Array< int > &A, Table &At, int _ncols_A=-1)
Transpose an Array<int>
void Mult (const Table &A, const Table &B, Table &C)
C = A * B (as boolean matrices)
Function Documentation
void Mult (const Table & A, const Table & B, Table & C)
C = A * B (as boolean matrices)
Definition at line 302 of file table.cpp.
References Table::GetI(), Table::GetJ(), mfem_error(), Table::SetDims(), Table::Size(), and Table::Width().
Referenced by ElasticityIntegrator::AssembleElementMatrix(), VectorDiffusionIntegrator::AssembleElementMatrix(), DiffusionIntegrator::AssembleElementMatrix(), VectorDivergenceIntegrator::AssembleElementMatrix2(), DerivativeIntegrator::AssembleElementMatrix2(), ND_TetrahedronElement::CalcCurlShape(), L2_TetrahedronElement::CalcDShape(), L2_TriangleElement::CalcDShape(), H1_TetrahedronElement::CalcDShape(), H1_TriangleElement::CalcDShape(), GaussQuad2DFiniteElement::CalcDShape(), ND_TriangleElement::CalcVShape(), ND_TetrahedronElement::CalcVShape(), RT_TetrahedronElement::CalcVShape(), RT_TriangleElement::CalcVShape(), VectorFiniteElement::CalcVShape_ND(), Mesh::CheckDisplacements(), GridFunction::ComputeH1Error(), GridFunction::ComputeW11Error(), GridFunction::GetVectorGradient(), IsoparametricTransformation::Jacobian(), Geometry::JacToPerfJac(), Mult_AtDA(), NodalFiniteElement::ProjectGrad(), and RAP().
void Transpose (const Table & A, Table & At, int _ncols_A = -1)
Transpose a Table.
Definition at line 263 of file table.cpp.
References Table::GetI(), Table::GetJ(), Table::SetDims(), Table::Size(), and Table::Width().
Referenced by Mesh::ElementToElementTable(), Mult_AtDA(), Mesh::PrintElementsWithPartitioning(), and RAP().
void Transpose (const Array< int > & A, Table & At, int _ncols_A = -1)
Transpose an Array<int>
Definition at line 291 of file table.cpp.
References Table::AddAColumnInRow(), Table::AddConnection(), Table::MakeI(), Table::MakeJ(), Array< T >::Max(), Table::ShiftUpI(), and Array< T >::Size().