MFEM: tic_toc.cpp File Reference
tic_toc.cpp File Reference
#include <limits.h>
#include <sys/times.h>
#include <unistd.h>
#include "tic_toc.hpp"
Functions
void tic ()
Start timing.
double toc ()
End timing.
Variables
StopWatch tic_toc
Function Documentation
void tic ()
Start timing.
Definition at line 105 of file tic_toc.cpp.
References StopWatch::Clear(), and StopWatch::Start().
double toc ()
End timing.
Definition at line 111 of file tic_toc.cpp.
References StopWatch::UserTime().
Variable Documentation
StopWatch tic_toc
Definition at line 103 of file tic_toc.cpp.