MFEM: vector.cpp File Reference
vector.cpp File Reference
#include <iostream>
#include <iomanip>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include "vector.hpp"
Functions
void swap (Vector *v1, Vector *v2)
void add (const Vector &v1, const Vector &v2, Vector &v)
void add (const Vector &v1, double alpha, const Vector &v2, Vector &v)
void add (const double a, const Vector &x, const Vector &y, Vector &z)
void add (const double a, const Vector &x, const double b, const Vector &y, Vector &z)
void subtract (const Vector &x, const Vector &y, Vector &z)
void subtract (const double a, const Vector &x, const Vector &y, Vector &z)
Function Documentation
void add (const Vector & v1, const Vector & v2, Vector & v)
Definition at line 216 of file vector.cpp.
References Vector::data, mfem_error(), and Vector::size.
Referenced by add(), VectorFEBoundaryFluxLFIntegrator::AssembleRHSElementVect(), BoundaryLFIntegrator::AssembleRHSElementVect(), DomainLFIntegrator::AssembleRHSElementVect(), BiCGSTAB(), NURBS1DFiniteElement::CalcDShape(), CG(), PCG(), and SLI().
void add (const double a, const Vector & x, const Vector & y, Vector & z)
Definition at line 257 of file vector.cpp.
References add(), Vector::data, mfem_error(), and Vector::size.
void add (const double a, const Vector & x, const double b, const Vector & y, Vector & z)
Definition at line 287 of file vector.cpp.
References add(), Vector::data, mfem_error(), Vector::Set(), and Vector::size.
void add (const Vector & v1, double alpha, const Vector & v2, Vector & v)
Definition at line 230 of file vector.cpp.
References add(), Vector::data, mfem_error(), and Vector::size.
void subtract (const Vector & x, const Vector & y, Vector & z)
Definition at line 330 of file vector.cpp.
References Vector::data, mfem_error(), and Vector::size.
Referenced by aGMRES(), BiCGSTAB(), CG(), GMRES(), PCG(), SLI(), and subtract().
void subtract (const double a, const Vector & x, const Vector & y, Vector & z)
Definition at line 348 of file vector.cpp.
References Vector::data, mfem_error(), Vector::size, and subtract().
void swap (Vector * v1, Vector * v2)
Definition at line 202 of file vector.cpp.
References Vector::allocsize, Vector::data, and Vector::size.